### ISSUE TITLE
Notify VRMS of 100Automations' Team Meeting Times

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#10]
### Overview
VRMS needs to know details of 100Automations' weekly team meetings

### Dependency
project card to be added to website

### Action Items
Notify VRMS of weekly team meetings once project card issue completed 

### Resources/Instructions

[Project Card Issue](#2 )

**Comment by ExperimentsInHonesty** [comment]
opened this issue on VRMS repo https://github.com/hackforla/VRMS/issues/232

**Comment by ExperimentsInHonesty** [comment]
It still not showing up properly.  Here is our latest communication with the team: https://github.com/hackforla/VRMS/issues/232#issuecomment-683350553

**Comment by NivenPrasad** [comment]
This issue has now been fixed and the meeting times, including header, are now showing up.
