### ISSUE TITLE
Create a favicon for 100 Automations

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#100]
### Overview
We need to create a favicon for 100 Automations so our website is recognizable in browsers.

### Action Items
- [x] Create a standard favicon
- [x] Review with team

### Resources/Instructions
[How to design a favicon](https://www.creativebloq.com/illustrator/create-perfect-favicon-12112760)

**Comment by susantangux** [comment]
![100 Automations Favicon](https://user-images.githubusercontent.com/78511203/108188581-96c00680-70c4-11eb-9a9b-5bc4202d64ab.jpg)

Different favicon options w/ different branding colors and background shapes. Included Hack for LA logo for reference.

**Comment by susantangux** [comment]
I personally prefer options 16-19. I like the fact that the background is rotated like Hack for LA to show that 100 Automations is part of the H4LA family. Option 15 is the same concept but I don't like the color combination as much.

**Comment by Olivia-Chiong** [comment]
We like 16, 18 and 19. @ExperimentsInHonesty please give your comments

![image](https://user-images.githubusercontent.com/75456721/108288917-49827a00-7142-11eb-84d0-840069cae627.png)

![image](https://user-images.githubusercontent.com/75456721/108288952-5b641d00-7142-11eb-824b-f626afcd8396.png)

**Comment by Olivia-Chiong** [comment]
@susantangux could you mock these up into a browser window tab like below in both light and dark mode please.

![image](https://user-images.githubusercontent.com/75456721/108290362-12fa2e80-7145-11eb-8ce7-a8cd7f2d243b.png)

**Comment by susantangux** [comment]
4 Favicon Options in Light & Dark Mode w/ 2 tab states (active & inactive) within light and dark mode:

![Favicon 11](https://user-images.githubusercontent.com/78511203/108575929-9c8a3780-72d0-11eb-9fd0-7d261eba2b81.jpg)
![Favicon 16](https://user-images.githubusercontent.com/78511203/108575928-9c8a3780-72d0-11eb-9d00-9fbf568070c1.jpg)
![Favicon 18](https://user-images.githubusercontent.com/78511203/108575927-9bf1a100-72d0-11eb-9820-c4dacc28840e.jpg)
![Favicon 19](https://user-images.githubusercontent.com/78511203/108575922-9b590a80-72d0-11eb-9793-c23c704c9827.jpg)
Favicon 19 is problematic due to the white background blending in when tab is active in light mode

Because 16, 18, and 19 have their backgrounds rotated within the 16x16 space for favicon, the '100' icon is smaller than if we don't rotate the background, which is Option 11 for your reference and comparison.

**Comment by Olivia-Chiong** [comment]
@susantangux please edit with the following changes

1. Orange rotated background with single white gear
2. No background with orange gear
3. No background with blue and orange gear

**Comment by Olivia-Chiong** [comment]
@susantangux just saw the new options you posted in Figma. Could you do option 6/13 without the background so we can see how it looks?

**Comment by susantangux** [comment]
Sure! Will do!

**Comment by susantangux** [comment]
**5 Options:**

![Favicon 26](https://user-images.githubusercontent.com/78511203/108962628-e440f400-762d-11eb-943f-7c803b01a70c.jpg)
![Favicon 27](https://user-images.githubusercontent.com/78511203/108962862-37b34200-762e-11eb-9e4c-dad1a19c9071.jpg)
![Favicon 28](https://user-images.githubusercontent.com/78511203/108962888-3f72e680-762e-11eb-8e74-92ebdde90819.jpg)
![Favicon 29](https://user-images.githubusercontent.com/78511203/108962900-43066d80-762e-11eb-8097-bc416d2fbc86.jpg)
![Favicon 6_13](https://user-images.githubusercontent.com/78511203/108962918-47328b00-762e-11eb-8635-a67e468f587b.jpg)

**Comment by NivenPrasad** [comment]
Votes on 02.24:
26 - 4
27 - 2
29 - 4
18 - At a larger size (dynamic sizing pending)
@NivenPrasad to set up Usability Hub for 26, 27, and 29

**Comment by susantangux** [comment]
**Updated Favicon 29**
![Favicon 29_updated](https://user-images.githubusercontent.com/78511203/109119919-2a638980-76fa-11eb-9175-43bb0b5fa109.jpg)

**Comment by NivenPrasad** [comment]
Usability Hub test here: https://app.usabilityhub.com/do/24089a86036a/104b

**Comment by susantangux** [comment]
Please review this image for Favicon testing. Once approved, I'll proceed with the other 2 options.
![Favicon 26 (1)](https://user-images.githubusercontent.com/78511203/109403390-ffec1900-7911-11eb-97aa-642433bb2d5d.jpg)

**Comment by susantangux** [comment]
**Updated Images for Favicon Usability Tests:**
![Favicon 26_Usability Test](https://user-images.githubusercontent.com/78511203/109410823-95a79880-7952-11eb-990e-84d7eac99223.jpg)
![Favicon 27_Usability Test](https://user-images.githubusercontent.com/78511203/109410826-9b04e300-7952-11eb-8dff-fee84166680b.jpg)
![Favicon 29_Usability Test](https://user-images.githubusercontent.com/78511203/109410828-9dffd380-7952-11eb-848d-6651a31d19d2.jpg)

**Comment by henlatourrette** [comment]
With only 24 responses from the usability test, we've decided to ask for more responses leaving only the alternatives number 1 and 3  as options. @Olivia-Chiong  is doing the update and will publish it again in the general channel for more responses.

**Comment by henlatourrette** [comment]
We've decided to go with option 3 (the two gears). @akibrhast will upload it to the site.

**Comment by henlatourrette** [comment]
We're starting with a 32 pixel square and investigating the options for larger sizes.
