### ISSUE TITLE
Create holding landing page for website

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#101]
### Overview
Create holding landing page for website to be used once domain is redirected to website instead of wiki.

### Action Items
Product 
- [ ] Create content to go on landing page
- [ ] Include links to the following
   - [ ] overview of project
   - [ ] email button for anyone who wants to be notified of official launch.
   - [ ] if you want to join 100 Automations website team, go to volunteer page on repo
   - [ ] if you want to donate - add button to go to code for America
- [ ] Create landing page on Mailchimp

### Resources/Instructions

**Comment by henlatourrette** [comment]
It's live and working fine.
