### ISSUE TITLE
Establish Project Story Points

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#104]
### Overview
Establish project story points so we can better estimate project timeline

### Action Items
Product
- [ ] Map user stories into user stories template
- [ ] Determine priority of each story
- [ ] Determine MVP functionalities

Development
- [ ] Estimate effort required

### Resources/Instructions
[100 Automations Story Points](https://docs.google.com/spreadsheets/d/1XJOWLgtBB3Ksrae3Y89U5T09dG-zxSKJhc8UfHmiy1Q/edit?usp=sharing)

**Comment by superbunker** [comment]
superceded  by #473 - Roadmap
