### ISSUE TITLE
Create CODE OF CONDUCT file

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#107]
### Overview
Create CODE OF CONDUCT file

### Action Items

- [ ] Create CODE OF CONDUCT file: link to the Hack for LA code of conduct : https://github.com/hackforla/codeofconduct

### Resources/Instructions
See this github guide for healthy repository https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

**Comment by superbunker** [comment]
Read through the Hack for LA CoC and github community health file docs. Could use more guidance on if we'd just be swapping out "Hack for LA" as "100 Automations" or if there's deeper edits we need to make?

**Comment by Olivia-Chiong** [comment]
No edits required, just put in the code of conduct file similar to what it shows [here](https://github.com/civictechindex/CTI-website-frontend/blob/main/CODEOFCONDUCT.md) on Civic Tech Index

**Comment by superbunker** [comment]
File created.  pr #183

**Comment by henlatourrette** [comment]
Code of Conduct file created.
