### ISSUE TITLE
Iterate on Landing Page copy and buttons

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#116]
### Overview
The top portion of the Landing page is confusing and requires clarification.

### Action Items
- [ ] Clarify what the two submit buttons do and if they are the same
- [ ] Create copy to clarify what "contribute" and "submit" means
- [ ] When you click submit - it should go to a readme.md or a wiki that shows two paths for ideators or developers.

![image](https://user-images.githubusercontent.com/75456721/103708041-99c3c500-4f64-11eb-9e13-7858d0a26168.png)

### Resources/Instructions
[Landing Page on Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Comment by Olivia-Chiong** [comment]
Product would like the team to look at this page and provide feedback on the UX experience

- [ ] If you were a developer, is this clear enough? What would you like to see?
- [ ] If you were an ideator, is this clear enough? What would you like to see?

**Comment by Oskar-Adam-Zloch** [comment]
Yes! 

- Contribute word is rather not suit to be primary, it sounds more like after clicking it, I would join developers working on the 
   100 Automations page to help them. 
   
   I think that submitting new automation should be primary, and joining existing automation secondary,
   something like "Submit new" or "Join existing" would create more context.

- Main title is just repeating brand/logo name.

   What is most important that should be there? In my opinion, it's the 
   mission/values of the project, or something that participants could gain.

- Subtitle is too long, it's not an about page.
   
   It should shortly say what it is, but shouldn't be longer than 5 - 8 words.

**Comment by NivenPrasad** [comment]
@Olivia-Chiong @henlatourrette @superbunker Is this issue now redundant considering #125?
