### ISSUE TITLE
Write Bio - Site Builder: Jason Brown

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#120]
### Overview
We need some info to put on our site about you, so that we highlight your contributions.

### Action item
- [ ] Provide 
   - [ ] Name
   - [ ] Bio: _A 1-2 paragraph professional bio_
   - [ ] Quote:  _A quote from you about automations_
   - [ ] Motivations
      - [ ] Internal:  _What are your internal motivations for creating the 100 Automations site?_
      - [ ] External: _What are your external motivations for creating the 100 Automations site?_
   - [ ] Picture - _Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by superbunker** [comment]
need to work on some "personal branding" issues -- could use a week or two for this

**Comment by Olivia-Chiong** [comment]
@superbunker will have this done by 1/24

**Comment by superbunker** [comment]
On track. Will try to have it done before Saturday meeting.

**Comment by superbunker** [comment]
## Jason Brown

*Bio:* 
I’m a researcher, designer, and web developer who wants to help artists and non-profits use technology to achieve their goals. 
I’ve been an instructional technologist at Pomona College, Technical Coordinator for the Calarts School of Critical Studies, and board member of Machine Project, an arts non-profit in Los Angeles. I’m currently the executive janitor at Betalevel, a basement in Chinatown.  

*Quote:* 
There isn’t really a good place to go ask someone to make the tool that fits your need. 100 Automations is a unique resource where developers actually _want_ you to.


### Motivations

*Internal:*
Working with technology-averse faculty, I’ve called myself only half-jokingly a therapist. No one is inherently “bad” at technology, and I always find it rewarding to frame the tools in more relevant ways and make them easier to use. 

*External:*
I’ve often had to fill in all the roles on project—designer, developer, server admin. Working on 100 Automations project lets me learn from the deep expertise of everyone on the team and gain experience in collaborative development.

*Picture:* Yes
https://www.linkedin.com/in/jasonbr/

**Comment by superbunker** [comment]
swapped "internal" and "external"

seems good enough for now
