### ISSUE TITLE
Research on whether to create a template or guide for automation graphics

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#121]
### Overview
We need to research whether we need a template or guide for automation graphics.

### Action Items
- [x] Research whether a template is appropriate for automation graphics
- [x] Research whether a guide is appropriate for automation graphics
- [x] Review with team
- [ ] Add to _guides folder

**Comment by superbunker** [comment]
Suggestion that we offer project image design as one of our "value ads"

**Comment by Olivia-Chiong** [comment]
We have agreed to develop a guide for developers to either create their own logo with best practices or open an issue to get a UI designer to do it for them. @superbunker is going to draft the guide.

**Comment by superbunker** [comment]
topics for project image guide:
 - finding original art
 - check policies for use of existing logos. eg: [GitHub logo guidelines](https://github.com/logos)
 - content advice (image,text y/n?)
 - fonts, colors, layout

**Comment by NivenPrasad** [comment]
Issue for reference: https://github.com/hackforla/website/issues/707

**Comment by superbunker** [comment]
Guide drafted, still quite rough. May need to narrow the focus so it doesn't get too long?

**Comment by Olivia-Chiong** [comment]
@superbunker will update the header with 3 # and also include a menu for navigation.

**Comment by superbunker** [comment]
Guide updated—changed formatting, added menu with anchors. Still working on content for image rights/attribution details, and overall design advice. 

Question about formatting: for standards and accessibility, should we stick to the heading hierarchy? (eg: only use H3 below an H2)

**Comment by superbunker** [comment]
Converted to bullet style, reduced the design advice, focused a bit more on "don't get us sued" issues.

**Comment by NivenPrasad** [comment]
Include the following elements: 
Title 
Link
Content
Used-IN
Artist 
Provider 
Provider-Link
Image-URL 
Alt 
Type 

[From HfLA Website doc](https://docs.google.com/document/d/17AbUtj9aIA8G88O8AVJnyL1jz4cNQ3x740cmzO-2yzk/edit
)

**Comment by superbunker** [comment]
Added specific to do items to guide... haven't done them yet. 
Should have it by Saturday

**Comment by superbunker** [comment]
- Added creative commons requirements for image credits, and established Readme as best spot. (More specific H4LA image metadata might not be best for project image containing modified images?)
 - Added image credit guidelines to Resources section
 - Re-arranged sections from general to more specific (design, images, rights/attribution)

**Comment by NivenPrasad** [comment]
@susantangux can you confirm the Guide for readability/sense from your perspective or otherwise confirm it looks good?

**Comment by susantangux** [comment]
I have reviewed the Image Guide and it looks really good. I have the following comments/suggestions:

1. Section 1 title suggestion - "Finding Free Images to Avoid Copyright Infringement." The sites listed are all free sites so if people stick to them they'd be fine. I worry if they get non-CC0 images from other sources, they could potentially get into trouble and we'd have to explain the different types of image licenses (editorial use, royalty free use, etc). 

2. Very minor on formatting consistency - Sometimes section sub-titles are underlined and sometimes not

3. Section 5 Sizing Best Practice - Link at the very end of the guide (Website Image Format for the best SEO) mentioned TinyPNG and TinyJPG for image compression. It may be a good idea to mention them in Section 5 so they're at people's fingertips.

4. Minor formatting - Section 6 Text On Image: the 3 techniques under this shouldn't be labeled #7, 8, and 9. Use bullets?

**Comment by susantangux** [comment]
I've reviewed "Creating a Good Project Image" guide and it looks good! My only comment is regarding "How to Credit Images" - current guide lists 4 items for image credit: 1) Title, 2) Creator, 3) Linked Source, and 4) License, but Niven requested adding the following elements also (from HfLA Website doc): 

1. - Content
2. - Used-IN
3. - Provider
4. - Provider-Link
5. - Image-URL
6. - Alt
7. - Type

@NivenPrasad - Please confirm. Thx!

**Comment by NivenPrasad** [comment]
The list above (Content to Type) was originally included for reference but it was subsequently decided, after further work by @superbunker and then discussion amongst the team, that the final guide didn't need to include those items.

**Comment by Olivia-Chiong** [comment]
Changes merged, issue closed
