### ISSUE TITLE
Automate the updating of OKR sheet using Zapier

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#123]
### Overview
Automate the updating of OKR sheet using Zapier to make tracking WBS more efficient.

### Action Items
- [x] Create OKR labels
- [x] Set up OKR and WBS spreadsheet
- [ ] Create zap in Zapier

### Resources/Instructions
[OKR & WBS spreadsheet](https://docs.google.com/spreadsheets/d/178wkyjmXPQ8PPM8jjWElUQ0qEcsvzaa12IEAlwYf_uA/edit#gid=688048273)
[Zapier](www.zapier.com)

**Comment by Olivia-Chiong** [comment]
Progress: Zapier set up correctly, but not all labels are showing accurate, still in testing phase
Blocks: wanted to create an auto update for status from "open" to "closed"
Availability: Some availability
ETA: 1/16

**Comment by Olivia-Chiong** [comment]
Progress: Still testing status update
Blocks: Away camping this week
Availability: None
ETA: 2/4

**Comment by superbunker** [comment]
This functionality has been set up, but has not been used. If we don't need it, it should be removed.

**Comment by henlatourrette** [comment]
It seems to work but we're not using it.
