### ISSUE TITLE
Make a list of all the functions that are required on the Homepage

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#125]
### Overview
Make a list of all the functions that are required on the Homepage so we can confirm we have all the features and workflows covered.

### Action Items
Product
- [ ] Make a list of all the functions a user will use when they visit the homepage
- [ ]  Validate it against the homepage in Figma.

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Comment by NivenPrasad** [comment]
### List of functions on Homepage:
- Contribute to an in progress automation
  - maintenance
  - refactoring
  - support for user
  - documentation
  - peer review
  - to be built 
- Submit an idea for automation
- Submit a worked-on automation
- Find an automation that could be useful for my project
- View current automations
- View the status of current automations
- Read guides related to automation
- Navigate to read more about the project
- Read guides
  - Creating a good Readme for your automation
  - Documenting your automation
  - Preparing your automation for publication
  - Writing about your automation
  - Supporting your automation with community
- Suggest a guide
- Contact the project team

**Comment by NivenPrasad** [comment]
From discussion:

3 buttons by Users (with CTAs below):

Pick your path:

For Ideators:
- Have an idea for an automation

For Automation Builders:
- Help an existing automation
- Find an automation to build
- Build your own automation here

Learn more:
- Get more information

**Comment by NivenPrasad** [comment]
Action Items:

- Flows for CTAs.
- Wireframes.
- @NivenPrasad to create issues for these.

**Comment by NivenPrasad** [comment]
### Flows:

#### For Ideators:
- Have an idea for automation 
   - Visit website Home Page -> See button for submit idea -> Click on button -> 
      - Taken to Guide on Evaluating your idea -> Link in Guide to Future Automations Readme -> Click on Link -> Taken to Future Automations Readme -> Link to Future Automations Board -> Click on Link -> Taken to Future Automations Board **OR**
      - Taken to Future Automations -> Readme Link to Future Automations Board -> Click on Link -> Taken to Future Automations Board **OR**   
      - Taken to Future Automations Board

#### For Automation Builders:
- Help an existing automation
  - Visit website Home Page -> See button for contribute to an automation -> Click on button -> 
     - Automation cards filtered to show automations needing help -> Click on Readme for relevant automation **OR**
     - Taken to guide on how to contribute to automations -> Link in guide to automations needing help -> Click on link -> Taken to Home Page showing automation cards filtered for those needing help

- Find an automation to build
  - Visit website Home Page -> See button for automations ready for building -> Click on button -> 
     - Automation cards filtered to show automations with ready for development label  -> Click on Readme for relevant automation **OR**
     - Taken to guide on how to build an automation -> Link in guide to automation proposals ready for development -> Click on link -> Taken to Future Automations project board to Unclaimed Backlog **OR** Unclaimed Ideas Backlog

- Build your own automation
  - Visit website Home Page -> See button for build your own automation -> Click on button -> 
     - Taken to guide on how to build an automation -> Link in guide to start your own automation -> Click on link -> Taken to Future Automations Readme -> Link in Readme to Project Board -> Click on link -> Taken to Future Automations project board start building own

#### Learn more
- Get more information
  - Visit website Home Page -> See Learn More button -> Click on button -> 
    - Taken to Guides section on Home Page OR
    - Taken to Guides Page

**Comment by Olivia-Chiong** [comment]
## Have an idea for automation?
***
Put text here that includes the following information:
* Who gets to work the idea/bring the idea to market? (You or somebody else if you don't want/don't have the skills to do it)
* Why 100 automations would love your idea and how we would use it
* First, you submit your idea, once it is approved, you can either work on it, or builders can find it on our project board and develop it.
* Disclaimer - Once you submit an idea and we do a peer review on it, you agree to the work that is done and will host it here on 100 automations (Check with legal on terms and conditions needed)
* For non developers, have a warning that click the button will go to GitHub and explain how to fill it in.

[Self evaluating an automation idea](https://github.com/100Automations/Website/blob/master/_guides/self-evaluating-new-automation-idea.md)
[Submitting an idea for peer review](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal)

**Comment by Olivia-Chiong** [comment]
Went through the user flow on the wiki with the team and came to the decision that we need to have landing page guides.

### Ideators
* Have an idea guide page

### Builders
* How to contribute to an existing automation guide page
* How to build other automations guide page
* How to build your own automation guide page

**Comment by Olivia-Chiong** [comment]
### Want to build or contribute to an automation?

***

Automations on our site are in various levels of development. Some of them need help. Some of them are ready to use. Here's an anatomy of an automation card that tells you exactly everything you need to know about automations. (this could be a separate link)

**Comment by Olivia-Chiong** [comment]
### Want to build an automation?
***
Include more information about the process of selecting an idea etc
If you are looking for an something to build, we have a list of peer-reviewed automation proposals available for your selection [here](https://github.com/100Automations/futureautomations/projects/1#column-9876973)

**Comment by NivenPrasad** [comment]
Have started visual representation of user flows in the [Figma board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1593%3A525) in a page called "PM Sandbox".

**Comment by NivenPrasad** [comment]
@Olivia-Chiong @henlatourrette @superbunker propose we start incorporating these into the PRD instead?
[Project Requirements Summary Issue](https://github.com/100Automations/Website/issues/25)

**Comment by henlatourrette** [comment]
This issue becomes part of the issue #25 so we are closing it now.
