### ISSUE TITLE
Create a Have an idea for automation? guide

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#126]
### Overview
We need to create a guide for ideators so there is a landing page and flow for the ideator user journey.

### Dependency

#223 

## Have an idea for automation?
***
Put text here that includes the following information:
* Who gets to work the idea/bring the idea to market? (You or somebody else if you don't want/don't have the skills to do it)
* Why 100 automations would love your idea and how we would use it
* First, you submit your idea, once it is approved, you can either work on it, or builders can find it on our project board and develop it.
* Disclaimer - Once you submit an idea and we do a peer review on it, you agree to the work that is done and will host it here on 100 automations (Check with legal on terms and conditions needed)
* For non developers, have a warning that click the button will go to GitHub and explain how to fill it in.
- [ ]  Have Product review draft

### Resources/Instructions
#125 
[Self evaluating an automation idea](https://github.com/100Automations/Website/blob/master/_guides/self-evaluating-new-automation-idea.md)
[Submitting an idea for peer review](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal)

**Comment by nahyungkim1220** [comment]
Do you know how to get things done faster?

You may be a developer who is annoyed with a program, or a project manager with a brilliant idea you want to see built out. No matter who you are or your technical skills, your ideas are valuable to the open-source community! As an Ideator at 100 Automations, you can make life easier for thousands of others, and be recognized for your contributions. 

Here is how it works:
Run your idea through our [Self-Evaluating an Idea](https://github.com/100Automations/Website/blob/gh-pages/_guides/self-evaluating-new-automation-idea.md) guide. You will be able to solidify and organize your idea – such as who your automation will help and what problem it solves. 

Once you have gone through the [Self-Evaluation guide](https://github.com/100Automations/Website/blob/gh-pages/_guides/self-evaluating-new-automation-idea.md), congrats! Your idea is a step closer to coming alive.
Follow these steps to submit your idea to 100 Automations.

**If you are a developer:**
If you are a developer familiar with GitHub, you can directly submit your idea on our [Project Board](https://github.com/100Automations/futureautomations/projects/1#column-9876971), where you can see ideas that have been submitted and approved. Follow the steps on our [Workflow Guide for Ideators](https://github.com/100Automations/futureautomations/wiki/Ideators-Guide) to learn how to navigate our project board.

**If you are not a developer:**
If you are not a developer, or you aren't familiar with GitHub – no worries! You can easily submit your idea through this form(submit an idea form). 

Once our evaluation team approves your idea, you or builders can find it on our project board and develop it, depending on what you'd prefer. A disclaimer: Once you submit an idea and we do a peer review on it, you agree to the work that is done and will host it here on 100 Automations (Check with legal on terms and conditions needed).

When the automation's been brought to life, you will be accredited for developing the idea, and featured on the website along with your automation. Make sure to show off your project in your Author Bio!

If you have any questions, you can reach out to us at our [Slack](https://slack.com/app_redirect?channel=100automations) channel.

Ready to get started?
Share your ideas with the community!

**Comment by nahyungkim1220** [comment]
Question: Did we opt out of using a template to submit automation ideas? (just to make sure I'm writing the right directions by guiding ideators to GitHub).

**Comment by Olivia-Chiong** [comment]
@nahyungkim1220 we will be using a form instead of opening an issue directly.

**Comment by nahyungkim1220** [comment]
Condensed the opening line & added a bit more structure to the instructions.

**Comment by nahyungkim1220** [comment]
Move into Review after it's been revised.

**Comment by NivenPrasad** [comment]
Google form for ideas being created in #223 - added this as dependency at top of this issue. Once that is ready - update the relevant section in the guide above and we can review one more time :)

**Comment by Olivia-Chiong** [comment]
@Olivia-Chiong will review the guide and update to latest workflow.

**Comment by Olivia-Chiong** [comment]
Completed
