### ISSUE TITLE
Create Want to build an automation? guide

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#129]
### Overview
We need to create a guide for builders so there is a landing page and flow for the builders user journey.

### Action Items
If you have your own idea, read "Have an idea for an automation?"
Include more information about the process of selecting an idea etc
If you are looking for an something to build, we have a list of peer-reviewed automation proposals available for your selection [here](https://github.com/100Automations/futureautomations/projects/1#column-9876973)

### Resources/Instructions
#125

**Comment by NivenPrasad** [comment]
[This pull request](https://github.com/100Automations/Website/pull/268) should close this issue. It's also linked to #130 - for some reason the guide was created within that issue but should have been created here.
