### ISSUE TITLE
Check existing automations for Languages

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#137]
### Overview
We need to check that existing automations list languages

### Action Items
- [ ] Check pre-commit starter kit automation and update automations markdowns if necessary
- [ ] Check True GitHub contributors automation and update automations markdowns if necessary
- [ ] Check Gather Types GitHub contributors automation and update automations markdowns if necessary

### Resources/Instructions
https://github.com/100Automations/true-github-contributors
https://github.com/100Automations/jekyll-gather-data-types
https://github.com/100Automations/github-actions and  https://github.com/100Automations/pre-commit-hooks

Where the makdowns live https://github.com/100Automations/Website/tree/gh-pages/_automations

**Comment by ExperimentsInHonesty** [comment]
been replaced by #494
