### ISSUE TITLE
Assets for website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#14]
### Overview
We will collect assets to put onto website and wiki in this issue

### Action Items
- [ ] First Item
   - [ ] Workshop for Automation https://www.meetup.com/hackforla/events/qlggsrybckbdc/

### Resources/Instructions
[100 Automations Youtube Channel](https://www.youtube.com/channel/UCS_BOwZ5Hj3pGHN0gmx4gAA/?guided_help_flow=5)

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty Youtube channel now set up and Resources/Instructions section updated in Issue. Also added to Quick Links on project board

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-12-14 at 3 11 06 PM](https://user-images.githubusercontent.com/37763229/102146941-bca80100-3e1e-11eb-884c-c77a9b7d5f92.png)

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-12-14 at 3 23 26 PM](https://user-images.githubusercontent.com/37763229/102148055-9edb9b80-3e20-11eb-9610-d17c856cef84.png)



![Screen Shot 2020-12-14 at 3 23 10 PM](https://user-images.githubusercontent.com/37763229/102147909-62a83b00-3e20-11eb-8ad5-27488429a738.png)

![Screen Shot 2020-12-14 at 3 28 33 PM](https://user-images.githubusercontent.com/37763229/102148308-11e51200-3e21-11eb-9d8d-4844cf0807c7.png)

**Comment by superbunker** [comment]
Site has been soft launched. Further planning, see: #473
