### ISSUE TITLE
Create a landing page for email

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#140]
### Overview
We need to create a landing page so that people can insert their emails to be notified of website launch.

### Action Items
Design
- [x] Create Landing Page for email collection to notify people of website launch.

Product
- [x] Set up the MailChimp account and share with Design via 1Password
- [x] Re-direct DNS #4 

### Resources/Instructions
[Civic Tech Index Landing Page](http://civictechindex.org/)
[BallotNav Page](https://ballotnav.org/)
[Mailchimp Landing Page](https://mailchi.mp/405f59c3e4e5/coming-soon)

**Comment by NivenPrasad** [comment]
@CamilaArias I've just created Mailchimp account for us and the details are stored in 1Password.

**Comment by Olivia-Chiong** [comment]
Design has been approved as below:
![image](https://user-images.githubusercontent.com/75456721/106370282-5bc08380-630d-11eb-9be0-963b0db9cd69.png)

https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1632%3A0

**Comment by NivenPrasad** [comment]
Have created one but need a little help "finessing" it as current iteration doesn't reflect Figma design accurately - esp. subscribe button and other elements. Once have that, probably won't take much more and will be ready by Saturday 2/6

**Comment by NivenPrasad** [comment]
Add an About section.

**Comment by NivenPrasad** [comment]
Mailchimp Landing Page editor doesn't allow adding more pages with the free version we have. Updated [landing page](https://us7.admin.mailchimp.com/landing-pages/edit?id=27085) to have an About button that goes to project page in HfLA.

**Comment by NivenPrasad** [comment]
Keep link in About Us. Send link to @ExperimentsInHonesty so that we can point DNS there.

**Comment by Olivia-Chiong** [comment]
Revised Mailchimp landing page and have pointed DNS to 100automations.org

**Comment by ExperimentsInHonesty** [comment]
FYI - how we created the landing page:
- Hosting Plan after launch: gh-pages
- Landing page: https://100automations.org
- Repo: https://github.com/100Automations/landingpage
- index.html code used: https://github.com/100Automations/landingpage/blob/master/index.html- 
- Mail Chimp: https://mailchi.mp/6f150ef215c6/100automations
- Logistical details: We created a index.html page on a repo and pointed the domain name at the repo.  The index.html page uses an iframe to display the mailchimp content.  That way we get a customized url for our landing page, and when we are ready to turn on the actual site, we can point the domain name to the repo the developers have been working on.
- domain : managed by hfla's google domains account
- DNS is pointed at registrar interface with the following settings:

  ![Screen Shot 2021-02-19 at 1 14 26 PM](https://user-images.githubusercontent.com/37763229/108562306-82daf700-72b4-11eb-8d7d-99361e17f62a.png)
  
- GitHub settings are as following:

   ![Screen Shot 2021-02-19 at 1 21 43 PM](https://user-images.githubusercontent.com/37763229/108562897-6f7c5b80-72b5-11eb-9e3d-477b82a55d58.png)
