### ISSUE TITLE
Create a button for the Automation Card

### ISSUE THREAD

**Issue by mdothman** [100Automations/Website#146]
### Overview 
We need to create and style a button for the Automation card so it looks like the design in Figma.

### Action Items
- [ ] Create a button for our Automation Card
- [ ] Make sure it is big, blue, and centered as per the design

### Resources
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)
![image](https://user-images.githubusercontent.com/75456721/107134005-03582b80-68a3-11eb-9665-d6ed9654c0af.png)

**Comment by NivenPrasad** [comment]
[PR here](https://github.com/100Automations/Website/pull/151)
