### ISSUE TITLE
Create new design for Getting Started section

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#147]
### Overview
We need to create new design for the getting started section so it fits with the rest of the page

### Action Items
- [x] Create new getting started section
- [x] Change text to be provided by Product
- [x] Change illustrations to be gender neutral or swap gender for idea and build
- [ ] Send 3 options to Product for useability testing
- [ ] Remove dependency on #125 when done

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1593%3A525)

**Comment by Olivia-Chiong** [comment]
Change "You have your own idea and you want to build it yourself." to "You have an idea for an automation and want to submit your idea."
Change "Suggest Idea" to "Submit Idea"
Change "You want to build an automation from scratch but don’t have your own idea." to "You want to build your own approved automation idea or you want to pick an automation from an existing list of approved ideas."

**Comment by susantangux** [comment]
There are 3 options to review, each with 2 versions - difference being the illustrations for ideas guy and building gal. See attached.
![Getting Started_Option 1A](https://user-images.githubusercontent.com/78511203/107581418-e6766d80-6bac-11eb-8b99-8fd4ed2d17f3.png)
![Getting Started_Option 1B](https://user-images.githubusercontent.com/78511203/107581419-e70f0400-6bac-11eb-9f33-08c9d8235694.png)
![Getting Started_Option 2A](https://user-images.githubusercontent.com/78511203/107581420-e7a79a80-6bac-11eb-8f3d-2d4d4c2f3976.png)
![Getting Started_Option 2B](https://user-images.githubusercontent.com/78511203/107581421-e7a79a80-6bac-11eb-8fe3-d5b7dd32f2a8.png)
![Getting Started_Option 3A](https://user-images.githubusercontent.com/78511203/107581423-e7a79a80-6bac-11eb-97c1-069aaff321ee.png)
![Getting Started_Option 3B](https://user-images.githubusercontent.com/78511203/107581424-e8403100-6bac-11eb-9d67-d2894c1f4a88.png)

**Comment by CamilaArias** [comment]
Changed the text strings. I don't know if those are the "text provided by Product" or something else needs to be added. Can't join today's meeting, but Susan shared the illustrations she worked on and if you choose a set of them today, we'd have the three different layouts to test.

**Comment by Olivia-Chiong** [comment]
@susantangux please use illustrations 1 and 4 based on todays meeting. Then mock up the 3 pages for us to push out for testing.

![image](https://user-images.githubusercontent.com/75456721/107594393-b1771480-6bc6-11eb-8b50-47bc59dcc39c.png)

**Comment by susantangux** [comment]
3 Landing Page Options for Testing:
### **Option 1**
![Landing Page_Option 1](https://user-images.githubusercontent.com/78511203/107859982-d56a6e00-6df1-11eb-8434-7100bd4c492a.png)

### **Option 2**
![Landing Page_Option 2](https://user-images.githubusercontent.com/78511203/107859985-d69b9b00-6df1-11eb-9de5-e634ab7e041b.png)

### **Option 3**
![Landing Page_Option 3](https://user-images.githubusercontent.com/78511203/107859986-d69b9b00-6df1-11eb-9a28-eedb152156f8.png)

**Comment by Olivia-Chiong** [comment]
@susantangux will change top Contribute button to orange and send the above 3 options for usability test.

**Comment by susantangux** [comment]
Updated Versions for Testing (w/ Orange CTA Buttons at Top):
### **Option 1**
![Landing Page for Testing_Option 1](https://user-images.githubusercontent.com/78511203/107863990-23409f80-6e0d-11eb-936d-6d4d956ae5c7.png)

### **Option 2**
![Landing Page for Testing_Option 2](https://user-images.githubusercontent.com/78511203/107864001-2c317100-6e0d-11eb-8bc8-4e41964423d7.png)

### **Option 3**
![Landing Page for Testing_Option 3](https://user-images.githubusercontent.com/78511203/107864006-39e6f680-6e0d-11eb-81ab-4e3f302336d3.png)

**Comment by Olivia-Chiong** [comment]
@Olivia-Chiong will run usability testing with the white button options.

**Comment by Olivia-Chiong** [comment]
Usability testing set up at this link - https://app.usabilityhub.com/do/fb79b666faa1/b9b7

**Comment by Olivia-Chiong** [comment]
77% have chosen option 1 which is 3 columns for the getting started portion.

**Comment by Olivia-Chiong** [comment]
@susantangux please provide some color options for the illustrations so we can pick top 3 for usability testing.

**Comment by susantangux** [comment]
**5 Color Options:**

![Green Landing Page](https://user-images.githubusercontent.com/78511203/108968092-2de10d00-7635-11eb-9f55-dddec2cbe08e.png)
![Purple Landing Page](https://user-images.githubusercontent.com/78511203/108968101-320d2a80-7635-11eb-9e22-9d840edb0b68.png)
![Pink Landing Page](https://user-images.githubusercontent.com/78511203/108968121-39343880-7635-11eb-8411-0e9b817d8b70.png)
![Red Landing Page](https://user-images.githubusercontent.com/78511203/108968133-3b969280-7635-11eb-8646-fcd7a295d8c2.png)
![Orange Landing Page](https://user-images.githubusercontent.com/78511203/108968142-3e918300-7635-11eb-803c-bafb94cd17a3.png)

**Comment by NivenPrasad** [comment]
Team voted for purple, green and blue for Usability Hub. Next step to test usability - @NivenPrasad to set up.

**Comment by NivenPrasad** [comment]
Adding the blue one here:

![image](https://user-images.githubusercontent.com/61798667/109400168-1e074880-7915-11eb-9527-a43ec4057e16.png)

**Comment by NivenPrasad** [comment]
Usability test here: https://app.usabilityhub.com/do/ab9952fa013d/39b

@Olivia-Chiong @henlatourrette Can you test if it looks ok? We may need to update the pre-commit hooks cards for the green and purple sections and re-upload.

**Comment by susantangux** [comment]
Updated Images for Getting Started Usability Testing:
![Option 1 Purple Getting Started_R](https://user-images.githubusercontent.com/78511203/109403208-79830780-7910-11eb-9c87-03a81688d903.png)
![Option 2 Green Getting Started_R](https://user-images.githubusercontent.com/78511203/109403217-84d63300-7910-11eb-8737-5ba59aa69de7.png)
![Option 3 Blue Getting Started_R](https://user-images.githubusercontent.com/78511203/109403219-899ae700-7910-11eb-8de8-fd59b3496cf0.png)

**Comment by NivenPrasad** [comment]
@NivenPrasad to update tests and publish on Monday 03/1

**Comment by NivenPrasad** [comment]
@CamilaArias @susantangux 

### Looks like Blue is the winner!

![image](https://user-images.githubusercontent.com/61798667/109901251-bfb8cd80-7c66-11eb-9976-81b7c06a1c29.png)
