### ISSUE TITLE
Validate information collection from automation creators for website content

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#15]
### Overview
We need to review the information we intend to collect from automation creators, so that we can present each automation in a way that is valuable to our audience

### Action Item
- [x]  Review the template below with Automation Creators on the Ops group, and identify any additional information they would like to see.
   - [ ] Update the template
- [ ] Review the template with Automation implementers e.g. people outside our organization or otherwise

### Resources
Ops team meeting, Tuesday 8pm PDT  [zoom link](https://us02web.zoom.us/j/410239238?pwd=WXFZbXBNUFVyUkZ1NkRJcEZxMVJOUT09)
TDM Calculator meeting, Wed 7pm PDT [Zoom link](https://zoom.us/j/97719222309?pwd=VS8xdWV3U3o3Z1JBVnZaV2plVXE2dz09)

```
### Overview
Provide collateral for the OpenSourceAutomations.org website

### Action Items
- [ ]   Gather items
  - [ ]  600 x 400 image
     - [ ]  Alt image text
  - [ ]  Name of automation
  - [ ]  A blurb about the automation
  - [ ]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [ ]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [ ]  If you are looking for collaborators - What you are looking for skills wise
  - [ ]  Status (in use, depreciated, needs update - and any other status you can think of)
     - [ ] If status in use, what codebase can it be seen in?
- [ ]   Add automation Card to website

### Resources/Instructions
See project cards on the hackforla.org website for general idea, although the format of these will be different.
```

**Comment by NivenPrasad** [comment]
Ops meeting 7/28 input:
- Create harness repo that would make it easy to incorporate other scripts or executable automations as opposed to elaborate automation app
- See for reference: Standards for organizing Unix POSIX tooling directories: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
- See for reference: Standards for Unix POSIX file system layouts: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by NivenPrasad** [comment]
This has been validated us much as we're able to until we have mock-ups of the website.
