### ISSUE TITLE
Get rid of inline `style` tags

### ISSUE THREAD

**Issue by mdothman** [100Automations/Website#160]
### Overview

100 Auotmations website contains some inline style tags that in best practice are absent. These styles will not show up otherwise. @mcspach has previously incorporated styling without the use of inline styles. See issue #148.  

![styletags](https://user-images.githubusercontent.com/56901689/108289003-78005500-7142-11eb-96b1-8ad25fed52c9.jpg)

### Action Items

[x ] - Remove inline `style` tags
[x ] - Comment what changes you made

### Resources/Instructions

Please read this article on [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**Comment by mcspach** [comment]
@NivenPrasad @Olivia-Chiong It doesn't seem like I have the clearance to self-assign, or change anything in the righthand column of issues on this project board. 
Do you know if that can be changed? 
Thanks.

**Comment by Olivia-Chiong** [comment]
@mcspach I've updated your permissions, I think it should be fixed now, but let me know if its not.

**Comment by mcspach** [comment]
@Olivia-Chiong thank you. Working now.

**Comment by mcspach** [comment]
<img width="650" alt="Screen Shot 2021-03-03 at 12 11 22 PM" src="https://user-images.githubusercontent.com/38964454/109867049-ed782500-7c1a-11eb-9e49-1cbfe2ffb6bf.png">
These inline styles were not required. The specificity of cascading styles is already working. 
You can see the element attributes in the screenshot. 
Code removed [style="font-family: Poppins; color="white"]
