### ISSUE TITLE
Redirect domain URL to index.html on gh-pages

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#161]
### Overview
We need to frame the domain URL to index.html on gh-pages.

### Action Items
- [x] Create a landing page repository
- [x] Upload a index.html into it that frames Mailchimp
- [x] connect 100automations.org to the repo and activate gh-pages on it.

### Resources/Instructions
[Mailchimp Link](https://mailchi.mp/6f150ef215c6/100automations)
[Iframe resource](https://github.com/hackforla/website/blob/gh-pages/dashboard.html)
[landing page repository](https://github.com/100Automations/landingpage)

**Comment by ExperimentsInHonesty** [comment]
@mdothman I added a index.html blank page on the repo and the domain name is pointing to it.  You can replace that with the index.html with an iframe.

**Comment by mdothman** [comment]
Here is what I've done so far. 

![screencapture-file-C-Users-Beelzebub-Desktop-Professional-landingpage-index-html-2021-02-18-15_35_13 (1)](https://user-images.githubusercontent.com/56901689/108435916-4c8f7000-71ff-11eb-9bc1-0c815007b062.png)

**Comment by mdothman** [comment]
@ExperimentsInHonesty here is the [pr](https://github.com/100Automations/landingpage/pull/3)

**Comment by Olivia-Chiong** [comment]
@mdothman it's been merged. Thank you so much, looks good!
