### ISSUE TITLE
Create a dropdown for needs help button on automation cards

### ISSUE THREAD

**Issue by mcspach** [100Automations/Website#162]
### Overview
Each Automation card needs the button in upper lefthand corner to dropdown list of all roles that are needed on the project.

### Action Items
- [x] Make button clickable, and list hidden when page loads.
- [x] Add list of 'needs help' roles that toggles when button is clicked. 

### Resources/Instructions
Use Figma if needed.

<img width="352" alt="Screen Shot 2021-02-20 at 8 49 13 AM" src="https://user-images.githubusercontent.com/38964454/108602742-858f2800-7358-11eb-8436-0c507ff4db80.png">

**Comment by Olivia-Chiong** [comment]
@mcspach please reference to Figma when you are working on this. The dropdown should be on the right.

**Comment by mcspach** [comment]
UPDATE: Dropdown is on the right. It is now clickable, and reveals (or hides) a list of needed roles when its clicked. 


@CamilaArias and @susantangux  --- This is not identical to the Figma, but the way it is currently designed with the flag coming outside the automation card and then the dropdown list appearing in front of the card will take some work. Is this a sufficient substitute, or do I need to figure out how to match Figma perfectly?

<img width="356" alt="Screen Shot 2021-02-23 at 10 28 33 PM" src="https://user-images.githubusercontent.com/38964454/108960301-8bbc2780-762a-11eb-8dfe-9a8cf5246037.png">
<img width="344" alt="Screen Shot 2021-02-23 at 10 58 53 PM" src="https://user-images.githubusercontent.com/38964454/108960472-d3db4a00-762a-11eb-9f40-626a37596120.png">

**Comment by henlatourrette** [comment]
@mcspach will reposition the button above the card - and make the border radius of the card in that corner will be zero - square.

**Comment by mcspach** [comment]
New positioning for the button and list elements. 
<img width="469" alt="Screen Shot 2021-03-01 at 4 36 27 PM" src="https://user-images.githubusercontent.com/38964454/109579437-ba645300-7aad-11eb-8567-20ae30f98f2f.png">
<img width="447" alt="Screen Shot 2021-03-01 at 4 36 32 PM" src="https://user-images.githubusercontent.com/38964454/109579472-ccde8c80-7aad-11eb-8af2-d2dce9742987.png">

**Comment by Olivia-Chiong** [comment]
@mcspach will be updating the style of the card to be closer to the Figma component.

**Comment by mcspach** [comment]
<details><summary>screenshot-button</summary>
<img width="392" alt="Screen Shot 2021-03-10 at 11 45 13 AM" src="https://user-images.githubusercontent.com/38964454/110688111-14dc6e00-8196-11eb-9bff-f645ed1f2d4d.png">
</details>
<details><summary>screenshot-dropdown</summary>
<img width="394" alt="Screen Shot 2021-03-10 at 11 44 54 AM" src="https://user-images.githubusercontent.com/38964454/110688072-0b530600-8196-11eb-9578-7641c05f8eef.png">
</details>

Checked newest Figma component in Design System and matched:
padding, text-weight, line-height, capitalize, border-radius, height/width, etc.

On Figma there is a 100% inconsistency rate with this element in Final Pages.

**Comment by henlatourrette** [comment]
@Olivia-Chiong  will take a look at the pull request to merge it.
