### ISSUE TITLE
Update new automation image size

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#164]
### Overview
We need to update the new automation image size (744 by 300) across all documentation that mentions it

### Action Items
- [x] guide for image creation
- [x] automation template

**Comment by superbunker** [comment]
PR #168 - in "good project image" guide changed first line of design tips to add image size

PR #169 - in "prep automation" guide, corrected size, added note about display size, removed old example images

**Comment by superbunker** [comment]
Checking the guides, I didn't see other references to a specific size aside from the two above.

A higher level comment: I think I'd be best to target this type of formatting advice to contributors who already have an image in hand or in mind, and who already have some basic familiarity with how to do it. Having 100 Automations create project images would be a nice value-add for contributors who don't already have an image (or who have a bad image) and would be pretty minimal work on our part.

**Comment by henlatourrette** [comment]
Image size changes have been made on template.
