### ISSUE TITLE
Create video for how to take and present screenshots

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#165]
### Overview
We need to have a video that shows how to take and present screenshots as a project standard

### Action Items
- [ ] create a video to show the steps
- [ ] upload it to the google drive and link into the Wiki

**Comment by NivenPrasad** [comment]
Status: In progress
Blockers: None
Availability: Available
Eta: Ready by Saturday 02/27

**Comment by NivenPrasad** [comment]
Status: In progress
Blockers: None
Availability: Been
Eta: Ready by Saturday 03/20

**Comment by NivenPrasad** [comment]
![image](https://user-images.githubusercontent.com/61798667/111883748-d52a3900-8982-11eb-802c-ee973134f101.png)

**Comment by NivenPrasad** [comment]
![image](https://user-images.githubusercontent.com/61798667/111884212-c1340680-8985-11eb-9ee6-cc6465b0e8d6.png)

**Comment by NivenPrasad** [comment]
Video uploaded to [100 Automations G Drive here](https://drive.google.com/file/d/1-ZLzmbP6mdtdFxhyzu_CyrBcsBnsZONv/view?usp=sharing)

**Comment by henlatourrette** [comment]
@NivenPrasad will share the link at the wiki.
