### ISSUE TITLE
Research other open source automation repos on GitHub

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#17]
### Overview
Find out how other open source automation repos approach creating automations to see what we can implement with our own automations.

### Action Items

- [x] Search Github for 3-4 open source automation repos
- [x] Fill out competitive analysis template

### Resources/Instructions
[Competitive analysis template](https://docs.google.com/spreadsheets/d/1eEx5xuqgYcTF_0qHFsa0hRfcpBmeY5Lf5iyLy9O2hCo/edit?usp=drive_web&ouid=115147153382252034796)

[Example of competitor](http://theautomatic.net/)

**Comment by ExperimentsInHonesty** [comment]
Most of the resources on the web are just articles about major open source projects leaving out all the little interesting projects.  
There is this though
https://npm.community/
https://www.npmjs.com/package/liveql (here is my friends project.  It seems to be getting attention long after being published).  So this should be part of our process.

**Comment by NivenPrasad** [comment]
Done.
