### ISSUE TITLE
Revise Guides wireframe design

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#174]
### Overview
We need to revise the guides wireframe design to reflect the new menu engineering is going to implement

### Action Items
- [ ] Engineering will provide screenshots for current menu options
- [ ] UI/UX will review the menu structure and provide a redesign

### Resources/Instructions
@akibrhast please include screenshots here

**Comment by Olivia-Chiong** [comment]
Once @akibrhast has included the screenshots, we will wait for discussion with @superbunker before moving on towards redesign.

**Comment by akibrhast** [comment]
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/32349001/109610067-3f755980-7afa-11eb-8b54-20e26ad9ee05.png)

</details>

**Comment by akibrhast** [comment]
Consider a layout where this wouldnt happen for the toc in mobile
![image](https://user-images.githubusercontent.com/32349001/109895339-0b667980-7c5d-11eb-9ed2-2539bce565e3.png)

**Comment by henlatourrette** [comment]
@CamilaArias will create an issue to create component for the table of contents on desktop and mobile, and clean up design with constraints and spacing for the whole page

**Comment by henlatourrette** [comment]
@superbunker  will  put a guide that is more representative for the purpose of formating and  @akibrhast can run  it through the code so we could see what it looks like before bring it to design.

**Comment by akibrhast** [comment]
> Hey Akib. Here’s two, that have different heading lengths —
> - https://github.com/100Automations/Website/blob/gh-pages/_guides/self-evaluating-new-automation-idea.md
> - https://github.com/100Automations/Website/blob/gh-pages/_guides/creating-good-project-images.md
> Could we see how the both work? 
>@superbunker 

<details>
<summary>Self Evaluating a New Automation Idea</summary>

![image](https://user-images.githubusercontent.com/32349001/111051177-1ec4d200-841f-11eb-8787-7dfeeb124953.png)

</details>

<details>
<summary>Creating A Good Project Image</summary>

![image](https://user-images.githubusercontent.com/32349001/111011346-0beec680-8367-11eb-84ec-5faf2c6c3b95.png)

</details>

**Comment by akibrhast** [comment]
@akibrhast Redo screenshots using root16px-- something something to do with rem on paragraphs. Look at hack4la stuff and double check with @CamilaArias

**Comment by akibrhast** [comment]
I would like some assistance regarding this, cause I am a bit unclear on what to do next

**Comment by Olivia-Chiong** [comment]
@akibrhast We need to set the root for the page to be 16 px. That way we can use REM to size up the fonts as needed. Does that make sense for you? If not, could you book a time with me to discuss this? Thanks.

**Comment by akibrhast** [comment]
Conceptually I understand I think @Olivia-Chiong . But what I do not understand is , where do I set the root of the page in context of this projects hierarchy .
![image](https://user-images.githubusercontent.com/32349001/111417304-f73e6580-86bb-11eb-968d-f3a3843b5558.png) 
????

- Should I set it in an arbitary scsss file?
- Should I create a _typography.scss file like hackforla and put it in there?
- Where should the _typography.scss file go?
- Should it go within includes? guides?
- Why is there a _sass/includes in the first place.. That's a bit confusing and does not make sense atm...
- I will edit this comment when I think up new questions...

**Comment by superbunker** [comment]
@akibrhast For right now, I think we just need a demo that uses a base 16px font. You can set that by making the the body font size 16px.

**Comment by akibrhast** [comment]
UPDATED IMAGE

<details>
<summary>Self Evaluating A New Automation Idea</summary>

![image](https://user-images.githubusercontent.com/32349001/111559291-9ddf4080-8766-11eb-8053-76fd97f7c5ac.png)

</details>

<details>
<summary>Creating a Good Project Image</summary>

![image](https://user-images.githubusercontent.com/32349001/111559334-ae8fb680-8766-11eb-83e3-80e26ab1ee44.png)

</details>

**Comment by henlatourrette** [comment]
We have decided on this format for the Guides Table of Contents:

![image](https://user-images.githubusercontent.com/21250505/112400451-29b51780-8ce7-11eb-8ef6-15f8b92e749b.png)

Next Steps:

* @akibrhast can you comment on functionality ?
*  @susantangux to mock a page with screenshot images.

**Comment by NivenPrasad** [comment]
@susantangux you can use this screenshot for the mockup: ![Future Automations Workflow New Ideas Ice Box](https://user-images.githubusercontent.com/61798667/106541571-46478700-64d0-11eb-80a6-049c6137d0ff.jpg)

**Comment by henlatourrette** [comment]
This is being worked on #191
