### ISSUE TITLE
Create site map with UI/UX navigation flow

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#18]
### Overview
We need to create a flexible structure for the website to accommodate MVP requirements and growth beyond.

### Dependency
Requirements gathering summary Issue #25  

### Action Items
- [ ] Product/UI/UX
  - [ ] Review requirements summary with UI/UX team
  - [ ] Ideate on potential designs
- [ ] UI/UX
  - [ ] Create site map
    - [ ] Review with Product
  - [ ] Create style guide issue #20 
    - [ ] Review with Product
  - [ ] Build low-fi mock-ups
    - [ ] Get sign-off
  - [ ] Build hi-fi mock-ups
    - [ ] Get sign-off

### Resources/Instructions
- [Website requirements summary](https://docs.google.com/document/d/1GvI9SssKWr0ewXgjM9qCEB8rSgmKyQpiLKZt2PbGafM/edit?usp=drive_web&ouid=115147153382252034796)
- [Hack for LA Website](www.hackforla.org)

**Comment by Olivia-Chiong** [comment]
![image](https://user-images.githubusercontent.com/75456721/103105919-e1059980-45e5-11eb-823f-331112f88be8.png)
Reference: https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=25%3A0

**Comment by superbunker** [comment]
This refers to the website architecture with Design MVP milestone.
It's done.
