### ISSUE TITLE
Decide/develop our own style guide

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#20]
### Overview
Develop style guide for the overall navigation and visual appearance of the site.

### Action Items
- [x] Define a color guide
- [x] Define a typography system
- [x] Create key components

### Resources/Instructions
- Figma File: https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363
- Reference to [Hack for LA Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

**Comment by Olivia-Chiong** [comment]
@CamilaArias Bonnie shared this [style guide](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3686%3A93) for the hack for LA website and was wondering if we could develop the same for this project. Are you able to take a look and let us know if you are able to work on this?

**Comment by NivenPrasad** [comment]
Progress: This has been started in Figma: ["Tokens and Components" page](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)
Blocks: None
Availability: Available
Eta: 2 weeks

**Comment by NivenPrasad** [comment]
@CamilaArias is away until January 3, 2021.

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty will add @CamilaArias to UI/UX board.

@CamilaArias and @mdothman will meet to discuss best practices for style guide.

**Comment by Olivia-Chiong** [comment]
@CamilaArias and @mdothman are still working together with the team from Hack for LA website and will provide updates next week.

**Comment by CamilaArias** [comment]
Still very busy with work this week, but I will get back to working on this again this weekend onwards. I will break it up in smaller tasks, components and phases and track it on Figma, will post update then.

**Comment by Olivia-Chiong** [comment]
@CamilaArias is putting together the list of tasks to do here - https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363
and we can convert some into issues.

S - no need to think, quick task that takes 5-10 mins
M - needs a bit of thinking and then working for 45 mins - 60 mins
L - Needs thought process before working on it, could take 1-2 hours
XL - Ambiguious task that requires thinking before start working on it

**Comment by henlatourrette** [comment]
Close this issue when all the desing issues have been created.

**Comment by henlatourrette** [comment]
Proposing a working session to create all issues on Sat March 20th, 2021.

**Comment by NivenPrasad** [comment]
Notes: Design System - too much work - need some more detail from developers. Then do a lean handoff to developers. Design System can come after that. Setting expectations around "design system".

Handoff to include:

1. [Autolayout - for all pages Constraints - for all pages](https://github.com/100Automations/Website/issues/216)
2. [Colors for each of mobile and desktop, Typescale for each of mobile and desktop, Layout (Grid for mobile and desktop, navigations of footer and header for mobile and desktop)](https://github.com/100Automations/Website/issues/217)
3. [Components - developer specs](https://github.com/100Automations/Website/issues/218)
4. [Exportable assets (eg. SVGs) - for all pages](https://github.com/100Automations/Website/issues/219)

**Comment by superbunker** [comment]
we totally have styles
