### ISSUE TITLE
Create site framework

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#208]
### Overview
We need to create a site framework so we can move away from MDL

### Action Items
- [x] Come up with folders hierarchy
- [x] Create scss variables
- [x] Format of variables naming convention
- [x] create typography.scss
- [x] create colors.scss
- [x] create containers.scss (padding, spacing, margin, border, display, grids etc)
- [x] create buttons.scss
- [x] create cards.scss

### Resources

**Comment by mdothman** [comment]
I will be typing a up a document for explaining the folder hierarchy and variables naming convention to place in site architecture document. Expected to complete by 04/07/2021.

**Comment by mdothman** [comment]
There are several folders in the `_sass` folder: Components, Guide, Includes, and variables.
The components folder will contain re-usable components such as buttons, cards, and the flexbox.

The guide folder will contain the styles for our guides layout. The Includes folder is going to style all of the elements in our includes folder: Header, Footer, Action card, etc.

The Variables folder will contain our css varaibles for our colors and typography. The variables can be used in the css to style elements and keep our elements standardized. 

Font variables will define the different types, weight, and size. The color variables define the different colors used in the site.

**Comment by henlatourrette** [comment]
The Framework has been created.
