### ISSUE TITLE
Finalize Guide Page

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#210]
### Overview
We need to finalize the guide page layouts and include all components from new site framework

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style guide page according to design

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2187%3A2227)

**Comment by superbunker** [comment]
Is this redundant? #322

**Comment by superbunker** [comment]
Clarification: this is for the individual guide page layouts. #322 is for the "all guides" page.

I think this one can be closed.

**Comment by NivenPrasad** [comment]
@superbunker Agree!
