### ISSUE TITLE
Finalize Homepage

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#211]
### Dependency
#208 #209 
(add issue for design dependency)

### Overview
We need to finalize the front page layouts and include all components from new site framework

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style homepage according to design
- [x] Four sections [Dependencies]
   - [x] Hero - https://github.com/100Automations/Website/issues/212
   - [x] Automations - https://github.com/100Automations/Website/issues/213
   - [x] Getting Started - https://github.com/100Automations/Website/issues/214
   - [x] Guides - https://github.com/100Automations/Website/issues/215

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Comment by mcspach** [comment]
Almost done. I made a few changes today to solve spacing issues, etc. 
1 problem, gears appear above text in hero. I will ask @mdothman for help on that. After that we can ask for final review on homepage and make last changes for MVP. I will push changes to 'development' branch now and wait for next steps.
![image](https://user-images.githubusercontent.com/38964454/116135280-c6bbf500-a685-11eb-8895-0bf8deb8845b.png)

**Comment by mcspach** [comment]
Asked cami for some specific instructions on finalizing this page styling, I will do my best to have all the changes made by Saturday.

**Comment by mcspach** [comment]
@mdothman I will complete hero and guide cards, you can take over automation cards. How does that sound?

**Comment by mdothman** [comment]
We should discuss over slack, 10-15 minute call.

**Comment by mdothman** [comment]
I will pass off Hero Section to @mcspach after I have added mobile styling, and finish the automation section.

**Comment by NivenPrasad** [comment]
@mcspach You might have seen already but note the Figma update on the guides section at the bottom of the Home page.
cc: @CamilaArias @susantangux

**Comment by henlatourrette** [comment]
We need to remove the "Suggest a Guide" button and leave the "See all guides" button below the "Guides" links. Also, the "Get involved" button needs to be aligned to the paragraph above.

**Comment by henlatourrette** [comment]
We need to fix the lines - there are fewer lines on the figma but on the website there are some orphan words like "it":
![image](https://user-images.githubusercontent.com/21250505/120401896-f1493f80-c30e-11eb-80ed-6545f143548f.png)

**Comment by superbunker** [comment]
its final
