### ISSUE TITLE
Finalize Hero Section for Homepage

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#212]
### Overview
We need to finalize the hero section for the homepage.

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style hero section according to design
- [x] Add [working link](https://github.com/100Automations/Website/blob/gh-pages/_pages/creator_overview.md) to "Contribute" button 

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2187%3A2227)

**Comment by mcspach** [comment]
-Problem with Z-Index on small screen sizes. We need to make sure the gears appear behind text in this section. 
-Otherwise it is good for MVP.

**Comment by mcspach** [comment]
Still need help solving the z-index issue. Please let me know if you have any suggestions @mdothman.

**Comment by superbunker** [comment]
z-index issue fixed!
But the wavy whoop-dee-doo has margins left and right exposing the underlying blue

**Comment by superbunker** [comment]
The button is off to the left edge. It's always something.  

The whoopty SVG is lightly glitching — especially visible when slowly resizing the window (at least for me, Safari/Mac)

**Comment by superbunker** [comment]
Button fixed - yay!

The whoopy glitch gray line is only showing up on Safari/Mac (?) and only(?) with window resizing. It's not a major bug. So let's call it good enough for now.

**Comment by henlatourrette** [comment]
It looks good for MVP
