### ISSUE TITLE
Finalize Automations section

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#213]
### Overview
We need to finalize the automations section for the homepage.

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style automations cards according to design
- [x] Style automations section according to design
- [x] Add [working link](https://github.com/100Automations/futureautomations/wiki/Use-An-Automation) to "automation implementation"
 

### Resources/Instructions
[Automation Card Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1432%3A998)
[Homepage Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2187%3A2227)

**Comment by henlatourrette** [comment]
We added a working link to the "automation implementation" text but we removed that text from the home page until we have more automations available.
