### ISSUE TITLE
Finalize the Getting Started section

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#214]
### Overview
We need to finalize the getting started section for the homepage.

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style getting started section according to design
- [x] Add working links to the following buttons
   - [x] [Submit idea](https://github.com/100Automations/Website/blob/gh-pages/_pages/submit_idea.md)
   - [x] [Start Building](https://github.com/100Automations/Website/blob/gh-pages/_pages/start_building.md) 
   - [x] [Start Contributing](https://github.com/100Automations/Website/blob/gh-pages/_pages/start_contributing.md)
- [x] Center the text on the images in the Getting Started section.
-
### Resources/Instructions
[Homepage Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2187%3A2227)

**Comment by henlatourrette** [comment]
We will rephrase the text inside each card of the "Submit Your Automation" section. And also, we have to align the text to the Top and Centered.

**Comment by henlatourrette** [comment]
We agree on Centering the text on the images in the Getting Started section.

**Comment by mcspach** [comment]
<img width="1320" alt="Screen Shot 2021-06-09 at 10 50 28 AM" src="https://user-images.githubusercontent.com/38964454/121405681-30c8ea80-c912-11eb-88cd-a9a151d53a77.png">
We decided to center the text and that was the last action item. Linked pull request today
