### ISSUE TITLE
Finalize Guides Section

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#215]
### Overview
We need to finalize the guides section for the homepage.

### Action Items
- [x] Get finalised design from UI/UX
- [x] Style guides section according to design

### Resources/Instructions
[Homepage Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2187%3A2227)

**Comment by mcspach** [comment]
May be waiting on 'development' branch to be merged with 'gh-pages'. But Guide Card Section is complete.
