### ISSUE TITLE
Create Autolayout - for all pages Constraints - for all pages

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#216]
### Overview
We need to create autolayout and constraints for all pages.

### Action Items

- [ ] Create autolayout and constraints for:
  - [ ] Home Page
  - [ ] About Us
  - [x] Guide
  - [x] Press Kit
- [x] Review against current styles
- [ ] Review with development team

### Resources/Instructions
[Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1899%3A1)

**Comment by superbunker** [comment]
Since all layouts have been made, this issue no longer seems relevant
