### ISSUE TITLE
Complete Style Guide and Layout

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#217]
### Overview
We need to complete the style guide which includes:
- Colors 
- Typescale for each of mobile and desktop
- Layout (Grid for mobile and desktop and navigations of footer and header for mobile and desktop)

### Action Items
- [x] Verify all color styles are correct
- [x] Verify typescales are correct for
  - [x] Mobile
  - [x] Desktop 
- [ ] Review grid with developers for:
  - [x] Mobile
  - [x] Desktop
- [x] Add specs for header and footer in nav bar  

### Resources/Instructions
[Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1899%3A1)

**Comment by superbunker** [comment]
This looks complete. Moving to review to confirm.
