### ISSUE TITLE
Create Components for Developer Specs

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#218]
### Overview
We need to add visual specs for all components on each page (example buttons, cards, filters)

### Action Items

- [ ] Add visual specs for all components on each page 
  - [ ] Verify example buttons for each page
  - [ ] Verify cards for each page
  - [ ] Verify filters for each page

### Resources/Instructions
[Figma Board]()

**Comment by henlatourrette** [comment]
@CamilaArias will include the actions inside this issue as steps on other issues for each page.

**Comment by superbunker** [comment]
Components created!
