### ISSUE TITLE
Get exportable assets ready to export to corresponding containers

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#219]
### Overview
All exportable assets (images, icons, svg) should be ready to export in their corresponding containers.

### Action Items
- [ ] Review that we have all exportable assets
- [ ] Export all assets to corresponding containers

### Resources/Instructions
[Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1899%3A1)

**Comment by superbunker** [comment]
Does this still need to be open?

**Comment by superbunker** [comment]
They're totally exportable
