### ISSUE TITLE
Fix typo in Getting Started image

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#221]
### Overview
Fix typo in center image: HTLM 

### Action Items
- [x] replace current image with HTLM --> HTML

### Resources/Instructions
[figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A7443)

<img width="309" alt="Screen Shot 2021-03-23 at 2 22 21 PM" src="https://user-images.githubusercontent.com/47950704/112220282-4ec06200-8be3-11eb-9ccd-98c577e78f2e.png">

**Comment by susantangux** [comment]
@superbunker Hi Jason - You have eagle eyes! Thank you for catching this! I've fixed the typo for both desktop and mobile.

**Comment by superbunker** [comment]
@NivenPrasad caught it! I was just practicing making issues. 

Thank you for jumping on it so quickly. I think we can close this, but I'll wait till we meet tomorrow.

**Comment by susantangux** [comment]
Fixed for desktop and mobile:
![pana](https://user-images.githubusercontent.com/78511203/112711456-c0b7d600-8e85-11eb-87a6-1e910863083d.png)

**Comment by superbunker** [comment]
finally getting around to closing this
