### ISSUE TITLE
create google form to take in new ideas

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#223]
### Overview
We need a simple method to take in raw automation ideas and feed them in to future automations

### Action Items

- [x] create a google form tied to 100automations@@hackforla.org
- [x] take them into a google sheet formatted to work with issue fields
- [x] Create GitHub issue using Google Apps Script

### Resources/Instructions
- [this is the issue and content that the Google Form needs to map to](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal)

**Comment by superbunker** [comment]
Jason will make google form and sheet, then assign Henry for the zap

**Comment by henlatourrette** [comment]
I was researching on how to do the Zap part and I have a doubt regarding the Github integration:
Since we need to connect it to a Github account, which account should we use? is there a official 100automations Github account? I couldn't find anything within the 1Password account. Please advise, thanks!
![image](https://user-images.githubusercontent.com/21250505/112692554-e6c98000-8e5d-11eb-82ac-3499924e2bc1.png)

**Comment by henlatourrette** [comment]
@akibrhast to set up the Google Form with an script and the GitHub API.
@henlatourrette will put the Zapier implementation on hold.

**Comment by superbunker** [comment]
Form created, still need to tweak some permissions. Akib linked it up. 
https://docs.google.com/forms/d/16BebCxeMH031c7prjLdyKa20nLZ4dj7ORFsw6HyaMIQ/edit

**Comment by superbunker** [comment]
[Idea Submission Form](https://docs.google.com/forms/d/16BebCxeMH031c7prjLdyKa20nLZ4dj7ORFsw6HyaMIQ/edit) created. Akib linked it up to futureautomations.
But I can't change the ownership of the form and sheet — looks like [google made this impossible](https://www.techtimes.com/articles/257610/20210303/google-forms-no-longer-allowed-to-be-transferred-to-other-accounts-as-part-of-new-privacy-protection-rule.htm)?

**Comment by henlatourrette** [comment]
Jason is the owner of the form which is shared to the team with "Edit" access.
I'll create a new issue with the pending issues to: "change the Github user who creates the issue to the FutureAutomations board." as right now the user is Akib. I'll close this issue once the related new one is created.

**Comment by henlatourrette** [comment]
A new issue was created to address the pending task> https://github.com/100Automations/Website/issues/241
