### ISSUE TITLE
Website Use Metrics

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#23]
### Overview
Identify how we will track and measure web analytics.

### Action Items
- [x] Research and discuss options
- [ ] Decide on approach to data instrumentation

### Resources/Instructions
[OKRs Issue](https://github.com/100Automations/Website/issues/6)

**Comment by NivenPrasad** [comment]
Google Tags Manager is an easy to use option - we should consider this and also think about whether we need to involve marketing team on setting up instrumentation for website use metrics.

**Comment by NivenPrasad** [comment]
Some metrics to track on page:
1. Contribute
2. Getting started
3. Visits
4. Guides read
5. Automation ReadMe Button on Homepage
6. Time on page
7. User exit path - where/when are they leaving the page?

Overall metrics:
1. New ideas created
2. Automations vetted for building
3. Automations built
4. Number of automations deployed

Can we track GitHub metrics? E.g. reading time on ReadMe

**Comment by henlatourrette** [comment]
@superbunker will research on how to track visits to GitHub ReadMes. I will move forward with the Google Tag Manager to have the snippet ready.

**Comment by henlatourrette** [comment]
Hi! This is how to add the Google Tag Manager Snippet for our Website:

```
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NK8P8ZW');</script>
<!-- End Google Tag Manager -->

Additionally, paste this code immediately after the opening <body> tag:
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NK8P8ZW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

For more information about installing the Google Tag Manager snippet, visit our [Quick Start Guide ](https://developers.google.com/tag-manager/quickstart).
```

**Comment by NivenPrasad** [comment]
@mdothman could you and the team please insert the above snippet onto the website for testing.

**Comment by henlatourrette** [comment]
The Tag Manager snippet was already added to the Website by @mdothman on Wednesday meeting. 

I've now created the "Webstream" on Google Analytics with ID "G-8GD9S32H5N" 

![image](https://user-images.githubusercontent.com/21250505/114245314-3e87e100-995e-11eb-967f-c5e445899b93.png)

And have connected it to the Google Tag Manager following Google's instructions:
![image](https://user-images.githubusercontent.com/21250505/114245438-7db63200-995e-11eb-9d1a-1706fbd707f1.png)

In order to try this out, we need to access the site from everywhere and from different devices. Hopefully, we would now have some data to anaylize within the following days.

**Comment by superbunker** [comment]
Discuss this in context of launch plan #300

**Comment by superbunker** [comment]
To clean things up a bit, I think we can close this, with the live site testing covered by #342

**Comment by henlatourrette** [comment]
Analytics is up. We can close this issue.

**Comment by henlatourrette** [comment]
I'ver currently lost access to my 1password account and don't have access to the 100automations Google Analytics tool - so, I cannot check it right now.
