### ISSUE TITLE
Update Create Automation Card Template in the Futureautomations Repo

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#234]
### Overview
We need to update the Create Automation Card Template for the the right list of items.

### Action Items
- [x] Compare template against one of the in progress create automation cards
- [x] Update template for what's missing
- [ ] Review with team

### Resources/Instructions
[Create Automation Card Template](https://github.com/100Automations/futureautomations/blob/master/.github/ISSUE_TEMPLATE/create-automation-card-for--automation-name-.md)
[In Progress Create Automation Card](https://github.com/100Automations/Website/issues/24)

**Comment by henlatourrette** [comment]
Progress: Already working on updating the template but didn't finish it yet. I'm using the "in progress" one as a template.
Blockers: None for now.
Expected Completion Date: This week.

**Comment by henlatourrette** [comment]
Hi, I've created the pull request to update the template. 
https://github.com/100Automations/futureautomations/pull/36

**Comment by henlatourrette** [comment]
@NivenPrasad please review my PR with the changes made.

**Comment by superbunker** [comment]
Looks done
