### ISSUE TITLE
Create automation card for Pre-commit-hook-starter

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#24]
### Overview
Provide collateral for the OpenSourceAutomations.org website

### Action Items
- [ ]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x]  Name of automation
  - [x]  A blurb about the automation
  - [ ]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [ ] Healthy project files (see resources for instructions)
     - [ ]  Readme.md URL
     - [ ]  contributing.md URL
     - [ ]  security.md URL
     - [ ]  support.md URL
- [ ]  Current status of Automation
     - [ ] in use and ready to deploy
     - [ ] in use and being refactored
     - [x] ready to deploy
     - [ ] in development
     - [ ] ready for development
     - [ ] in ideation
     - [ ] abandoned
- [ ] If status in use, what codebase can it be seen in?
- [ ] Help wanted (check all that apply)
     - [ ] needs maintenance
     - [ ] needs support for users
     - [ ] needs refactoring
     - [ ] needs documentation 
     - [ ] needs peer review
     - [ ] needs to be built
     - [ ] needs to be researched
     - [ ] needs advice
        - [ ] Advice Needed: (type in sort description of what you need)
     - [ ] needs takeover
- [ ]   Add automation Card to website

### Resources/Instructions
See project cards on the hackforla.org website for general idea, although the format of these will be different.

- [GitHub's guide: Setting guidelines for repository contributors](https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors)
- [GitHub's guide: Adding a security policy to your repository
](https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository)
- [GitHub's guide: Adding support resources to your project
](https://docs.github.com/en/articles/adding-support-resources-to-your-project)

**Readme should include:**
- Overview 
  - _What kind of repetitive thing do you have to do often and what is the benefit of automating it?_
- Current State 
  - _"As-is" most likely something manual but could be partially automated_
- Future Development
  - _The “To-be” state_
- Stakeholders
  - _Impact - who benefits and how?_
- Anticipated outcomes
- Resources/Instructions
  - _How to run the automation and any packages or dependencies_ 
- Language
  - _Programming language(s)_
- Platform
  - _Where is it deployed (e.g. GitHub, Linux Command Line, Windows Command Line etc)_
- Automation triggers 
  - _What starts it? What's it responding to?
  - _Is it Time-based (Specify frequency (e.g. 1x/week)?_
  - _Is it Event-based (e.g. someone just created a new GitHub on a repo)?_
- Input required 
  - _How much manual or custom input is required?_
- Output 
  - _What's the desired result? What do we not want to see?_

### Final Action Item

- [ ] Release the dependency #73

**Comment by NivenPrasad** [comment]
Hi @salice! Checking in with you to see if you will have time to work on this issue, or we should put it back in the prioritized backlog. No pressure, just checking your status. If you are working on this please provide update:

Progress:
Blocks:
Availability:
Eta:

**Comment by NivenPrasad** [comment]
**600x400 image:** [TO BE ADDED]

**Alt text:** [TO BE ADDED]

**Name of automation:** Pre-commit hooks
**Blurb:** 

Links:

**Repo:** https://github.com/100Automations/github-actions

**Resources:**

Readme: https://github.com/100Automations/github-actions/blob/master/README.md
contributing.md: 
security.md: 
support.md: 

**Help wanted:** 
**Status:** 
**Used in codebase:**

**Comment by NivenPrasad** [comment]
Hi @salice! I've put together the above to "package" the github-actions repo into an automation that we can showcase on the website as we're building it.

We'll need to add contributing.md, security.md, and support.md files to the repo (this is a minimum threshold that we're implementing for all automations that enter the project) but I've already put together some text [for it here](https://docs.google.com/document/d/106JPOcMYIy1QrrXba_EsjW7HIPuzP-nPUOLtaFG-AH0/edit#heading=h.dihytz3tgi9u)

Would love to work with you to finish packaging this up this week if available.

**Comment by NivenPrasad** [comment]
Discussed with @salice this week and have updated the checklist. Health files text is ready in the doc link in the above comment - I have to create the files in the repository.

Note that the status has been set as "Needs to be built" which is not completely accurate - the developer, Sophia, is planning to augment and build further on the code so this is the status that most closely resembles that.

**Comment by NivenPrasad** [comment]
@NivenPrasad to check on PRs and confirm all assets are available for the card, before next meeting.

**Comment by NivenPrasad** [comment]
We need to create a new image and re-write the description to relate more closely to the new "Pre-commit hook starter kit" name.

**Comment by NivenPrasad** [comment]
@NivenPrasad to follow up with @salice on the outstanding action items.

**Comment by NivenPrasad** [comment]
Progress: @salice working on it
Blocks: None
Availability: Available
Eta: Looking to get it done over the weekend but otherwise by Tuesday

**Comment by NivenPrasad** [comment]
Checked in with @salice - had to attend to other priorities and will address this post-holiday/New Year's week.

**Comment by Olivia-Chiong** [comment]
@superbunker to create a replacement image for the logo

**Comment by superbunker** [comment]
An idea for a replacement logo -- 
![gpch-0106_1517](https://user-images.githubusercontent.com/47950704/103833031-b92a2300-5034-11eb-967b-94db5f8fe11e.jpg)

**Comment by NivenPrasad** [comment]
Logo approved.

**Comment by Olivia-Chiong** [comment]
@salice is working on it this weekend and will provide update next week.

**Comment by Olivia-Chiong** [comment]
@salice has started working on this and it will be ready on Friday 1/15

**Comment by Olivia-Chiong** [comment]
@salice is still working on it and will be done Monday 1/18.

**Comment by Olivia-Chiong** [comment]
Have sent @salice a request for current available information and documentation so we can work on it if she is not free.

**Comment by Olivia-Chiong** [comment]
Sent Sophia this message today -

Hey Sophia, happy long weekend! Wanted to check in with you to find out where you stand currently on this issue. If you don't have time to work on it, could you give me some guidance on what is required so I can get someone to help on it please? Thank you!

**Comment by Olivia-Chiong** [comment]
@superbunker can you please change the logo to 744 by 300 please.

**Comment by Olivia-Chiong** [comment]
@salice any chance we could meet up this week to talk about this? I'm also reaching out to you on Slack.

**Comment by superbunker** [comment]
shazam

![ghpch-744x300](https://user-images.githubusercontent.com/47950704/108957321-22d2b080-7626-11eb-8ef7-a904652af20b.png)

**Comment by superbunker** [comment]
an unsquished tentacle for the wider format
![gpch-744x300-0224](https://user-images.githubusercontent.com/47950704/109089179-aa233100-76c5-11eb-86cd-00e9ecedae02.png)

**Comment by Olivia-Chiong** [comment]
spoke to @salice and she is busy with her job and Out in Tech mentorship. She will be available to work on this after end of March. To check in with her at the beginning of April.

**Comment by superbunker** [comment]
Will ask Sophia if we can do any further needed clean-up

**Comment by henlatourrette** [comment]
It looks good!
