### ISSUE TITLE
Change the Github user who creates the issue to the FutureAutomations board.

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#241]
### Overview
We need to have the 100 automations account as a user to create issues from the Google Form.

### Action Items

- [x] GitHub personal access token for the 100 automations account with necessary permissions
- [x] Finalization of what Label  an "Automation Idea Proposal" issue should have
- [x] Finalization of what Projects an "Automation Idea Proposal" issue should be put under
- [x] Finalization of the form questions
- [ ] Finalization of the submitted issues style/looks
- [ ] Test implementation 

### Resources/Instructions

https://github.com/100Automations/Website/issues/223

**Comment by akibrhast** [comment]
@henlatourrette @Olivia-Chiong @NivenPrasad 

Would it be possible to get an update on these:

- [ ]  Finalization of what Label an "Automation Idea Proposal" issue should have
- [ ]  Finalization of what Projects an "Automation Idea Proposal" issue should be put under
- [ ]  Finalization of the form questions
- [ ]  Finalization of the submitted issues style/looks

**Comment by NivenPrasad** [comment]
@akibrhast We can look at this, this weekend and get you the answers.

Btw, I think we need to clarify whether we just have the Google Form or both a Google Form + GitHub issue for automation proposals. Imo we should have both to cater for both users who are and aren't familiar with GH issues. We had a template automation proposal in the futureautomations repo, which looks to have been replaced with just the form - the old issue template contained all the questions to ask, similar to the first comment in one of the ideas you'll see in the FA project board: [see example](https://github.com/100Automations/futureautomations/issues/14#issue-784789408)

Here's a start to those questions but we'll finalize within product then tag you in a new comment in this issue once we have final answers.

- Label an "Automation Idea Proposal" issue should have
   - "Automation Idea"
   - "Documentation" 
-  What Projects an "Automation Idea Proposal" issue should be put under
   - Unclaimed/Project Management Board in the futureautomations repo. [This one](https://github.com/100Automations/futureautomations/projects/1
 )
    - Side note: maybe the product team needs to come up with a better name for this board
-  The form questions
    - Will be the same as the ones in the template issue 
-  Submitted issues style/looks

**Comment by superbunker** [comment]
labels to add for all incoming: documentation, ideation, review

**Comment by superbunker** [comment]
User issue is fixed. Still need to do the labels.
Reach out to @akibrhast to help finish this up

**Comment by akibrhast** [comment]
@superbunker Hey there, what can I assist with?

**Comment by superbunker** [comment]
Hey @akibrhast 

We'd like these labels added to all the ideas submitted through the form: 
documentation, ideation, review,  role: administrative

**Comment by akibrhast** [comment]
The following labels has been added to the form
- documentation, ideation, review, role: administrative 
@superbunker

**Comment by superbunker** [comment]
implementation testing _underway!_

**Comment by henlatourrette** [comment]
it's working now!

**Comment by ExperimentsInHonesty** [comment]
@superbunker can you move the folder into the 100 automations drive

**Comment by superbunker** [comment]
There are two google accounts: 100automations@gmail.com and 100automations@hackforla.org

The form was made with the 100automations@hackforla.org account. It's located here:
https://docs.google.com/forms/d/16BebCxeMH031c7prjLdyKa20nLZ4dj7ORFsw6HyaMIQ/edit

Looking at the incoming email, that account also seems to have something active at zapier but its behind another password, so don't know what

**Comment by superbunker** [comment]
form appears to be broken at the moment
creating a new issue...

**Comment by superbunker** [comment]
closing this, working on the form in #488
