### ISSUE TITLE
User Research with Engineering Community of Practice

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#243]
### Overview
We need to do research to find out what engineers would expect their user journey to be when considering what automations to contribute to.

### Action Items
- [x] Create draft of questions to be used 
- [x] Review draft with team
- [ ] Conduct user research at Engineering Community of Practice

### Resources/Instructions
[List of questions](https://docs.google.com/document/d/1gTL4wddo4N8pIbPRNaKbKpt4SFDTEEHccKjHqDnfKgg/edit?usp=sharing)
[User Interview Script](https://docs.google.com/document/d/1uUdkb3aoPdLYAIgpIcOVm70FLnZ55crBBgTqZijGnuE/edit)

**Comment by NivenPrasad** [comment]
Initial intro with Engineering Community went well - we can partner with them for ongoing user research and discovery on our product. Next step is to start rolling out a framework for testing, start doing, and iterate on that framework. Not entirely necessary for MVP imo but can start putting in place.

Here is a [User Research folder](https://drive.google.com/drive/u/0/folders/1SVg5oTbJaqRi3Y_1WxubUvlN9BwcbL9S) I added to our G Drive with a starter template user testing script contained within.

**Comment by NivenPrasad** [comment]
I'll propose next steps to change this issue/add a new issue to be create a User Testing framework and start scheduling research. Also to consider who to be involved? Is this a UX + Product thing? What makes most sense?

Can also dogfood and do some testing with our own developers or do "expert interviews": [See article as starting point](https://medium.com/@grahamhowe/design-sprints-ask-the-expert-4928a8b03c2e) - usually used when you're right at the beginning of exploring a new problem space or ideation.

**Comment by superbunker** [comment]
We should either revise this for individual user interviews or create a new issue

**Comment by superbunker** [comment]
Link to the templates from a new issue

**Comment by superbunker** [comment]
Feedback from Engineering on the demo site has been addressed

We need a new issue for updated user research
