### ISSUE TITLE
Write Project Requirements Summary Document

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#25]
### Overview
We need a requirements summary to share with website design and to complete the initial requirements gathering milestone.

### Dependency
Requirements gathering milestone complete

### Action Items
- [x]  Review all the items in the [requirements gathering milestone](https://github.com/100Automations/Website/projects/1?card_filter_query=milestone%3A%223+-+website+requirements+gathering%22)
- [x] Write summary
- [x] Review with Bonnie
- [ ] Close issue and check to make sure milestone shows as completed

### Resources/Instructions
- [Website Requirements Gathering Summary](https://docs.google.com/document/d/1GvI9SssKWr0ewXgjM9qCEB8rSgmKyQpiLKZt2PbGafM/edit#heading=h.4g4fancxvw7h)
- [Project Figma Board with Content Outline](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
We need to add a sample media kit/todo list for each new automation to follow.

**Comment by NivenPrasad** [comment]
We're going to gather bios for content creators - we have created separate issues for these.

Bios page for creators (perhaps a pdf). Additionally: 
- a quote from the creators e.g. what they've gotten out of creating the content, or why they think automating is important 
- motivations, internal and external, for sharing
@NivenPrasad to ask creators
@CamilaArias to think about layout for bios

Bios page for page builder (perhaps a pdf). Additionally:
- a quote from the builders 
- motivations, internal and external, for building

**Comment by NivenPrasad** [comment]
Landing page for persona value propositions:
- Will contain a list of the personas
- Top meme for each persona, to get people's attention
- Value propositions for each persona
- How to navigate the site (may be in the value prop or may be separate)
- Describe persona's pain points (e.g. I'm not getting recognition I deserve at work)
- How the site and community solves that persona's pain points through the value prop
- Call to Action(s) for that persona

**Comment by Olivia-Chiong** [comment]
@Olivia-Chiong will move task board from Figma into Website Requirements document.

**Comment by Olivia-Chiong** [comment]
Completed moving of items on task board in Figma into Website Requirements document. Pending review.

**Comment by Olivia-Chiong** [comment]
Go through the workflow on Figma and move Figma annotations into requirements document.
Separate items into MVP and post MVP.

**Comment by henlatourrette** [comment]
update requirements for finalized mockups

**Comment by henlatourrette** [comment]
@NivenPrasad to make template of webpage requirements to reflect final pages.

**Comment by henlatourrette** [comment]
We need to add the UAT

We can use this as an example: https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#

**Comment by henlatourrette** [comment]
We will open an issue for the UAT and leave it open for a week so that people could audit the site and report any bugs right on that issue.

**Comment by henlatourrette** [comment]
We need to include Mobile design on the UAT as well

**Comment by henlatourrette** [comment]
I will check this and create new issues for Bugs.

**Comment by superbunker** [comment]
Site has been soft launched. Further work on requirements now in #473
