### ISSUE TITLE
Design a Guides page

### ISSUE THREAD

**Issue by CamilaArias** [100Automations/Website#253]
### Overview
Design a guides page to house all the guides for 100A since we already have too many to fit in a section in the homepage.
This is different than the Guide Template page which is for an individual guide.

### Action Items

- [x] Redesign Guides section on homepage to only feature some guides and link to the guides page
- [x] Wireframe some options to review with the team after discussing what should be here. Would probably have a couple featured guides and then some categorization, filtering of all of them. Also some CTA for suggesting a guide, maybe a way to visualize ideas that have been approved but no one has written guides for, etc.
- [x] Create final designs and provide Specs for spacing and any new components.
- [x] Add any new components to the DS.
- [ ] final review

### Resources/Instructions
Figma page - https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=3014%3A2467

**Comment by superbunker** [comment]
The all-guides page is live. I believe this issue can be closed.

**Comment by henlatourrette** [comment]
This one is done! we're closing it!
