### ISSUE TITLE
Create Team Page

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#255]
### Overview
~We need a template Bio so that we can use it to create other bios.~
Make a Team page for MVP.
 Possible post-MVP: individual bios

### Action Items
- [x] Create the Template for the Team Page.
- ~Product team will create a file for each individual Bio.~

**Comment by mdothman** [comment]
---
first-name: Your first name.
last-name: Your last name.
linkedIn-url: The address for your LinkedIn profile (https://www.linkedin.com/in/jane-doe/).
bio-description: Your bio description and information.
image: We will be placing the image in our assets folder.
---

## Explanation

Bios will be placed in a folder called _bios/ and will be named after each individual (muhi-dean-othman.md, henry-latourrette.md, etc.).
The user will provide a profile picture that we will place in our assets folder (muhi-dean-othman.jpeg, henry-latourrette.jpeg, etc.).

**Comment by henlatourrette** [comment]
The Bios folder for this is included in the PR #353

**Comment by Olivia-Chiong** [comment]
@mdothman I've created the md files where the bio issue is closed, please check and confirm all is good.

**Comment by superbunker** [comment]
Team page looks good — just take off the drop shadow from the top and replace with something subtle. Say, 1px border of slightly darker gray

**Comment by henlatourrette** [comment]
Susan suggests adding more padding at the bottom and make left and right margins the same so that cards are centered.

**Comment by superbunker** [comment]
Done for now
