### ISSUE TITLE
Create md files for overview pages and links

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#257]
### Overview
We need to create md files for overview pages and links so developers can link to them

### Action Items
- [x] Create blank guide for Contributor Overview #131
- [x] Create blank guide for https://github.com/100Automations/futureautomations/wiki/Overview-for-Creators
- [x] Create blank guide for    
   - [x] [Submit Idea](https://github.com/100Automations/Website/blob/gh-pages/_guides/workflow-guide-for-ideators.md) - Link at bottom of this page needs to be changed to Google Form
   - [x] Start Building #130
   - [x] Start Contributing #127

**Comment by superbunker** [comment]
- [Pages directory](https://github.com/100Automations/Website/tree/gh-pages/_pages)
- [Contributor Overview](https://github.com/100Automations/Website/blob/gh-pages/_pages/contributor_overview.md)
- [Creator Overview](https://github.com/100Automations/Website/blob/gh-pages/_pages/creator_overview.md)
- [Submit Idea](https://github.com/100Automations/Website/blob/gh-pages/_pages/submit_idea.md)
- [Start Building](https://github.com/100Automations/Website/blob/gh-pages/_pages/start_building.md)
- [Start Contributing](https://github.com/100Automations/Website/blob/gh-pages/_pages/start_contributing.md)

**Comment by Olivia-Chiong** [comment]
@superbunker went rogue and made the files without using PR, but all blank files are done and uploaded, we can proceed to populate them now.

**Comment by henlatourrette** [comment]
The "contributor overview" was renamed to "using_an_automation.md"
