### ISSUE TITLE
Create the About Page

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#258]
### Overview
We need to create an "About" Page

### Action Items

- [x] Confirm the Design for the "About" page.
- [x] Create the "About" page.
- [x] Finish the final Design of the "About" page.
- [x] Review it with the team.
- [x] add roadmap link
- [x] add button links 
- [x] final review

### Resources/Instructions
Link to the Roadmap: https://github.com/100Automations/Website/blob/gh-pages/100-Automations-Project-One-Sheet.pdf

**Comment by henlatourrette** [comment]
@mdothman this is the issue for the about page you were working on. Please confirm with @CamilaArias whether there is any important design thing to consider.

**Comment by mdothman** [comment]
@CamilaArias and I have discussed important design factors for consideration. The about page has been created, expected finalization on 4/21/21 for team to review.

**Comment by mdothman** [comment]
#  Update

## Progress

The  about page is being developed to become more responsive to screen sizes. 

### Currently working on:

*  Positioning the gears.
*  Keeping the Acknowledgements title in frame.

### Completed 

* The text is entirely mobile responsive.
* The header drawer button has been stylized

**Comment by mdothman** [comment]
# Review

Please see pull request #293

**Comment by henlatourrette** [comment]
@mdothman is this already finished?

**Comment by mdothman** [comment]
I didn't review this with the team, and that is the only thing left on the checklist.

**Comment by henlatourrette** [comment]
The only pending issue is to add the URL to the "Check out Roadmap" sentence

**Comment by superbunker** [comment]
I think I can handle adding this link

**Comment by superbunker** [comment]
I'm goin' in!

**Comment by superbunker** [comment]
ohhh, I'm the problem.

**Comment by superbunker** [comment]
PR #356

**Comment by henlatourrette** [comment]
After the PR is merged. We need to adjust the "Acknowledgements" text size. @mdothman is going to review the pull request.

**Comment by superbunker** [comment]
Can we just open the PDF on its own? I'll look in to this.

**Comment by superbunker** [comment]
Ayyyy, I figured out GitHub PDF rendering, with a combination of raw file and Google doc viewer.

- Add to beginning of URL: `https://docs.google.com/viewer?url=`
- Add to end of the URL: `?raw=true`

Full URL to display GitHub hosted PDF in-browser: 
https://docs.google.com/viewer?url=https://github.com/hackforla/product-management/blob/master/project-one-sheets/100-Automations-Project-One-Sheet.pdf?raw=true

I updated the roadmap link on the About page (and hot fixed, since it had gone 404 for some reason)

**Comment by superbunker** [comment]
Work on them buttons, @mdothman 
Also, gigantic Acknowledgements needs to be taken down a peg
~And the random gray line has now been banished~  _reprieve_

**Comment by henlatourrette** [comment]
The "acknowledgment" size is fixed but there's still an issue with the position because it's' overlapping with the gear. It needs to be moved to the left a little bit.

**Comment by superbunker** [comment]
Acknowledgments overlap fixed itself (?)

Border on the buttons is weird with some browsers (eg: mac/safari)
Buttons are not currently linked - where do they go?

Page seems to be pretty much done otherwise.

**Comment by superbunker** [comment]
Button border solid. But now white button is gray. Simple fix!

More importantly, the buttons don't go anywhere. We should... do something about that. 
- First needs to link to a "landing page" guide - probably the Creator Overview: https://100automations.github.io/Website/guides/creator_overview.html
- Website link goes to H4LA home page for 100 automations: https://www.hackforla.org/projects/100-automations

**Comment by superbunker** [comment]
@superbunker will take a swing at these links

**Comment by superbunker** [comment]
Links added. 

Final review and move to done.

**Comment by superbunker** [comment]
yaaaaaay
