### ISSUE TITLE
Role Recruitment

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#27]
### Overview
We need to recruit contributors for this project on an ongoing basis.

### Note
Last comment on this sheet will have our current recruiting needs listed.

### Action Items
- [x] Check last comment on recruiting sheet and update as necessary
- [ ] If updates made, update spreadsheet

### Resources/Instructions
- [Hack for LA Recruiting Current Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0
)
- [UX/UI Slack Channels](https://www.designerslack.community/)
- [UX/UI Slack Channels 2](https://uxdesign.cc/the-best-slack-groups-for-ux-designers-25c621673d9c?gi=6224907f9787)
- [Canva link](https://www.canva.com/design/DAESDlZ68dA/share/preview?token=2PRPpY_2tD8GCnmcLurRwQ&role=EDITOR&utm_content=DAESDlZ68dA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)
- [Logo on Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=242%3A327)

**Comment by NivenPrasad** [comment]
We need a UI/UX designer (must have) and a UX writer (nice to have).

**Comment by NivenPrasad** [comment]
Have onboarded UI/UX Designer - Camila Arias

**Comment by NivenPrasad** [comment]
10.14. Discussed that we need front-end Javascript developer.

**Comment by NivenPrasad** [comment]
@NivenPrasad to keep checking the new-joiner-orientation channel for developers.
@CamilaArias reaching out to Zayd who is potentially interested in helping with JS development.

**Comment by NivenPrasad** [comment]
New PM will take over responsibility of checking channel for new joiners/developers.

**Comment by Olivia-Chiong** [comment]
@Olivia-Chiong will start recruiting developers

**Comment by Olivia-Chiong** [comment]
Recruited Dean and Amy to the project. Continuing to recruit more.

**Comment by NivenPrasad** [comment]
@Olivia-Chiong will connect with the Civic Opportunity team post-xmas to discuss content writer pipeline.

**Comment by Olivia-Chiong** [comment]
Invite Audrey to join our team.

**Comment by Olivia-Chiong** [comment]
Created [new form](https://forms.gle/LGXf7DABcnaSUFxm7) for recruitment purposes.

**Comment by Olivia-Chiong** [comment]
@superbunker to help with replacing header for form.

**Comment by superbunker** [comment]
revised form header --
![100_automations_google_form_header-0106_1249](https://user-images.githubusercontent.com/47950704/103833249-5e44fb80-5035-11eb-9a5c-bbfd3c329240.png)

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty has approved.

**Comment by mdothman** [comment]
I would like someone who knows at least: CSS, SASS, Javascript, and HTML. It would be awesome if I found someone who knew: Material Design Lite, Jekyll, YAML and JSON.

**Comment by superbunker** [comment]
We could use some help on this - _Define a Process to handle the Future Automations_ #352

**Comment by superbunker** [comment]
- Product Managers: Future Automations, H4LA developer outreach, process design/improvement
- UX researchers: accessibility, usability testing, H4LA developer needs
- Developer(s): code review, refactoring

**Comment by ExperimentsInHonesty** [comment]
@susantangux will make ux role postings. 
@henlatourrette will make new pm posting.

Please get these done before next onboarding on Monday 23rd at 6pm

Note for both:  Please put links to them here or if you start a new issue for it, link that issue here

**Comment by superbunker** [comment]
per slack,  Susan doesn't seem to have full access to UI/UX posting

**Comment by henlatourrette** [comment]
Hi! I Posted a Product Manager opportunity in here: https://github.com/hackforla/product-management/projects/8#card-67378302

**Comment by susantangux** [comment]
Thanks, Jason! I knew you might know something about this.

Best,

*Susan Tang*

**Comment by susantangux** [comment]
I posted two roles: 1) UX/UI designer for website accessibility audit, and 2) UX researcher for website usability testing.

- [UX/UI Designer](https://github.com/hackforla/UI-UX/projects/3#card-61744819)
- [UX researcher](https://github.com/hackforla/UI-UX/projects/2#card-67701768)

**Comment by citrusapple** [comment]
Outdated needs, closing.
