### ISSUE TITLE
Prepare for Hack for your mother Hackathon

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#270]
### Overview
We need to prepare issues for the Hack for your Mother Hackathon on May 8 2021

### Action Items
- [x] Sign 100 Automations up in Democracy Lab
- [x] Sign 100 Automations up for the hackathon
- [x] Create list of issues to be shared during the hackathon
- [x] Fill in Project scope for Hackathon

### Resources/Instructions
[Event Link](https://www.democracylab.org/events/hackforyourmother2021)
[Sample project scope for Civic Tech Index](https://docs.google.com/document/d/1GGw3UmzWTTHXbfzceFwGTpho5KBxb6dpQ1Z07ygNBEc/edit)
[Sample project scope for Civiform](https://docs.google.com/document/d/1BY3Jl-WQxCzPcCgj05ImpT7DSoK7yZwMgemcDGiDqno/edit)
[Sample project scope for A/B Street](https://docs.google.com/document/d/10zGd081Y8L8MVNOs0vBhmDHeZF05_uYcQ-vs54Wpn84/edit)
[Project scope for 100 Automations](https://docs.google.com/document/d/19iEmws4zb4Yhrhb9bINSicjR0rLOPpXhdnH2f7Gczo4/edit?usp=sharing)

**Comment by henlatourrette** [comment]
https://docs.google.com/spreadsheets/d/1dyPfMhk5ZfwWeSySv7ljx9jooFAeh5GNE1lYeOJZVHo/edit?usp=sharing

This is the link for us to schedule our time.

**Comment by henlatourrette** [comment]
Let's do a review with the whole team.

**Comment by superbunker** [comment]
working on issues from the notes
