### ISSUE TITLE
Create sketches for website pages

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#28]
### Overview
We need initial sketches for the website pages.

### Action Items
- [x] Review Figma Board for outline of content for 5 pages
- [x] Produce first sketches of pages
- [x] Review with team

### Resources/Instructions
[Project Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by NivenPrasad** [comment]
@CamilaArias  Looks like you added a User Flow on the Figma board- are some of these actions and some of these pages? Perhaps we can distinguish between what these are by color coding? Happy to catch up on this.

**Comment by CamilaArias** [comment]
@NivenPrasad I believe this was before I joined the call that day so you know what follows, but just for future reference we decided we need a User Journey for different types of users to map what they would be looking for and therefore how to best help them find it.

**Comment by NivenPrasad** [comment]
@CamilaArias @ExperimentsInHonesty I put together User Stories in this document to help get the ball rolling on User Journey Mapping:

https://docs.google.com/document/d/1u53qfwgYW8isruErcqOZJL_1J66QGYAU8P2UxkmdOL0/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-09-28 at 12 05 12 PM](https://user-images.githubusercontent.com/37763229/94475137-8219bb00-0183-11eb-84f6-636858ad6658.png)

**Comment by NivenPrasad** [comment]
All page sketches are completed.
