### ISSUE TITLE
Make all external links open in new window

### ISSUE THREAD

**Issue by mcspach** [100Automations/Website#281]
### Overview
Find external links and replace with 

### Action Items
REPLACE THIS TEXT -

Change links in the following places:
- [x] readme button on cards.
- [x] social media links in the footer.
- [x] links from within getting started, etc. 
- [x] links inside of guides.

BONUS POINTS:
- [x] make the hack for la logo in the footer lead to hackforla.org

### Resources/Instructions
https://www.html.am/html-codes/links/open-link-in-new-window.cfm

**Comment by henlatourrette** [comment]
added @superbunker to review the PR
