### ISSUE TITLE
Remove "100 Automations" from guide page titles

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#286]
### Overview
We need to remove the "- 100 Automations" from guide page titles in the website. On the tab bar.

### Action Items
- [ ] Check where the header data is being pulled from
- [ ] Remove the "- 100 Automations" from the guide page titles

**Comment by superbunker** [comment]
Looks like this has been fixed?

**Comment by ExperimentsInHonesty** [comment]
This has been resolved
