### ISSUE TITLE
Add a Link to Hack for LA at the bottom

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#298]
### Overview
We need to link the Hack for LA logo to the HackForLA.org website. 
Optional: We could also add a link from the text where it says "Hack For LA".

### Action Items

- [ ] Add a link to the logo image at the bottom of the page.

### Resources/Instructions
HackForLA.org website link: https://www.hackforla.org/

**Comment by c-arvind** [comment]
Hi I just added them can you please check?

**Comment by superbunker** [comment]
This seems to be done

**Comment by superbunker** [comment]
Indeed, it is done
