### ISSUE TITLE
Role Identification

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#3]
### Overview
We need to build a team for the 100Automations site.

### Action Items
- [x] Review the roles document
- [x] Identify initial list
- [x] Add requirements to current needs doc

### Resources/Instructions
[General Role Definitions](https://docs.google.com/document/d/1X6d6-Sm_QDQPobiRfqachCSajAOpqRLVUsdCnczhhts/edit#heading=h.7brglf3y33hh
)

[Project Recruiting Current Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0
)

**Comment by ExperimentsInHonesty** [comment]
UI designer (must have)
UX content writer (nice to have)
front end dev (don't need now, will need after initial design)
back end dev (don't need now, will need after initial design)

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad put must have and nice to have into this sheet https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty edit access requested to make changes to sheet - waiting to be granted

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty roles now added to Current Needs doc so moving this issue to Done
