### ISSUE TITLE
Compliance with Open Source Logo Guidelines

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#30]
### Overview
We need to review the open source logo guidelines to ensure there is no misuse of the logo in our project.

### Action Items
- [ ] Review open source logo guidelines
- [ ] Make note on Project Figma Board about what (if any) restrictions to use there are so that these are incorporated in the design process
- [ ] Review website designs before launch to ensure compliance with guidelines where required

### Resources/Instructions
[Open Source Logo Guidelines](https://opensource.org/logo-usage-guidelines)
[100Automations Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=25%3A0)

**Comment by ExperimentsInHonesty** [comment]
We decided to create a new logo to better represent the project. This issue can now be closed.
