### ISSUE TITLE
Updates on Future Automations

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#315]
### Overview
This is to Report the status of the ongoing projects on the Future Automations board.

### Action Items
- [x] Check whether there are new ideas on the Future Automations Board
- [ ] Get them on track and make sure they're moving forward

### Resources/Instructions
[Future Automations Project Board](https://github.com/100Automations/futureautomations/projects/1)

**Comment by henlatourrette** [comment]
Status as of Today:

- unclaimed/half-backed ideas -> 6 
- idea iteration in process -> 1 
- automation signoff -> 1 
- unclaimed/prioritized backlog -> 2
- in progress -> 2

**Comment by henlatourrette** [comment]
@superbunker opened a new issue #370 to create an "Automations Status Card" to check the status periodically in some sort of automated manner. 

Should we consider closing this issue and focus on the new related issue instead?

**Comment by superbunker** [comment]
Automation idea: automate this. 
In the meantime... @superbunker can just make the card

**Comment by henlatourrette** [comment]
We created a note and it is already in the Review column. We can close this one.
