### ISSUE TITLE
Get setup on 1password

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#32]
### Overview
We need to add our 100 Automations passwords to the password system that Hack for LA uses so that they can be available for the organization.

### Action Items
- [ ] Read this draft: https://github.com/hackforla/website/issues/701#issuecomment-679316669
- [ ] Prepare a list of accounts and passwords that we will need to store
- [ ] Work with Bonnie to get setup on the system
- [ ] Follow instructions in the document and identify if any of the instructions could be improved.  Put revised draft in issue.
   - [ ] Take screen shots of any screen that would be useful.  Put screen shots in this issue.

### Resources
https://hackforla-team.1password.com/

**Comment by ExperimentsInHonesty** [comment]
I sent an invite to @CamilaArias @NivenPrasad.  Those must be accepted, and then they must be added to the vault.  Then Niven can add the following passwords:
- [ ] twitter
- [ ] instagram
- [ ] email

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty accepted 1password invitation today. Once added to vault, will store the social media and gmail account passwords over in the shared vault.

**Comment by NivenPrasad** [comment]
All passwords now included in 1Password.
