### ISSUE TITLE
Create a "See all Guides Page"

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#322]
### Overview
We need to create a new page to list all the available guides

### Action Items

- [x] Create a Guides Page
- [x] Design the Guides Page
- [x] Choose/approve design
- [x] Finish the Guides Page development
- [x] Review it with the team

### Resources/Instructions
- #375

**Comment by Olivia-Chiong** [comment]
Proposed guide categories: 

- How to improve, promote your automation Guides
   - Creating a good project image
   - Community support for automations
   - Creating a good readme
   - Prep automation for publications
   - Write your opensource automation creator bio
   - Writing articles for automations
   - Writing short descriptions for automations
- How to use the website Guides
   - Project card anatonmy 
   - Suggest a guide for 100 automations
- How to contribute to automations Guides
   - Self-evaluating new automation idea
   - Workflow guide for builders
   - Workflow guide for ideators

**Comment by superbunker** [comment]
Design proceeds!

**Comment by henlatourrette** [comment]
Hi @CamilaArias , do you have any feedback on design suggestions for the "See all guides page"?

**Comment by henlatourrette** [comment]
The design is almost ready.

**Comment by superbunker** [comment]
We have three options designed. Just gotta pick one.

@mcspach @mdothman  - Can we make an interim page for now so we can link to the guides?

**Comment by superbunker** [comment]
_Susan doesn't like it!_ (small tweaks)
Also, we need to pick a design. So.

**Comment by henlatourrette** [comment]
Provisionally, we picked the Design # 2 (going from left to right). But still needs to have approval from Design team.

**Comment by henlatourrette** [comment]
The design team is OK with the Design 2 but moving the Suggest a Guide button from the bottom to the top right. And also, they suggest adding categories - that Product team would still need to define the categories.

**Comment by henlatourrette** [comment]
We have the categories already. We decided on removing the "Suggest a Guide" button and leaving it for Post-MVP

**Comment by superbunker** [comment]
Upon further discussion — Nix the "suggest a guide" button entirely

Add categories as section headings ... is a problem.  There would need to be additional metadata for each guide so they could be pulled in to three separate lists. We don't have that right now. Not _super_ hard, but a bit annoying.

We'll make a new issue for adding category metadata to the headers of the guides.

**Comment by henlatourrette** [comment]
The issue we created to address the metadata requirements was #375

**Comment by superbunker** [comment]
@Clue355 update styles to match figma (the 4th version with category headers)
We may need some hardcoded dummy headers for now.

**Comment by henlatourrette** [comment]
We can refer to [Olivia's comment](https://github.com/100Automations/Website/issues/322#issuecomment-846467657) to update the final category assignation for each guide

**Comment by henlatourrette** [comment]
The new update after the Pull Request looks fine. Please let's also remove the Suggest a Guide button. We may need to update the design on Figma as well @susantangux

**Comment by susantangux** [comment]
Finished updating All Guides Page in Figma per Olivia's proposal. I also made all verb tenses consistent. Right now some of them are in present tense, some in present participle, such as "**write** your opensource automation creator bio" and "**writing** articles for automations." I turned them all into present tense.

**Comment by henlatourrette** [comment]
I reviewed and approved the PR. 

@Clue355 , regarding your concern about not "all" of the guides showing on the list, that's just because they're not ready for publication or we decided to leave them "off" for the moment. The new "categorization" feature allows us to do that. 

By saying that there are Guides with more than one category, which one/s are you referring to?

**Comment by superbunker** [comment]
Ohh yeah
