### ISSUE TITLE
Fix "Submit Idea" Guide - "In this Guide"

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#335]
### Overview
The section called "In this Guide" says "Learn best practice for creating a good project image". But that message is not related to the content. We need to change it to "Learn how to submit an idea".

### Action Items

- [ ] Remove the current paragraph
- [ ] Replace it with the appropriate phrase
- [ ] Review it with the team

### Resources/Instructions
-

**Comment by superbunker** [comment]
re-closeing
