### ISSUE TITLE
Guides have wrong description text

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#339]
### Overview
Every guide's description is "Learn best practice for creating a good project image," which does not match the description text in the files. 

### Action Items
- [x] What the hey? (research why they're pulling the wrong text)
- [x] Stahp! (get guides to use their own description)

### Resources/Instructions
example, "[creating a good readme](https://100automations.github.io/Website/guides/creating-good-readmes-for-automations.html)" has "good project image" description

**Comment by henlatourrette** [comment]
Each Guide has now its own issue:
#335 
#336 
#337

**Comment by superbunker** [comment]
it was hard coded. for... reasons? should be easy fix.

**Comment by mcspach** [comment]
This is fixed in my recent pull request #344

It should also be checked when Carlos pushes his changes on the guides page.
