### ISSUE TITLE
Change the V for a Chevron on the "Needs help" button

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#340]
### Overview
We need to change the V for a Chevron on the "Needs help" button.

### Action Items

- [x] Get the Chevron image
- [x] Remove the V and replace it with the Chevron

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1432%3A998)

**Comment by mcspach** [comment]
Do you guys like this or no?

<img width="786" alt="Screen Shot 2021-06-09 at 9 18 37 AM" src="https://user-images.githubusercontent.com/38964454/121392378-2ef82a80-c904-11eb-95a6-b5b9b9f6ad1e.png">

**Comment by superbunker** [comment]
FontAwesome isn't working, so this needs to be an uploaded image, or live text (which it is now).

Merging PR but leaving open for further review.
