### ISSUE TITLE
Finish guides section on homepage

### ISSUE THREAD

**Issue by mcspach** [100Automations/Website#347]
We need to restyle the guides section to match the new Figma.

- [x] Get new design from Figma
- [x] Remove suggest a guide button and add see all guides button
- [x]  Add padding, resizing, etc to finish guides section

**Comment by mcspach** [comment]
<img width="1433" alt="Screen Shot 2021-06-09 at 10 30 13 AM" src="https://user-images.githubusercontent.com/38964454/121405160-8d77d580-c911-11eb-95cd-b15580e296d1.png">
<img width="213" alt="Screen Shot 2021-06-09 at 10 29 58 AM" src="https://user-images.githubusercontent.com/38964454/121405171-910b5c80-c911-11eb-91ff-059a7cb52109.png">

**Comment by superbunker** [comment]
Can merge PR.

Leaving issue open: 
- vertically center text inside the cards
- check the border radius on mobile 
- link button (Dependent on creating guides page and getting url)
