### ISSUE TITLE
Create a default Code of Conduct file in .github

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#35]
### Overview
A Code of Conduct file is necessary for repos to meet community health standards. We need to create a default one so that any automations include this as part of their repo.

### Action Items
- [x] Craft a Code of Conduct file that links to the Hack for LA code of conduct and create a default file in the .github repo

### Resources/Instructions
[Hack for LA Code of Conduct](https://github.com/hackforla/codeofconduct/)

**Comment by ExperimentsInHonesty** [comment]
The repos that were created before the default file was installed will need to be added.  See issue #63
