### ISSUE TITLE
Add Content to the Press Kit Page

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#351]
### Overview
It looks empty right now and not ready for MVP

### Action Items

- [x] Add the Memes
- [x] Add the social Media content
- ~Finish the "Bio" Pop-Up functionality~ using LinkedIn
- [x] Finish the layout
- [x] Add URL to the Fact Sheet linking to the OneSheet
- [x] Review it with the team

### Resources/Instructions
One Sheet > https://github.com/100Automations/Website/blob/gh-pages/100-Automations-Project-One-Sheet.pdf
Link to the gDrive Memes > https://drive.google.com/drive/u/0/folders/10vaCzqqoAGc6STIlYEKUZ_6y9nTjSF-n
Press Release > https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit

**Comment by henlatourrette** [comment]
Comments from the meeting:
"Fact sheet" should link to the One Sheet
"Logo" should link to google drive where the Logos are
"Press release" should link directly to a Press Release page - still pending in production but already in mock up

**Comment by henlatourrette** [comment]
As for the Bio Pages, we need to finish the #255 . And we need help with the API to get the Profile pics from LinkedIn. @akibrhast can you give us a hand with this part?

**Comment by henlatourrette** [comment]
We decided to use GitHub profile pic instead of using the LinkedIn one because there are many blockers with LinkedIn regarding the APIs and stuff. Using the Github one would be much easier. 

When we solve the LinkedIn issue we can update it again.

**Comment by henlatourrette** [comment]
Regarding the Bios, there are doubts about cases when a person is involved in more than one automation. And a few more other issues. We may need to redefine the Bio cards and the information in there.

The modal for the Bio is a blocker right now. If we remove the "Bio" individual pages from the MVP, it can be faster to finish the press kit.

**Comment by henlatourrette** [comment]
We decided on removing the "View Bio" button for MVP and change the "Bios" title for just "Team" instead and remove the filters.  

@CamilaArias @susantangux can you please check how would this look in the final design?

**Comment by henlatourrette** [comment]
For MVP we re leaving the roles below the names, under the bio pages. But we're considering a better home for the bio pages but that's a low priority for the moment.

**Comment by henlatourrette** [comment]
We created an issue for the change on the section related to Social Media #373

**Comment by henlatourrette** [comment]
Instead of Bios, we can leave "Team" for MVP and that would be just a page with no Bios but with the team members.

**Comment by mdothman** [comment]
Website is displaying design standards

**Comment by superbunker** [comment]
We're going to keep the memes scrolling rather than batching out into paged array (bleh)
