### ISSUE TITLE
Create automation workflow overview 

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#354]
### Overview
The "automation workflow overview" is linked as a wiki page from the [Start Building](https://100automations.github.io/Website/guides/start_building.html) guide. It is currently blank.

### Action Items
- [ ] figure out what the automation workflow is
- [ ] document it

### Resources/Instructions
- overarching issue: _Define a Process to handle the Future Automations_ #352

**Comment by NivenPrasad** [comment]
Is this done because of #384 ?

**Comment by henlatourrette** [comment]
As Niven has mentioned, I believe this issue is already handled under #384 . @superbunker can you take a look at it and confirm?

**Comment by superbunker** [comment]
The wiki link is no longer in the revised builder's guide
