### ISSUE TITLE
Create a Guide: Creating a Good Read.me for Your Automation 

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#36]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Creating a Good Read.me for Your Automation" guide.

### Dependency
Waiting for other guides to be done to see if this needs any additional formatting.

### Action Items
- [x] Write mark-down for the guide instructions in a comment on this issue.
- [x] Create a mark-down file for this guide and add it to a folder called _guides
   - [x] Call the file a name with dashes that is as short as possible
      - [x] name: creating-good-readmes-for-automations.md
   - [x] Add the following header to the file:
```
---
title: Creating a Good Read.me for Your Automation
description: a read.me file is usually the first place that developers will start. It should be fairly comprehensive and should have links to the other health files.
status: active
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by NivenPrasad** [comment]
Creating a Good Read.me for your Automation

See an example of a good 100 Automations Read.me: True GitHub Contributors

A good 100 Automations Read.me should have the following content:

# Title

## Overview
What kind of repetitive thing do you have to do often and what is the benefit of automating it?

### Problem Being Solved

### Value Created from Solution

### Solution (simplified explanation)

### Stakeholders
Impact - who benefits and how?

## Technical Details
### Installation

### Current State
"As-is" most likely something manual but could be partially automated

### Future Development
The “To-be” state

### Anticipated technical outcomes

### Resources/Instructions
How to run the automation and any packages or dependencies 

### Language
Programming language(s)

### Platform
Where is it deployed (e.g. GitHub, Linux Command Line, Windows Command Line etc)

### Automation triggers
Time-based (Specify frequency (e.g. 1x/week)
Event-based (e.g. someone just created a new GitHub on a repo)

### Input required
How much manual or custom input is required?

### Output
What's the expected result? 

## API
(If applicable)
### Versions/Updates
### Configuration
### Usage

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad I think this is page is good to make a file out of now.  So when we next get together I can walk you through it.  And then once this one is done, we will have a url to insert into #43 and it can go live as well.
