### ISSUE TITLE
create Future Automations status card in main repo review

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#370]
### Overview
Would be helpful to have an at-a-glace status of the Future Automations board

### Action Items

- [x] make a card in the review column
- ~link to each FA~ - this gets weird in a note, since it pops out one (and only one) reference
- [x] add status

### Resources/Instructions
https://github.com/100Automations/futureautomations/projects/1

**Comment by henlatourrette** [comment]
I'll send the automation idea using the form.

**Comment by superbunker** [comment]
@NivenPrasad created a static note for this. There isn't a built-in way to display project status in another project, so a manual status card is probably it for now. The idea for an automated status card can be tracked in Future Automations
