### ISSUE TITLE
Add Categories as Metadata for the Guide 

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#375]
### Overview
In order to Make the All Guides Page list the Guides as categories, we need to add new Metadata values.

### Action Items

- [x] List the categories
- [x] Name them using alphanumerical symbols (used 1,2,3)
- [x] Create the values
- ~Add finalized category titles to guides page~ (see #322)
- [x] Review it with the team

### Resources/Instructions
#322

**Comment by superbunker** [comment]
Categories (1,2,3) are fully functional on the all guide page

This is now a content and organization issue.

**Comment by superbunker** [comment]
Categories (1,2,3) are fully functional on the all guide page

This is now a content and organization issue, so closing this and moving discussion back over to #322
