### ISSUE TITLE
Feature Idea: Related guide links

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#38]
### Overview
As a visitor to the site who selects a guide randomly I want to be to see how things are connected so that I can get a better understanding of how things work on the site or project 

### Action Items
- [ ] review @CamilaArias 's idea
@Bonnie @Niven Prasad I just thought it might improve the UX a bit if we had a section on the side for related guides, as you said you prefer smaller guides, then people might read a couple of them for the objective/interest they have. So something generic like "related guides"and you pick which ones are related when uploading the guide, or more custom like "If you've done whatever the guide is for you might be interested in another guide for something else". Below the column on the side where we have the description. 

### Resources/Instructions
[100 Automations project board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?)

**Comment by superbunker** [comment]
This issue remains unresolved.
But is superseded by #469
