### ISSUE TITLE
Write instructions for someone contributing existing automation

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#384]
### Overview
We need step by step instructions for how someone with an existing code can add it to 100 Automations

### Action Items
- [x] write up what we think the process might be
- [x] publish as guide(s)

### Resources/Instructions
- https://100automations.github.io/Website/guides/start_contributing.html
- https://100automations.github.io/Website/guides/start_building.html
- #354
- https://github.com/100Automations/Website/issues/127#issuecomment-830691542

**Comment by NivenPrasad** [comment]
Steps to add an existing automation to 100 Automations:

1. Create a new repository under the 100 Automations - [quick link here](https://github.com/organizations/100Automations/repositories/new)
2. Ensure the repository contains, at a minimum:
- A Readme
- Licence: we use the GNU General Public License v2.0 at Hack for LA [**Double-check this**]
- A Code of Conduct.md
- A Security.md
- A Support.md
- A Contributing.md
3.  Once the repository is complete with documentation and the automation code, complete [this automation card template](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal) in the Future Automations repo and move it to the [Review column](https://github.com/100Automations/futureautomations/projects/1#column-9876980)
4. If you prefer completing the automation card template over multiple sessions, place it in the [In Progress column](https://github.com/100Automations/futureautomations/projects/1#column-9876974) on the Future Automations board
5. Once the repo and template card are ready for review, the 100 Automations team will reach out to partner on getting the materials together to get the automation ready for the 100 Automations website. You will use [this automation materials template](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+good+first+issue&template=create-automation-card-for--automation-name-.md&title=Create+automation+card+for+%5Bautomation+name%5D) for this purpose.


## References ##

Here is an example of an [automation repo](https://github.com/100Automations/true-github-contributors)
Here are guides on:
- Writing a good readme
- Writing good health files (code of conduct, contributing.md, support.md, security.md)

**Comment by NivenPrasad** [comment]
Ready for review by product and UI/UX team

**Comment by superbunker** [comment]
@ExperimentsInHonesty I think this issue most directly addresses what you were describing.

The meta-issue (issue of issues) for the Future Automations process is #352

**Comment by superbunker** [comment]
Per #395 we're swapping the usage of "build" and "contribute." So content would probably fit best as an addition to the "Builder's Guide" (formerly contributor's guide) from https://github.com/100Automations/Website/issues/127#issuecomment-830691542

**Comment by superbunker** [comment]
Content has been added to the "Start Building" guide.

**Comment by superbunker** [comment]
If there's no edits to the contributor's guide for now, I'd like to close this

**Comment by superbunker** [comment]
This guide is now in use as the "Start Building" guide. If there's something further needed, leave a comment
