### ISSUE TITLE
fix guide: Good Readme - clarify code formatting 

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#387]
### Dependency
Determining if this is still a part of the process #469 

### Overview
The "code" formatting looks like it might be a mistake. Clarify that it's purposeful 

### Action Items
- [ ] Figure out best way to clarify the overall code block style (eg: background or border)
- [ ] Change style
- [ ] Review 

### Resources/Instructions
- https://100automations.github.io/Website/guides/creating-good-readmes-for-automations.html
- https://github.com/100Automations/Website/blob/gh-pages/_guides/creating-good-readmes-for-automations.md

**Comment by superbunker** [comment]
Best to do this with CSS rather than hacking something in the contents

**Comment by ExperimentsInHonesty** [comment]
Restructuring the process.  So this change is no longer needed.
