### ISSUE TITLE
Proposal: remove "Using An Automation" till post-MVP

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#388]
### Overview
This guide is a blank file. We don't currently have enough usable automations to write an effective guide for this. It may not even be necessary to have its own guide, since each repo will need to contain instructions for this?

Note: guide not showing up on "All Guides" page because it doesn't have a category

### Action Items
- [ ] Product makes a decision 
   - [ ] If yes, delete this guide file for now 
   - [ ] If keeping guide... write guide

### Resources/Instructions
https://github.com/100Automations/Website/blob/gh-pages/_guides/using_an_automation.md

**Comment by henlatourrette** [comment]
I vote for just deleting the guide for now.

**Comment by superbunker** [comment]
#131 in icebox
