### ISSUE TITLE
Social Media previews

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#39]
### Overview
We need preview images for each automation and for our own website repo

### Action Items
  -  [x] template for each automation
      - [x] name of automation
      - [x] image unique to their automation
      - [x] 100 Automations logo
- [x] social media preview image for 100 automations website
   - [x] our logo
 

### Resources/Instructions
![repository-open-graph-template](https://user-images.githubusercontent.com/37763229/95665201-f26cf880-0b02-11eb-94db-bdd6541d04a2.png)

**Comment by NivenPrasad** [comment]
@CamilaArias has created: 

- two versions of the website preview
- templates for each automation we have so far (we have versions with different colors, with names, and without names)

@ExperimentsInHonesty - we can discuss how to test and decide on versions.

**Comment by ExperimentsInHonesty** [comment]
@CamilaArias can you export [these images](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=791%3A303) in the size they need to be and add them to a folder on the google drive and link it here

**Comment by NivenPrasad** [comment]
@CamilaArias are you able to export these files? If you have already done so, please paste the URL in the issue here.

**Comment by NivenPrasad** [comment]
@CamilaArias has uploaded the previews in [this folder](https://drive.google.com/drive/folders/10vaCzqqoAGc6STIlYEKUZ_6y9nTjSF-n?usp=sharing).
