### ISSUE TITLE
fix all absolute links in the guides

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#390]
### Overview
Cross-linked guides currently use the absolute URL of the development site (eg: [Creator Overview](https://100automations.github.io/Website/guides/creator_overview.html) ). When the site goes live, these links break. We need to replace them with relative links. 

[example link to /guides/filename.html](/Website/guides/filename.html)

### Action Items
- [x] establish jekyll syntax for relative URLs within md files
- [x] change all internal site links in the content of the guides 
  - [x] community-support-for-automations.md - no internal crosslinks
  - [x] creating-good-project-images.md - no internal crosslinks
  - [x] creating-good-readmes-for-automations.md - no internal crosslinks
  - [x] creator_overview.md - [check](https://100automations.github.io/Website/guides/creator_overview.html)
  - [x] prep-automation-for-publication.md - [check](https://100automations.github.io/Website/guides/prep-automation-for-publication.html)
  - [x] project_card_anatomy.md - [check](https://100automations.github.io/Website/guides/project_card_anatomy.html)
  - [x] self-evaluating-new-automation-idea.md - [check](https://100automations.github.io/Website/guides/self-evaluating-new-automation-idea.html)
  - [x] start_building.md - no links to guides (has bad link to wiki though)
  - [x] start_contributing.md - [check](https://100automations.github.io/Website/guides/start_contributing.html)
  - [x] submit_idea.md - [check](https://100automations.github.io/Website/guides/submit_idea.html)
  - [x] suggest-guide-for-100Automations.md - no internal crosslinks
  - [x] using_an_automation.md - no internal crosslinks
  - [x] workflow-guide-for-builders.md - no internal crosslinks
  - [x] workflow-guide-for-ideators.md - [check](https://100automations.github.io/Website/guides/workflow-guide-for-ideators.html)
  - [x] write-your-opensource-automation-creator-bio.md - no internal crosslinks
  - [x] writing-articles-for-automations.md - no internal crosslinks
  - [x] writing-short-descriptions-for-automations.md - no internal crosslinks
- [x] test/confirm

### Resources/Instructions
NOTE: When making relative links in gh-pages, the links will be wrong in the md file (“blob/gh-pages”) because jekyll hasn’t processed them yet, so they're relative to the repo, not the site. Which means that as far as I can tell, relative links can’t be tested in the code — only on the live post-jekyll page.

**Comment by superbunker** [comment]
Guide links changed. Putting issue up for review as a final check before closing.

**Comment by henlatourrette** [comment]
It looks fine!
