### ISSUE TITLE
Adjust Style on Press Kit Page after Screen Width of 1700 pixels

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#402]
### Overview
Adjust Style on Press Kit Page after Screen Width of 1700 pixels

### Action Items

- [ ] - Press release title
- [ ] - Social Media Posts Title
- [ ] - Contact text mix up with the images of the waves
- [ ] 

### Resources/Instructions
[Press Kit Page](https://100automations.github.io/Website/press-kit/press-kit-index)

**Comment by citrusapple** [comment]
update: mobile is working properly.  Still having issues with tablet size or half size desktop, due to not having a tablet design in Figma. Carlos will continue to work on it.
