### ISSUE TITLE
Fix guides title wrapping

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#407]
### Overview
The titles of the guides wrap aggressively at smaller screen sizes, pushing titles out of the header. They need to be responsive and readable at all sizes. 

### Action Items
- [ ] design a responsive solution
- [ ] implement CSS for mobile and desktop
- [ ] review/confirm

### Resources/Instructions
- Possible options: vertical center, progressively shrink line spacing/font...
- Titles too long to fit after made responsive must be shortened.

**Comment by superbunker** [comment]
Example: 
<img width="1162" alt="Screen Shot 2021-08-06 at 5 05 33 PM" src="https://user-images.githubusercontent.com/47950704/128581706-d83f3801-7673-4ce4-917c-245978db1392.png">

**Comment by henlatourrette** [comment]
@Clue355 is working on an update that would solve this issue on the next PR. We'll check again once it's merged.

**Comment by superbunker** [comment]
I think this is the merged change. Looks like we'll need to work on this some more... 

<img width="953" alt="Screen Shot 2021-08-11 at 1 03 51 PM" src="https://user-images.githubusercontent.com/47950704/129095635-434f191b-650c-4a64-a88a-de76eebb848b.png">

**Comment by superbunker** [comment]
fixed
