### ISSUE TITLE
Create a Guide: Preparing Your Automation for Publication

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#41]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Preparing Your Automation for Publication" guide.

### Action Items
- [x] Write mark-down for the guide instructions in a comment on this issue.
- [x] Create a mark-down file for this guide and add it to a folder called _guides
   - [x] Call the file a name with dashes that is as short as possible
      - [x] prep-automation-for-publication.md
   - [x] Add a header to the file
```
---
title: Preparing Your Automation for Publication
description: Gather the items in this guide before submitting your automation for publication.
status: active
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by NivenPrasad** [comment]
This is what we’ll need from you to prepare your automation for publication on the website: 

Image

A 600 x 400 image that reflects the type of automation
Alt image text
 

Description of Automation

See our Guide to Writing About Your Automation

Health Files

See Supporting Your Automation with Community 


Current status of Automation

 in use and ready to deploy
 in use and being refactored
 ready to deploy
 in development
 ready for development
 in ideation
 abandoned
 If status in use, what codebase can it be seen in?
 
Help wanted (you can list all that apply)

 needs maintenance
 needs support for users
 needs refactoring
 needs documentation
 needs peer review
 needs to be built
 needs to be researched
 needs advice
 Advice Needed: (type in sort description of what you need)
 needs takeover

**Comment by ExperimentsInHonesty** [comment]
---
title: Preparing Your Automation for Publication
description: Gather the items in this guide before submitting your automation for publication.
status: active
display: true
---
# Preparing Your Automation for Publication

## Instructions
This is what we’ll need from you to prepare your automation for publication on the website: 

- [Image](#image)
- [Alt image text](#alt-text)
- [Description of Automation](#description)
- [Health Files](#health-files)
- [Current Status of Automation](#status)
- [As seen on](#as-seen-on)
- [Help wanted](#help-wanted)

<a name="image"></a>
### Image
A 600 x 400 image that illustrates the automation.  

Example 1:
<img src="https://user-images.githubusercontent.com/37763229/92680204-258f5280-f2df-11ea-9946-27d222bddf15.png" width=200px>

Example 2:
<img src="https://user-images.githubusercontent.com/37763229/91668001-92277780-eabd-11ea-893a-a7061a7cb520.png" width=200px>

<a name="alt-text"></a>
### Alt image text
This is some text that helps people who cannot see the image understand what the image portrays

Example 1: 
> Some GitHub profile Images of people who have contributed to the hackforla.org website and titles under some names indicating Designer, Stakeholder, Product all in uppercase text.

Example 2: 
>Jekyll logo with test tube and words Gather Data Types all in green.

<a name="description"></a>
### Description of Automation
 _See our Guide to [Writing About Your Automation](url)_

<a name="health-files"></a>
### Health Files
_See our Guide to [Supporting Your Automation with Community](url)_ 

<a name="status"></a>
### Current Status of Automation

-  in use and ready to deploy
-  in use and being refactored
-  ready to deploy
-  in development
-  ready for development
-  in ideation
-  abandoned

<a name="as-seen-on"></a>
 ### As seen on
_If status in use, what codebase can it be seen in?_
 
<a name="help wanted"></a>
### Help wanted (you can list all that apply)
- needs maintenance
-  needs support for users
-  needs refactoring
-  needs documentation
-  needs peer review
-  needs to be built
-  needs to be researched
-  needs advice
-  Advice Needed: (write a short description of what you need)
-  needs takeover

## Ready to submit your automation?
Use our [issue template](https://github.com/100Automations/Website/issues/new?assignees=&labels=documentation%2C+good+first+issue&template=create-automation-card-for--automation-name-.md&title=Create+automation+card+for+%5Bautomation+name%5D) for submitting the information we will need for the project card to appear on the [100automations.org](https://100automations.org) website
