### ISSUE TITLE
the "Github pre-commit hooks" automation card is taller than the other ones

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#411]
### Depedency
#438 

### Overview
The "Github pre-commit hooks" automation card is taller than the other ones

### Action Items

- [x] Find what's the problem
  - [x] actually verify it
- [ ] Solve it
- [ ] Review it with the team

### Resources/Instructions
If you are not seeing this on your screen, In order to replicate it you can try adding additional words to the Automation title until it appears on two lines.

**Comment by superbunker** [comment]
The bug _seems_ to be the second line of the wrapping title. The header is pushed up and the button below farther down. But this header image is also newer than the other two, so the revised format could be involved.

**verify** 
Dean cant see the bug (Win/Chome). Jason does (Mac/Safari).

<img width="1255" alt="Screen Shot 2021-09-02 at 4 36 57 PM" src="https://user-images.githubusercontent.com/47950704/131929168-a87d8a1f-a5c2-4c46-8c0e-496b40ac7166.png">

**Comment by superbunker** [comment]
Things to test:
 - cut off title so it doesn't wrap, see what happens
 - add text to other two titles to make them wrap, see what happens
 - make sure all three headers are using the same size/format  image

Posible Solutions:
- character limit all automation titles
- make title two lines high for all
- dynamically shrink text to fit

**Comment by ExperimentsInHonesty** [comment]
Possible Solutions comments

- character limit all automation titles
  - possible but a hassle.  Its already hard to get the authors to create the automations with unique but specific names
- make title two lines high for all
  - seems reasonable
- dynamically shrink text to fit
  - Risks the site accessibility rating going down

**Comment by henlatourrette** [comment]
@mdothman is working on figuring out the best solution for the flex box

**Comment by ExperimentsInHonesty** [comment]
This issue is being address by fix that will applied to #438 .  Check again after that issue is closed

**Comment by ExperimentsInHonesty** [comment]
its resolved on this issue
