### ISSUE TITLE
Update Project Status labels to the actual real ones

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#415]
### Overview
Currently, the labels are showing random statuses. We need to update them so that they display the actual real status of each project.

### Action Items

- [x] Change "abandoned" test status
- [ ] Research automations to establish actual status
- [ ] Update the "Needs Help" statuses accordingly
- [ ] Review with the team

### Resources/Instructions
![image](https://user-images.githubusercontent.com/21250505/130157821-d225efca-b92f-4ea5-affd-d2877f5935ec.png)

**Comment by henlatourrette** [comment]
They look currently updated now.

**Comment by superbunker** [comment]
Totally updated

**Comment by superbunker** [comment]
But wait....  ARE they updated? 
Review with team to confirm.

**Comment by henlatourrette** [comment]
Let's check and close this issue if they're already OK now.

**Comment by superbunker** [comment]
The current statuses are plausible... but we haven't actually reviewed the code in future automations

**Comment by henlatourrette** [comment]
I sent slack messages to each of the ones - who seem to me are the project owners - for all three current automation on our main website:
* Pre-commit hooks starter kit, Sophia Alice
* Jekyll Gather Data types, Raudel Blazquez
* True Github contributors, Kian Badie

Still didn't get a reply from any of them but will wait for the following days.
As for the labels situations, they seem to be accurate but I prefer to wait and confirm them with the project owners.

**Comment by henlatourrette** [comment]
Didn't hear back from Sophia and Kian but I did get to chat with Raudel from the "Jekyll Gather Data Types" project.

Raudel told me that "Akib Rhast" was working on a similar project that accomplished the same goal - However, we can conclude that this project status is still "In development".

We still need to confirm the statuses for Pre-commit and True Github contributors

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will ask sophia if the status on "Pre-commit hooks starter kit, Sophia Alice" is correct
currently:
in use and needs further development
Needs Help: Refactoring, Peer review, Advice

Please advise on current status:

Possible Status of project: (must pick one)
- [ ] In Use And Ready To Deploy
- [x] In Use and Needs Further Development
- [ ] In Use And Being Refactored
- [ ] Ready To Deploy
- [ ] In Development
- [ ] Ready For Development
- [ ] In Ideation
- [ ] Abandoned

Needs Help status: (can pick as many as apply)
- [x] Needs Maintenance
- [x] Needs Support For Users
- [ ] Needs Refactoring
- [ ] Needs Documentation
- [x] Needs Peer Review
- [ ] Needs To Be Built
- [ ] Needs To Be Researched
- [ ] Needs Advice
- [ ] Needs Takeover
- [ ] Advice Needed

**Comment by ExperimentsInHonesty** [comment]
added to DS agenda https://github.com/hackforla/data-science/issues/65#issuecomment-947191530

**Comment by salice** [comment]
> @ExperimentsInHonesty will ask sophia if the status on "Pre-commit hooks starter kit, Sophia Alice" is correct currently: in use and needs further development Needs Help: Refactoring, Peer review, Advice
> 
> Please advise on current status:
> 
> Possible Status of project: (must pick one)
> 
> * [ ]  In Use And Ready To Deploy
> * [x]  In Use and Needs Further Development
> * [ ]  In Use And Being Refactored
> * [ ]  Ready To Deploy
> * [ ]  In Development
> * [ ]  Ready For Development
> * [ ]  In Ideation
> * [ ]  Abandoned
> 
> Needs Help status: (can pick as many as apply)
> 
> * [x]  Needs Maintenance
> * [x]  Needs Support For Users
> * [ ]  Needs Refactoring
> * [ ]  Needs Documentation
> * [x]  Needs Peer Review
> * [ ]  Needs To Be Built
> * [ ]  Needs To Be Researched
> * [ ]  Needs Advice
> * [ ]  Needs Takeover
> * [ ]  Advice Needed

Needs additional language support (currently only has Python)

**Comment by henlatourrette** [comment]
Confirmed that 

- [x] Jekyll Gather Data Types didn't change Status
- [x] Pre-commit Hooks Starter Kit was updated as per feedback from Sophia
- [ ] True Github Contributors Status still needs to be confirmed with Kian Badie

**Comment by henlatourrette** [comment]
Hi @KianBadie , can you please help us confirm whether the following status is correct for "True Github Contributors"
- If not, please pick the correct ones.

Possible Status of project: (must pick one)
- [x] In Use And Ready To Deploy
- [ ] In Use and Needs Further Development
- [ ] In Use And Being Refactored
- [ ] Ready To Deploy
- [ ] In Development
- [ ] Ready For Development
- [ ] In Ideation
- [ ] Abandoned

Needs Help status: (can pick as many as apply)
- [ ] Needs Maintenance
- [ ] Needs Support For Users
- [ ] Needs Refactoring
- [ ] Needs Documentation
- [x] Needs Peer Review
- [ ] Needs To Be Built
- [ ] Needs To Be Researched
- [ ] Needs Advice
- [ ] Needs Takeover
- [ ] Advice Needed

Thanks!

**Comment by henlatourrette** [comment]
We can consider this updated for now - as there was no reply from the "True GitHub Contributor" and it seems to have the real status.
