### ISSUE TITLE
Path is wrong for all relative internal links

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#419]
### Overview
Everything with an internal link needs to have "/Website" removed from the path. 

wrong: https://100automations.org/Website/guides/creator_overview.html
correct: https://100automations.org/guides/creator_overview.html 

### Action Items
- [x] Home Page
- [x] About
- [x] Press
- [x] All Guides
- [x] each individual guide
   - [x] community-support-for-automations.md - no internal crosslinks
   - [x] creating-good-project-images.md - no internal crosslinks
   - [x] creating-good-readmes-for-automations.md - no internal crosslinks
   - [x] creator_overview.md - [check](https://100automations.github.io/Website/guides/creator_overview.html)
   - [x] prep-automation-for-publication.md - [check](https://100automations.github.io/Website/guides/prep-automation-for-publication.html)
   - [x] project_card_anatomy.md - [check](https://100automations.github.io/Website/guides/project_card_anatomy.html)
   - [x] self-evaluating-new-automation-idea.md - [check](https://100automations.github.io/Website/guides/self-evaluating-new-automation-idea.html)
   - [x] start_building.md - no links to guides 
   - [x] start_contributing.md - no internal crosslinks 
   - [x] submit_idea.md - [check](https://100automations.github.io/Website/guides/submit_idea.html)
   - [x] suggest-guide-for-100Automations.md - no internal crosslinks
   - [x] using_an_automation.md - no internal crosslinks
   - [x] workflow-guide-for-builders.md - no internal crosslinks
   - [x] workflow-guide-for-ideators.md - [check](https://100automations.github.io/Website/guides/workflow-guide-for-ideators.html)
   - [x] write-your-opensource-automation-creator-bio.md - no internal crosslinks
   - [x] writing-articles-for-automations.md - no internal crosslinks
   - [x] writing-short-descriptions-for-automations.md - no internal crosslinks
- [x] Review it with the team

### Resources/Instructions
- #390 
- #416

**Comment by siddharth1704** [comment]
i  want to work on this kindly assign me this issue

**Comment by kbhavre** [comment]
I will try to work on this issue, please assign this to me

**Comment by superbunker** [comment]
This should be fixed now.

**Comment by henlatourrette** [comment]
I was doing a test clicking at all the links randomly and couldn't find any broken one. So, I guess we can consider this one fixed.

**Comment by superbunker** [comment]
yay
