### ISSUE TITLE
Create a Guide: Supporting Your Automation with Community 

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#43]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Supporting Your Automation with Community" guide.

### Action Items
- [ ] Write mark-down for the guide instructions in a comment on this issue.
- [ ] Create a mark-down file for this guide and add it to a folder called _guides
   - [ ] Call the file a name with dashes that is as short as possible
      - [ ] name: community-support-for-automations.md
   - [x] Add the following header to the file:
```
---
title: Supporting Your Automation with Community
description: In order to save time and provide a consistent experience for creators and users we’ve created default health files for you to customize as appropriate to your project. 
status: active
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by NivenPrasad** [comment]
Supporting Your Automation with Community

100Automations wants to list your automation. In order to do that your automation needs to have: 

- a contributing file to communicate how people should contribute 
   - See GitHub tutorial (link to:   https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
   - Include the type of contribution you’re looking for:
      - maintenance
      - refactoring
      - peer review
      - advice
      - coding
 
- a security file for reporting
a secuirty vulnerability in your automation - see GitHub tutorial (link to: https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository)


- a support file for telling people how to get help for implementing your automation - see GitHub tutorial (link to: https://docs.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project)

- a read.me file 

At 100 Automations, we’re committed a building a strong community who shared value is reduction of repetitive work - whether that is from not having to write code more than once or answer the same question more than once for a lack of documentation.

So we’ve created default health files for you to customize as appropriate to your project. 

Additionally, we seek to reduce the amount of time that individual authors will have to spend to properly monitor the people using and contributing to these automations by creating a shared support space, which you’ll see referenced in the contributing, support, and security files

Links (github, slack channel url, Testing Site, Live Site, etc.)
Healthy project files (see resources for instructions)
 Readme.md URL
 contributing.md URL
 security.md URL
 support.md URL
 Licence file - we recommend GNU 2.0 - see GitHub guidelines on adding a licence
 Code of Conduct
   - If you’re creating a new automation, we have set up the Code of Conduct for you already (not to be amended)
   - If you are importing your automation from elsewhere, add our default Code of Conduct

**Comment by ExperimentsInHonesty** [comment]
In order to finish the above draft we need to do the following:
- [ ] Add a template file for the following types and link them
   - [ ] CONTRIBUTING.md
   - [ ] SECURITY.md
   - [ ] SUPPORT.md
   - [ ] README.md
- [ ] Write an overview for 
   - [ ] readme
   - [ ] license sections
- [ ] Add a link to the Code of Conduct file on true-github-contributors once kian has accepted the PR

**Comment by ExperimentsInHonesty** [comment]
This can be turned into a guide once the readme guide is done and linked - see Issue https://github.com/100Automations/Website/issues/36

**Comment by NivenPrasad** [comment]
Checklist completed. Now closing issue.
