### ISSUE TITLE
Bug: Mobile - Content Bust-out from the screen

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#438]
**Describe the bug**
On Mobile, the Homepage content Bust-out from the screen.

**To Reproduce**

**Expected behavior**

**Screenshots**

![IMG_0509](https://user-images.githubusercontent.com/47950704/131790859-fbd9896c-4ee4-49e3-8a69-ae21008c5ebc.png)

![IMG_0508](https://user-images.githubusercontent.com/47950704/131790824-367154a0-4347-4d58-956a-6f2203c52d34.png)

**Desktop (please complete the following information):**
 - OS: iPhone 6s
 - Browser: Safari

**Smartphone (please complete the following information):**

**Additional context**
It doesn't show the same behaviour on an Iphone 6plus with chrome browser.

**Comment by ExperimentsInHonesty** [comment]
[Figma for HfLA design system](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144)

see example 
Our Toolkit title on https://www.hackforla.org/toolkit/
```
<h1 class="title1">Our Toolkit</h1>
```
https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss

**Comment by henlatourrette** [comment]
This is already fixed.
