### ISSUE TITLE
Bug: Desktop - No Space to the Left of the Paragraph (About Page)

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#439]
**Describe the bug**
On Desktop, there's no space to the left of the paragraph on the top section of the page

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot from 2021-09-02 15-12-15](https://user-images.githubusercontent.com/54788134/131909951-46fa71bb-ecef-4afd-a703-4380fcfa3b47.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by citrusapple** [comment]
@Clue355 please make paragraph margin for desktop match figma

**Comment by ExperimentsInHonesty** [comment]
1. Progress: almost done
2. Blockers: none
3. Availability: good
4. ETA: 10/15
