### ISSUE TITLE
Create Guide: Evaluating A New Automation Idea

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#44]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Evaluating A New Automation Idea" guide.

### Action Items
Content
- [ ] Write a draft outline

Product
- [ ] Paste mark-down for the guide instructions in a comment on this issue.
- [ ] Create a mark-down file for this guide and add it to a folder called _guides
   - [ ] Call the file a name with dashes that is as short as possible
      - [ ] name:
   - [ ] Add a header to the file and add the name of guide where it says title
```
---
title:
description:
status: coming soon
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)
[Automations Proposal Template](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal)

**Comment by NivenPrasad** [comment]
Create or Publish Your First Automation

COMING SOON

**Comment by Olivia-Chiong** [comment]
Ideas to include
- Make sure it does not already exist
- Is it feasible?
- Time required to code it vs time required for the task

**Comment by superbunker** [comment]
Created placeholder document in _guides: [Evaluating Your New Automation Idea](evaluating-new-automation-idea.md)

**Comment by superbunker** [comment]
Progress: Made updates based on comments
Blockers: no
Availability: lookin' good
ETA: Draft seems pretty close to done

**Comment by Olivia-Chiong** [comment]
Change title to "Self-Evaluating an Automation Idea"

**Comment by superbunker** [comment]
Updated with suggested changes, and adding more items from the Automations Proposal Template

**Comment by Olivia-Chiong** [comment]
@superbunker to update this into new PR.

**Comment by NivenPrasad** [comment]
PR approved and merged. Issue now moving to Done.

**Comment by Olivia-Chiong** [comment]
We need to include a link at the bottom of this readme to [Automation Proposal](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal)

**Comment by superbunker** [comment]
Just have to remind myself to do this -- will try to do it later today

**Comment by superbunker** [comment]
Sorry, I should have asked this sooner... 
The Automation Proposal link will open a new github issue with the template text in it?

**Comment by superbunker** [comment]
added the following at the end of evaluation guide:

## Propose your automation
Once you're ready, fill out the [Automation Proposal](https://github.com/100Automations/futureautomations/issues/new?assignees=&labels=documentation%2C+review&template=-automation-proposal.md&title=%5BAutomation+Name%5D+Proposal) which will add your automation as a Future Automations issue.

Made pull request

**Comment by Olivia-Chiong** [comment]
Fixed with a PR.
