### ISSUE TITLE
Press page button behavior

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#440]
## Description of bug
Buttons dynamically resize as squished rectangles. They should remain square. 

### Platform/Devices/Browsers
all desktop versions

## Reference/Info 
![image](https://user-images.githubusercontent.com/37763229/131055823-8a452c14-0892-4dc4-a9c4-76e7c1c2df51.png)

**Comment by superbunker** [comment]
Should be good for responsive (a bit of overlap w/ content at very small squish) but needs more testing on native mobile.

**Comment by superbunker** [comment]
Doing some more testing on mobile

**Comment by henlatourrette** [comment]
The box sizes are fine now. but the design is not matching figma. @citrusapple will create a new issue for the figma matching part.

**Comment by citrusapple** [comment]
compared Figma and desktop site, design matching.  Mobile display issue (icons not stacking) opened at #461
