### ISSUE TITLE
Menu doesn't highlight active page

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#453]
## Description of bug
Menu not highlighting the current page

### Platform/Devices/Browsers
- [ ] make it highlight!
- [ ] review

## Reference/Info 
sitewide issue (i think)

![image](https://user-images.githubusercontent.com/21250505/131757491-7c697636-fd0c-4b38-9cc6-7345d4b32493.png)

Figma:
<img width="1440" alt="All Guides_Desktop" src="https://user-images.githubusercontent.com/78511203/131231982-87d33d1f-8638-40e3-bd2c-3515d98f93db.png">

**Comment by superbunker** [comment]
hey!

**Comment by superbunker** [comment]
Thought this was a duplicate, but can't find the original. So!

**Comment by henlatourrette** [comment]
it's fixed!
