### ISSUE TITLE
Bug: Compare live site to Figma image files for desktop and mobile version.

### ISSUE THREAD

**Issue by citrusapple** [100Automations/Website#458]
## Describe the bug
"Press" desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:

See issue #426 
## References
![image](https://user-images.githubusercontent.com/24448751/134259273-8b153033-2af8-4123-92f6-9c89e9e959d0.png)
![image](https://user-images.githubusercontent.com/24448751/134259329-1cde62e1-95ba-42b0-ad8f-31580e83302a.png)

**Comment by superbunker** [comment]
#459 (and some other issues) covers this in more detail. Closing this one.
