### ISSUE TITLE
Document 100 Automations team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#460]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the 100 Automations team to help match your project with available volunteers.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [x] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/100-automations
- Times that VRMS shows for your meetings: 
  - Thursday 5:00 pm, 1 hour
  - Saturday 2:00 pm, 2 hours

**Comment by henlatourrette** [comment]
Tuesday - PM meeting
  - [x] day: Tuesday at 4
   - [ ] start_time:
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 60 
   - [x] name_of_meeting:  PM meeting
   - [x] who_must_attend
      - [x] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: automators

**Comment by henlatourrette** [comment]
Thursday - Team Meeting

- [x] day: Thursday
   - [ ] start_time: 5:00
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 60
   - [x] name_of_meeting: Team Meeting
   - [x] who_must_attend
      - [x] pm
      - [x] all_leads
      - [x] design_lead
      - [x] research_lead
      - [x] frontend lead
      - [x] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [x] design
      - [x] research
      - [x] frontend
      - [x] backend
      - [x] data_science
      - [x] other: please explain
   - [x] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: automators

**Comment by henlatourrette** [comment]
Saturday - PM/Org Meeting

- [x] day: Saturday
   - [ ] start_time
      - [ ] AM
      - [x] PM: 2 PM
   - [x] duration_in_min: 120
   - [x] name_of_meeting: Team Meeting ( or just PM/Org Meeting?)
   - [x] who_must_attend
      - [x] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_can_attend
      - [ ] pm
      - [x] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: automators

**Comment by henlatourrette** [comment]
Just a quick update regarding the Google Calendar meetings -> We already changed the ownership of all meetings to the 100automations@hackforla.org account.
But we still need to change the meeting times according to the agreed schedule.

**Comment by henlatourrette** [comment]
We are removing the Tuesday meetings and leaving only Saturday as the PM/Org meetings. Team meetings will happen on Thursdays at 5 PM.

**Comment by henlatourrette** [comment]
Already agreed on the new meeting times and updated the related [HackforLA issue ](https://github.com/hackforla/CivicTechJobs/issues/35)- we removed the Tuesday meetings.
There was no need to update the [project page on HfLA website](https://www.hackforla.org/projects/100-automations) as the meeting times kept were already the original ones: Thu from 5 to 6 pm & Sat from 2 to 4 pm.

**Comment by henlatourrette** [comment]
I'm closing this issue since there's nothing else to update for now.
