### ISSUE TITLE
Bug: Assets, team, fact sheets icons not displaying properly on mobile

### ISSUE THREAD

**Issue by citrusapple** [100Automations/Website#461]
## **Describe the bug**
Assets icon on press page is not on screen on mobile view

## **To Reproduce**
mobile only

## **Expected behavior**
icons should stack according to figma final page design.

## **Screenshots**
Current state on Andriod/ Chrome:
![Screenshot_20210923-173347](https://user-images.githubusercontent.com/24448751/134757989-df649777-9d47-4f33-a52c-152705b70169.jpg)

figma design:
![image](https://user-images.githubusercontent.com/24448751/134757961-3937b509-c7ef-4cd7-bf62-0ea8b498341a.png)

**Comment by henlatourrette** [comment]
![8CC2E701-A2DD-40A4-9BA6-700E3540BA96](https://user-images.githubusercontent.com/21250505/136480669-a2d838ba-c8d1-4bbe-bf44-6bfe75871a8e.png)

**Comment by henlatourrette** [comment]
It's fixed!
