### ISSUE TITLE
Create a guide: Writing a Technical Description for Your Automation

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#47]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Writing a Technical Description for Your Automation" guide.

### Action Items
- [ ] Write mark-down for the guide instructions in a comment on this issue.
- [ ] Create a mark-down file for this guide and add it to a folder called _guides
   - [ ] Call the file a name with dashes that is as short as possible
      - [ ] name: writing-technical-descriptions-for-automations.md
   - [ ] Add the following header to the file:
```
---
title: Write a Short Technical Description about Your Automation
description:
status: coming soon
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by citrusapple** [comment]
guides have been written [Readme](https://100automations.org/guides/creating-good-readmes-for-automations.html) and [supporting automation with your community.](https://100automations.org/guides/community-support-for-automations.html)
