### ISSUE TITLE
Update [Pre-commit Hooks Starter Kit] card "Needs Help" information 

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#479]
### Overview
The current "Needs Help" information doesn't show the current requirements.

According to the [Pre-commit Hooks Starter Kit] Automation Owner, the current help requirements are the following:
- Needs Maintenance
- Needs Support For Users
- Needs Peer Review

### Action Items
Update the Needs Help information
Review it with the team

### Resources/Instructions
[Automation Owner's comment with the update](https://github.com/100Automations/Website/issues/415#issuecomment-954391983)

**Comment by henlatourrette** [comment]
hey, @superbunker do you think you can take on this issue? it seems to be a small and easy one but I don't know how to do it. Or maybe you can show it to me? As I think this can be a regular thing to do in the future as we add more automations.

**Comment by superbunker** [comment]
@henlatourrette yep, i got it. 
It's easy — I'll show you where it is next meeting

**Comment by superbunker** [comment]
pull request #480

**Comment by henlatourrette** [comment]
This issue is already done. The card is updated, we can close the issue.
