### ISSUE TITLE
Revise the Creator Overview guide

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#482]
## Overview
This is the generic landing page for all possible modes of contribution. It currently just points users to the starter guide they want. But since it's the topmost call to action, perhaps it could be more helpful?

## Action Items
- [x] Add current text below in the comments of this issue
- [ ] discuss
- [ ] revise
- [ ] publish

## Additional Info
- source: [Creator Overview](https://github.com/100Automations/Website/blob/gh-pages/_guides/creator_overview.md)
- [overall workflow diagram](https://www.figma.com/file/IL9pYQDnj1V0emSZK3UECa/workflow%3A-builder?node-id=0%3A1)

**Comment by superbunker** [comment]
current Creator Overview text:

--- 
**Want to know how to start creating automations?**

There are many ways to contribute to the 100 Automations project. Whether you have an excellent idea but don't know how to build, or you have an automation that needs improvement, or you have an idea and are excited to build it here. We have something for you.

## Suggest an Automation
If you have an idea start by reading our [Ideators Guide](/guides/submit_idea.html)

## Build an Automation Idea
If you are interested adding an automation you've already made or have been working on, take a look at our [Builders Guide](/guides/start_building.html)

## Contribute an Automation
If you just want to contribute to an existing automation, you can do so by checking out the [Contributors Guide](/guides/start_contributing.html)

**Comment by ExperimentsInHonesty** [comment]
LGTM
