### ISSUE TITLE
Project: 100Automations: Google Drive Migration

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#484]
### Overview
We need to Migrate the Files to the Google Shared Drives. Currently they're all under personal Drives.

### Action Items
Move Files to the Shared Drive
Review it with the team

### Resources/Instructions
[Guide on How to Do It](https://github.com/hackforla/knowledgebase-content/issues/66)

**Comment by citrusapple** [comment]
Created copy of existing files to new [shared drive](https://drive.google.com/drive/u/0/folders/0AFXxG16I9WmnUk9PVA).  Would like to get confirmation for what to do with previous drive owned by bonnie.  Should we delete the old copies or just revert access for everyone for the old folder? Once confirmed we can let everyone know on slack channel.

**Comment by citrusapple** [comment]
PM meeting 11/9 cannot download and upload migrate files from old drive to new shared drive.  Will delete the uploaded files and migration of files will be done owner by owner.

**Comment by henlatourrette** [comment]
We managed to move all the files now owned by active and inactive owners. We'd just need to do a final review to check nothing was pending.

**Comment by henlatourrette** [comment]
We can consider this to be finished. There's nothing else to move. Thanks to everyone for contributing to this!
