### ISSUE TITLE
hide the workflow guides from all guides list

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#486]
## Overview
The workflow for incoming contributors is in flux. The two workflow guides do not explain the overall process — they describe the columns of the futureautomations kanban board. For now, we'll take the guides out of the "all guides" list, but leave them online so we can discuss and revise them.

## Action Items

- [x] change category of guides to "0" to remove them from all guides list
- [x] confirm
- [x] review with team

## Resources/Instructions
- [Workflow for Ideators](https://100automations.org/guides/workflow-guide-for-ideators.html)
- [Workflow for Builders](https://100automations.org/guides/workflow-guide-for-builders.html)

**Comment by superbunker** [comment]
Confirmed that changing category to 0 removes them from all guides list while leaving guide online

**Comment by henlatourrette** [comment]
It's not useful yet at this moment - it can even confuse people - that's why we're hiding it right now.
