### ISSUE TITLE
fix google form

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#488]
## Overview
Google form submissions currently aren't being added as futureautomations issues. This was recently working, so something must have changed.

## Action Items
- [x] research and document how form was built 
- [ ] rebuild connection to the form 
   - [x] duplicate form as 100automations 
   - [x] rename (unpublish?) old superbunker-owned form and sheet
   - [x] connect responses of new form to a new sheet
   - [ ] get personal token for 100a account (requires 2FA)
      - [x] test with superbunker token
      - [x] test with old token (akib's)
   - [x] add app script to google sheet
      - [x] publish, deploy, versioning, trigger, uhhgggg
   - [ ] change all links to the form
      - [x] ideator's guide
      - [x] futureautomations board
      - [x] fa issue template - config.yml
      - [x] self-evaluating a New Automation Idea (linked to fa board)
   - [ ] various formatting and fussiness
   - [ ] test and revise
- [ ] review: ensure submissions go into the icebox with proper labels, etc
- [ ] Bonus Round: send an issue to the website project board too, alerting of new submission

## Resources/Instructions
Address of the new form:
https://docs.google.com/forms/d/e/1FAIpQLSemmRJ1tBDVrGtPpwpxLVCQbw2O-tVVRpcbRW3SzRdNbZ9olg/viewform

New form, shortened:
https://forms.gle/daURL7woEeCNans89

- [Broken Automation Proposal Form](https://docs.google.com/forms/d/e/1FAIpQLSeGJrU92Tj5Ft763MMWpSwyB6VqctPXzu8WKIy4xTjf1nJg0Q/viewform), [shortened](https://forms.gle/u4mRKgEZ8yDEbCMw9)
- [GitHub Issues API](https://docs.github.com/en/rest/reference/issues#create-an-issue)

apps script dashboard:
https://script.google.com/home/projects/1qT70DBmD4KgJMUPh_mTtsSQb1IBKhDkT3gjMIzsniOjGKMl0y_c9ACcK

### Related Issues:
- #223
- #241
- #189

**Comment by superbunker** [comment]
Linked google form seems to be owned by superbunker@gmail. ~Perhaps there's another form out there.~

Ah, yes. [Google made it impossible to change ownership](https://www.techtimes.com/articles/257610/20210303/google-forms-no-longer-allowed-to-be-transferred-to-other-accounts-as-part-of-new-privacy-protection-rule.htm) The form will have to be copied/recreated by the 100automations account. After we figure out how it's supposed to be working.

**Comment by superbunker** [comment]
Form is referenced in this yml : 
https://github.com/100Automations/futureautomations/blob/master/.github/ISSUE_TEMPLATE/config.yml

Can't find any other relevant code in GitHub

**Comment by superbunker** [comment]
## Research
There are zaps set up in the 100automations@hackforla Zapier account for GitHub and Google Sheets. 

GitHub issue to google sheet is still working. Wait.... this is sending all our issues to a google sheet? 
Is this even for the project submission form?

Zapier has an active connection to our GitHub. There's a zap still actively [updating a google sheet](https://zapier.com/app/editor/108805557?redirect=true) with each idea submission! My test submission is there. That zap last edited jun 17, 2021

There's also a zap for "[Create GitHub issues from new Google Forms responses](https://zapier.com/app/editor/117681350?redirect=true)" which is turned off and has never run. Setup isn't complete—no GitHub account selected. 
So...  what was creating the GitHub issue? 

Looks like prior comment ("akibrhast to set up the Google Form with an script and the GitHub API") is how it was done. But aside from that one YML reference, can't find any code for this in our repos.

**AH! Gotcha. It's a [script in the google sheet](https://script.google.com/u/1/home/projects/1XQlrkRmrvAaZLyW_D4m6XgwytYtfvJzLOe-QEPQ0PjUiVYdu4_kee7k9/edit) that form responses go in.** 
[Instructions for setting it up](https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b). (actually this seems to be a slightly different script)
[Another set of instructions for doing this with app script](https://gist.github.com/bmcbride/62600e48274961819084)
But wait... this script has the assignee as Olivia, and we changed that. Is there another script? Another form?

HERE we go: "The app is requesting access to sensitive info in your Google Account. Until the developer (superbunker@gmail.com) verifies this app with Google, you shouldn't use it." 
So I gotta copy the form as 100a so it has correct permissions, set up the script again, and change every link to the form.
Yaaaaaay..
oh hang on, It's letting me jump through "unsafe" hoops to give the script permissions to run....

**Comment by superbunker** [comment]
Address of the new form:
https://docs.google.com/forms/d/e/1FAIpQLSemmRJ1tBDVrGtPpwpxLVCQbw2O-tVVRpcbRW3SzRdNbZ9olg/viewform

Short:
https://forms.gle/daURL7woEeCNans89

**Comment by superbunker** [comment]
## Notes 
For users to get a copy of their responses, the form needs to "collect email" — the question asking for email is duplicated, and should be removed. 
On second thought, i'd have to re-do the sheet and probably re-deploy the app to get the fields right. Better to just turn off the send copy function 
on third thought, the form was created with duplicate email fields, lol

Have to deploy (web app?) and add the trigger. Ohhh wait. the function is *named* onFormSubmit? That seems odd.

[versions](https://stackoverflow.com/questions/22617138/function-not-found-error-when-making-both-get-and-post-requests-to-a-web-app). wtf

WORKING.  ugh only took two days. If the script is changed, i think it needs to be saved (floppy icon) and redeployed to a version - "Publish" allows a version to be updated. Let's see.  Yes! working with old token. 

But it looks like "project" isn't in the API, so not added to the board.

This looks handy:
https://github.com/marketplace/actions/assign-to-one-project
Oh ho! what's this! Secret is already there? https://github.com/srggrs/assign-one-project-github-action/issues/61
Creating a new issue for deploying this workflow to FA

Plot twist: there was *also* a script in the form itself. That might be better than form-to-sheet-to-issue? Contrariwise, the sheet is a backup

**Comment by henlatourrette** [comment]
The Google form is now working. A related issue was opened to work on having the new issue created through the google form go to the Project Board >> #491
