### ISSUE TITLE
Create a logo for 100 Automations

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#49]
### Overview
We need to create a logo for the project.

### Action Items
- [x] Ideate themes
- [x] Ideate first designs
- [x] Discuss with group and produce finalists or new version
- [x] Get feedback
- [x] Finalize logo
- [x] Clean up the Figma page with logo 

### Resources/Instructions

[Project Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Comment by NivenPrasad** [comment]
@CamilaArias when done cleaning up Figma page for logo, you can go ahead and close this issue.

**Comment by CamilaArias** [comment]
Forgot to do this. The logo is in the Branding page with the different variants and explorations have been moved to the Logo Explorations page.
