### ISSUE TITLE
Make sure the Icons are updated once the "Languages & Technologies" for each Automation Card is changed

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#490]
### Overview
Once the "Languages & Technologies" for each Automation Card is updated, we need to make sure the icons are updated.

![image](https://user-images.githubusercontent.com/21250505/141398961-fd746e08-2a92-4868-9287-b70992b8bc7d.png)

### Dependency
#137 

### Action Items
Check and update if necessary the "Languages & Technologies" for the current projects:
- [ ] Pre-commit Hooks Starter Kit
- [ ] Jekyll Gather Data Types
- [ ] True Github Contributors

### Resources/Instructions
100 Homepage
Each project's repo
[Jekyll Gather Data Types](https://github.com/100Automations/Website/blob/gh-pages/_automations/jekyll-gather-data-types.md)

**Comment by superbunker** [comment]
created duplicate, but more detailed issue. Closing this one.
