### ISSUE TITLE
edit issue templates

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#496]
## Overview
The issue templates are outdated — two for bios (we don't have bios), one for the wiki (we don't really use the wiki), one for suggesting a guide (we already have too many guides), and _Standard Issue_ is hard to deal with. Bug Issue template should also be more clear and relevant (eg: no way to report GitHub permissions issue)

## Action Items
- [x] edit Standard Issue template for ease of use
- [x] remove superfluous issue templates 

## Resources/Instructions
- [Issue Templates](https://github.com/100Automations/Website/tree/gh-pages/.github/ISSUE_TEMPLATE)

**Comment by superbunker** [comment]
Pull request (#497) for [standard issue](https://github.com/100Automations/Website/blob/gh-pages/.github/ISSUE_TEMPLATE/standard-issue-template.md) format change

I suggest we delete these superfluous templates: 
 - [Suggest a guide](https://github.com/100Automations/Website/blob/gh-pages/.github/ISSUE_TEMPLATE/suggest-a-guide.md)
 - [Wiki Improvement Template](https://github.com/100Automations/Website/blob/gh-pages/.github/ISSUE_TEMPLATE/wiki-improvement-template.md)
 - [Write Bio - Content Creator template](https://github.com/100Automations/Website/blob/gh-pages/.github/ISSUE_TEMPLATE/write-bio---content-creator-template.md)
 - [Write Bio - Site Builder](https://github.com/100Automations/Website/blob/gh-pages/.github/ISSUE_TEMPLATE/write-bio---site-builder.md)

**Comment by henlatourrette** [comment]
I reviewed and merged the PR for the Standard Issue format change.

**Comment by superbunker** [comment]
removed: suggest a guide (we have too many guides already)

Review: 
Wiki suggestion —not useful, but is currently linked from wiki
Bios — not currently used on the site, but may be, someday.

**Comment by ExperimentsInHonesty** [comment]
removed the wiki.  keeping the bios for now
