### ISSUE TITLE
hide "suggest a guide" guide

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#499]
## Overview
The "suggest a guide" guide does not seem to serve a useful purpose. Prior to deletion, we should remove it from public view and discuss its utility.

## Action Items
- [x] hide "suggest a guide" guide from the all guides list
- [ ] discuss its utility

### Resources/Instructions
- [How to suggest a guide for 100 Automations](https://github.com/100Automations/Website/blob/gh-pages/_guides/suggest-guide-for-100Automations.md)

**Comment by henlatourrette** [comment]
It's already hidden. The file still exists but it's not visible on the public site. We don't see a need for it to show up on the website at this time
