### ISSUE TITLE
One-sheet for project

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#5]
### Overview
Write a one-sheet for the 100Automations project including milestones for the next 6 months.

### Action Items

- [x] Review VRMS one-sheet
- [x] Review Civic Opportunity Project one-sheet
- [x] Produce First Draft of 100Automations project
- [x] Prepare questions for review with Bonnie

### Resources/Instructions
[VRMS Doc](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit
)

[Civic Opportunity Project](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf
)

[100Automations One-sheet](https://docs.google.com/document/d/1Bk2uMaSdiZTKu9c-BMXSsC-Gk-ohK_NcmodQRvrgjTU/edit)

**Comment by NivenPrasad** [comment]
Purpose of project:
Make it as easy as possible for the following:
- People to get credit for high-value contributions to GitHub and general open source community
- To publicize useful code to reduce repetitive work across the above community
- Website maintenance to support the above goals
- We want to encourage people to have a place to connect their automation ideas with talent to bring those automation ideas to life
- To publicize projects that utilize the automations that are created
- To have guides for people to level up on creating automations
- Get an automation without having to dig through a repository with all kinds of other code
- Be a magnet for currently unknown automation authors to our community
- Knowledge transfer and growth of the overall open source Civic Tech community

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad my edits are done.  Its ready to make into a pdf.  When you have the pdf link add it to the readme.  Here is an example of a project that has one: https://github.com/hackforla/civic-opportunity/blob/master/README.md

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty pdf of one-sheet now uploaded so moving this issue to the Done column

[100Automations Project One-sheet](https://github.com/100Automations/Website/blob/master/100Automations_Project_One_Sheet.pdf)
