### ISSUE TITLE
Memes for Social 

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#50]
### Overview
We need some clever memes for social.

### Action Items
- [x] List all pain points that 100 Automations is designed to solve
- [x] Add brief text that describes the pain and the solution in a pair

### Resources/Instructions
[Requirements Doc](https://docs.google.com/document/d/1GvI9SssKWr0ewXgjM9qCEB8rSgmKyQpiLKZt2PbGafM/edit#heading=h.4g4fancxvw7h)
[Project One-sheet](https://docs.google.com/document/d/1Bk2uMaSdiZTKu9c-BMXSsC-Gk-ohK_NcmodQRvrgjTU/edit)
[All documentation tickets](https://github.com/100Automations/Website/projects/1?card_filter_query=label%3Adocumentation)

**Comment by ExperimentsInHonesty** [comment]
Here is how the memes address our issues
- Automation Creators
Bernie - share your automation with us
Gru, office, headache - pain point is doing unnecessary work
simpsons - pain point is helping but not really helping
Spong Bob - pain point needs peer review (could be better addressed)
Crying cat , applause- not getting enough recognition
Girl - needs advice
Change my mind guy - pain point documentation
Brue lee - learn how to write better coe

- Automation Ideators
Bernie - share your ideas with us
Kayne - pain point: meeting developers
will ferrell mind reader - learn how to share with other developers

-Mentors of Automation Creators
samurai - need peer review

- People who want to promote the 100 Automations site

- People who used the automations
crime tracking board - pain point is trying to use others code when its inside of their project
mind meld, shera- pain point is badly documented code
toy story - pain point is finding solutions
change my mind guy - find something already done
Confused by charts guy - code is hard to use

**Comment by ExperimentsInHonesty** [comment]
@CamilaArias will still need one or more that demonstrate that mentoring Automations creators is exponential value

**Comment by CamilaArias** [comment]
- Meme for Product Managers - Mr Bean wink
- Meme for Employers - something about you don't know nothing about a developer but if they code automations or have been mentored by 100A you know they're good?
- Ideas for closed source vs open source

@ExperimentsInHonesty could you comment the wording for the first two? Not sure what sounds good.

**Comment by ExperimentsInHonesty** [comment]
Mr Brean - PM - when you see an increase in traffic because you publicized your project by extracting and publishing reusable code on 100Automations and it drives traffic to your project which was your intention all along

**Comment by ExperimentsInHonesty** [comment]
Employers - Evaluating a Developer from their GitHub and LinkedIn profile - Developers who publish their work on 100Automations

**Comment by ExperimentsInHonesty** [comment]
Developers who go it alone vs Developers who are part of the 100Automations community
wandering in the desert or picture of guy in basement vs community picture (peer review, mentorship, users)

**Comment by ExperimentsInHonesty** [comment]
Organizations making Civic Tech tools using closed source (wolf in sheep's clothing)
vs using open source (a lot of people helping each other)

**Comment by ExperimentsInHonesty** [comment]
mentoring automation developers
![Screen Shot 2020-11-07 at 2 35 01 PM](https://user-images.githubusercontent.com/37763229/98452686-70262300-2106-11eb-8542-4e2e9998de94.png)

**Comment by NivenPrasad** [comment]
@CamilaArias and I made a meme for: 
Employers evaluating potential candidate's competency  through their LinkedIn and GitHub vs candidate's contribution to 100 Automations

**Comment by ExperimentsInHonesty** [comment]
https://www.pxfuel.com/en/free-photo-qnlut
![people-city-diverse-diversity](https://user-images.githubusercontent.com/37763229/100530131-f7653480-31a2-11eb-9c14-d89e81fc592d.jpg)
![business-businessman-businesswoman-caucasian](https://user-images.githubusercontent.com/37763229/100530133-fc29e880-31a2-11eb-958b-c4bc356db51c.jpg)

https://www.pikrepo.com/fksik/man-in-black-suit-jacket-doing-peace-sign
![man-in-black-suit-jacket-doing-peace-sign](https://user-images.githubusercontent.com/37763229/100530143-14016c80-31a3-11eb-9e1a-0391e2e01778.jpg)

https://www.needpix.com/photo/download/1756411/achievement-agreement-arms-caucasian-cheerful-colleague-communication-cooperation-deal
![achievement-3829637_1280](https://user-images.githubusercontent.com/37763229/100530154-3abfa300-31a3-11eb-8c6d-bc20a90b48dd.jpg)

https://www.piqsels.com/en/public-domain-photo-jibua
![achievement-agreement-arms-asian](https://user-images.githubusercontent.com/37763229/100530170-65116080-31a3-11eb-98bb-e3b8dbab860f.jpg)

https://www.piqsels.com/en/public-domain-photo-jzvap
![action-adult-asian-black](https://user-images.githubusercontent.com/37763229/100530341-9ab74900-31a5-11eb-9e95-286f900979b3.jpg)

https://www.piqsels.com/en/public-domain-photo-zkiqy
![achievement-adult-agreement-arms](https://user-images.githubusercontent.com/37763229/100530346-b15da000-31a5-11eb-9bb6-6a4bd91981bc.jpg)

https://www.piqsels.com/en/public-domain-photo-zwyjk
![action-brainstorming-business-caucasian](https://user-images.githubusercontent.com/37763229/100530356-cafee780-31a5-11eb-81a4-4daa7d5245cc.jpg)

https://www.piqsels.com/en/public-domain-photo-jmxjc
![adults-bump-collaboration-colleagues](https://user-images.githubusercontent.com/37763229/100530359-dc47f400-31a5-11eb-9ae7-fea8f9fd5809.jpg)

https://www.piqsels.com/en/public-domain-photo-zkmsm
![cheerful-colleague-desk-expression](https://user-images.githubusercontent.com/37763229/100530367-07cade80-31a6-11eb-8ff4-457394238eac.jpg)

**Comment by CamilaArias** [comment]
Uploading memes here: https://drive.google.com/drive/folders/10vaCzqqoAGc6STIlYEKUZ_6y9nTjSF-n?usp=sharing

**Comment by NivenPrasad** [comment]
@CamilaArias has updated folder and Figma.
