### ISSUE TITLE
hide "write your bio" guide

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#500]
## Overview
The "Write your Open Source Automation Creator Bio" guide does not seem to serve a useful purpose, since we do not have a workflow for adding and editing bios. Prior to deletion, we should remove it from public view and discuss its utility.

## Action Items
- [x]  hide the "Write your Open Source Automation Creator Bio" guide from the all guides list
- [ ] discuss its utility

### Resources/Instructions
- [Write your Open Source Automation Creator Bio](https://100automations.org/guides/write-your-opensource-automation-creator-bio.html)

**Comment by ExperimentsInHonesty** [comment]
In order to hide a guide, we only need to change its category in the front matter
category: 0

see: https://github.com/100Automations/Website/blob/gh-pages/_guides/write-your-opensource-automation-creator-bio.md

**Comment by ExperimentsInHonesty** [comment]
The utility of this guide is getting bios from the creators during the process, so that when we start to do publicity we can share that with anyone who wants to write an article about us.
