### ISSUE TITLE
Write Bio - Content Creator: Ava Li

### ISSUE THREAD

**Issue by Aveline-art** [100Automations/Website#503]
### Overview
We need some info to put on our site about you, so that we can market your automation.

### Action item
- [x] Provide 
   - [x] Name
   - [x] Bio: _A 1-2 paragraph professional bio_
   - [x] Quote:  _A quote from you about automations_
   - [x] Motivations
      - [x] Internal:  _What are your internal motivations for creating an automation?_
      - [x] External: _What are your external motivations for creating an automation?_
   - [x] Picture - _Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by Aveline-art** [comment]
## Ava Li ([Linkedin](https://www.linkedin.com/in/aveline-art/))

### Bio

Ava is a technical lead for the CivicTechJobs project at HackForLA. Her day to day work includes managing the security and integrity of the project, compiling developer requirements into easy to complete tickets, and using digital solutions to improve team performance. As a technical lead, she has delivered multiple automations aimed at removing repetition and redundancy when managing a project, so that team members can focus on delivering a stellar product. To her, the role of a technical lead means showing strong leadership by reducing inefficiencies in the system she is tasked to oversee.

Outside of coding, Ava is an avid Dungeons and Dragons player and is pretty good at making tasty food. On the weekends, she can either be found reflecting on her D&D characters or testing out cool recipes that she had stumbled upon online. If you ever meet her, she will probably be very shy. The best way to get her excited is to start a conversation about her cool coding projects, her last D&D session, or what she is planning to cook next weekend.

> "I started making automations because they uplift the productivity of the entire team and gear them towards the successful completion of a project."

### Motivations:
  - Internal: Automations are a fun little thing to do that takes up only a week of my time but quickly produces great results. They are a lot more meaningful than a random project that only showcases my coding ability.
  - External: I want to do something that will support lots of people because I helping others accomplish great things give me a strong sense of accomplishment!

**Comment by ExperimentsInHonesty** [comment]
Hi @Aveline-art 

Can I change one word in the bio?

Currently it says

> Ava is a technical lead for the CivicTechJobs project at HackForLA. Her day to day work includes managing the security and integrity of the project, compile developer requirements into easy to complete tickets, and using digital solutions to improve team performance....

I want to change the word compile to compiling.  Is that ok?

Bonnie

**Comment by Aveline-art** [comment]
> Hi @Aveline-art
> 
> Can I change one word in the bio?
> 
> Currently it says
> 
> > Ava is a technical lead for the CivicTechJobs project at HackForLA. Her day to day work includes managing the security and integrity of the project, compile developer requirements into easy to complete tickets, and using digital solutions to improve team performance....
> 
> I want to change the word compile to compiling. Is that ok?
> 
> Bonnie

Yes, that is fine. I have already corrected that grammar mistake. Everything should look good now! :)

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art Thank you for the change.  Its perfect.  I love your quote and bio.  We look forward to integrating it into the site.
