### ISSUE TITLE
Guide: Name Your Project

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#509]
### Overview
We need to create a guide that tells people how to choose a name for their project. 

### Action Items
- [ ] Review the Guide for "Write a Good Description"
- [ ] Draft New Guide with Examples

### Resources/Instructions
https://github.com/100Automations/Website/blob/gh-pages/_guides/writing-short-descriptions-for-automations.md

**Comment by henlatourrette** [comment]
---
title: Name your Automation
description: Tips for making a good title to help bring targeted traffic to your repository
status: active
display: true
category: 2
---

You will need to write a title about your automation so that people will understand what it is about quickly 

## Uses:
- project card on 100Automations.org website
- read.me on your repository
- announcements (linkedIn, etc.)


## Elements:
The title should have the following elements:
- Be unique
- Be descriptive
- Self explanatory
- Be a summary of the description

## Examples:
Here are three examples:

### Example 1:

> Pre-commit Hooks Starter Kit


### Example 2:

>Jekyll Gather Data Types


### Example 3:

>True GitHub Contributors

**Comment by ExperimentsInHonesty** [comment]
The Guide has been created and deployed https://100automations.org/guides/name-your-automation.html
