### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by Rabia2219** [100Automations/Website#528]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
Repeat first 3 steps for each card
- [x]  copy this template to a comment below
   ````
   ### Text from project board card, [Add name of board here], [Add name of column here]
   ```
   [PASTE CARD CONTENT HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy the content of the card (by clicking the 3 dots and selecting Edit Note, and then CRTL+C) and paste it into your new comment where it says `[PASTE CARD CONTENT HERE]
- [x] delete card from project board
- [x] add project board URL(s) in resources below
- [x] add the `project board migration` label to this issue
- [x] add issue to project board
- [x] move issue to Prioritized Backlog

#### Classic Project board URL(s):
- Open:
  - [Personas, User Stories and Journeys](https://github.com/100Automations/Website/projects/2)

- Closed:
  - [Project Management](https://github.com/100Automations/Website/projects/1)

#### New Project board URL(s):
- [100 Automations Website: Project Board](https://github.com/orgs/100Automations/projects/3)

#### Card Content Spreadsheets
- [Project Board Cards: 100 Automations: Personas, User Stories and Journeys](https://docs.google.com/spreadsheets/d/1XjkRzfoQvgHuhSA_1ftW6lHvVY34DzgOb9aOcZXCJ0k/edit)

**Comment by Rabia2219** [comment]
#### Notes

- created a spreadsheet to copy the notes from the Personas, User Stories and Journeys board, it is linked in the resources above
  - added to [wiki](https://github.com/100Automations/Website/wiki/Project-Definition-&-Roadmap#audience)

**Comment by Rabia2219** [comment]
### Text from project board card, Project Management, Resources
```
Marketing Materials

[Project One-sheet](https://docs.google.com/document/d/1Bk2uMaSdiZTKu9c-BMXSsC-Gk-ohK_NcmodQRvrgjTU/edit)
[Twitter Page](https://twitter.com/100automations)
[Facebook Page](https://www.facebook.com/100Automations)
[Instagram Page](https://www.instagram.com/100automations/?hl=en)
[Youtube Channel](https://www.youtube.com/channel/UCS_BOwZ5Hj3pGHN0gmx4gAA/?guided_help_flow=5)
[Social Media Posts and Previews, and Memes and Folder](https://drive.google.com/drive/folders/10vaCzqqoAGc6STIlYEKUZ_6y9nTjSF-n?usp=sharing)
```
- [x] Determine where this item goes on the wiki (page and section) https://github.com/100Automations/Website/wiki/Resources#marketing-materials
- [x] copy item to wiki
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Management, Resources
```
Development Resources

[Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)
[Miro Board](https://miro.com/app/board/o9J_lZziQ3g=/)
[Site Architecture Documentation](https://100automations.github.io/Architecture/)
[New Google Shared Drive](https://drive.google.com/drive/folders/1aqnB0PGT6iMgXtp-d8WHN7COzYsbUpTp?usp=sharing)
```
- [x] Determine where this item goes on the wiki (page and section) https://github.com/100Automations/Website/wiki/Resources#development-resources
- [x] copy item to wiki
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Management, Resources
```
[Project One-sheet](https://docs.google.com/document/d/1Bk2uMaSdiZTKu9c-BMXSsC-Gk-ohK_NcmodQRvrgjTU/edit)
[Twitter Page](https://twitter.com/100automations)
[Facebook Page](https://www.facebook.com/100Automations)
[Instagram Page](https://www.instagram.com/100automations/?hl=en)
[Youtube Channel](https://www.youtube.com/channel/UCS_BOwZ5Hj3pGHN0gmx4gAA/?guided_help_flow=5)
[Social Media Posts and Previews, and Memes and Folder](https://drive.google.com/drive/folders/10vaCzqqoAGc6STIlYEKUZ_6y9nTjSF-n?usp=sharing)
https://github.com/100Automations/Website/issues/94#issuecomment-753534397
```
- [x] Determine where this item goes on the wiki (page and section) - the above is a duplicate of the [Marketing Resources](https://github.com/100Automations/Website/wiki/Resources#marketing-materials)
- [x] copy item to wiki
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Management, Review
```
[Future Automations](https://github.com/100Automations/futureautomations/projects/1)
unclaimed/half-backed ideas] -> 6
New ideas Icebox -> 0
idea iteration in process -> 1
Questions for the team -> 0
automation signoff -> 0
unclaimed/prioritized backlog -> 3
in progress -> 2
in review -> 1
Done -> 2
Will not be worked on -> 1
Last Update: Jan 8th, 2022
```
- [x] Determine where this item goes on the wiki (page and section) - this card used to be updated weekly by the active project team and it lived on the project board. Since the data can't be on the project board, we have instead linked to the future automation board in the New Issue Approval column
- [ ] copy item to wiki
- [x] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
This automation is affected by the project board change.

- https://github.com/100Automations/GHA-add-issue-to-project/issues/17

![image](https://github.com/user-attachments/assets/019889f9-acf0-4a85-b509-6b3b9fa25fcb)
