### ISSUE TITLE
Write a Press Release

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#55]
### Overview
We need to write a press release for the project. We have a Press Kit page and a Press Release, Bio, and Fact Sheet section. We need to write a press release to add to it.

### Action Items
- [x] Confer with marketing team to find out what content should be included in the press release. 
- [x] Interview team members for the relevant information
- [x] Write a draft
- [x] Get it reviewed by product
- [ ] Get it reviewed by marketing

### Resources/Instructions
Slack #hfla-marketing Elle Wheeler
[Project one pager](https://drive.google.com/drive/u/0/folders/1cEhbjTTT3HLXuHUzAqnvmGLtZXKIhM8A)
[Final Press Release](https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit)

**Comment by NivenPrasad** [comment]
We need to jot down bullet points for press release, bios, fact sheets. Get bios for Kian, Sophia, Raudel, the 100 Automations team. This can then go to the marketing team.

**Comment by NivenPrasad** [comment]
Bios will have own issue cards assigned to those whose bios we need.

**Comment by nahyungkim1220** [comment]
Draft 1: https://docs.google.com/document/d/1Vi74RhpZn2U8o79iimO6KesKRaY2zip-F0ANKxTq1go/edit

**Comment by nahyungkim1220** [comment]
###  How to Write an Article About Your Automation
#### Tell your journey like it’s a story. What challenges did you run into? How did you try to tackle them? Ultimately, what resolution did you come to? 
#### Tips: Break down big chunks of information under headlines. Always give examples (snippets of code) when you can.

- **Title:** Should be short and straight to the point, preferably not longer than 20 words.
o	Title can describe what your code does (i.e.”Create a team roster with Node.js, React, and Google Sheets”)
- **Subtitle**:
o	Optional, but a very good space to summarize how your code makes your life easier: (i.e. “Create and update your team’s page with ease”) 
- **Opening paragraph**: 
o This can be short and sweet. 
o You can begin this opening with anything - add your personal touch to this opening, but make sure to relate it back to your automation. 
o You can open your article with why you began developing your project.
- **Body**: 
-	Tell the journey of how you developed your code, and break it down into different stages; 
o	What problems/issues did you see? Why did you decide to address them?
o	How did you go about overcoming the challenges? (i.e. onboarding, communication, challenges within your code)
o	How would the reader implement your automation (what preparation do they need to make? Break this down into steps.)
- **Closing:** Finally, end the article with a summary of your thoughts, possible future improvements, or what you learned from this journey.

**Comment by nahyungkim1220** [comment]
[Draft2](https://docs.google.com/document/d/1MjVkvLVDqd5v5XMQft4b4WGM-tvNA2vWwpo0z3yTlCY/edit?usp=sharing).

**Comment by nahyungkim1220** [comment]
Update (1/4/21): Elle and another marketing volunteer will look at it and get back to me by Thursday.

**Comment by nahyungkim1220** [comment]
Update: Elle gave feedback on Thursday (1/7/21). Her feedback is mostly about the title and subtitle.
[Elle's feedback in the comments](https://docs.google.com/document/d/1dlHJqM33siqfla48aewZQC_Xpz6x_b7cqN5G7bA6Ab8/edit)

Update: Draft has been revised to incorporate Elle's feedback.
Draft 4

**Comment by nahyungkim1220** [comment]
Update: Revised draft to include Bonnie's suggestions. 
Notes: This draft is written more like a news article than the previous versions. References and outline is at the bottom of the article.
[Draft 5](https://docs.google.com/document/d/1xBEWJWzyGKTI9FixGrPcY_TcZf24KOk9JP5423DTf24/edit)

**Comment by nahyungkim1220** [comment]
Update: Revised draft to Niven and Dean's feedback.
[Draft 6](https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit)

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty will review before next meeting on 1/20

**Comment by nahyungkim1220** [comment]
Bonnie's revised quotes have been added to [Draft 6](https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit).

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty will be reviewing revised version and making comments/suggestions in the doc.

**Comment by nahyungkim1220** [comment]
Paragraph 4 has now includes what 100 Automations does to share the weight of maintenance.

**Comment by nahyungkim1220** [comment]
The press release is done!! Currently looking for pictures (Logo, TGC)!

**Comment by Olivia-Chiong** [comment]
@nahyungkim1220 Use this [guide](https://github.com/100Automations/Website/issues/121#issuecomment-759843226) to get better images

**Comment by nahyungkim1220** [comment]
New zombie photo has been added!
If people don't like the photo, here are [other options](https://docs.google.com/document/d/1TavzRT1sFNvK2cm5UvkMu3dTOU2ytJ89xOg568ZL8Ys/edit?usp=sharing).
(We could also choose to not have a zombie/ intermittent photo).

**Comment by Olivia-Chiong** [comment]
Option 1
![image](https://user-images.githubusercontent.com/75456721/107863931-bcbb8180-6e0c-11eb-8bbf-c3ef42df0716.png)

Option 2
![image](https://user-images.githubusercontent.com/75456721/107863923-b0cfbf80-6e0c-11eb-8750-566db9e00989.png)

Option 3
![image](https://user-images.githubusercontent.com/75456721/107863916-a3b2d080-6e0c-11eb-939a-daae123417bf.png)

**Comment by Olivia-Chiong** [comment]
team has chosen option 2 and @Olivia-Chiong will download it for @nahyungkim1220 to include in the press release.

**Comment by Olivia-Chiong** [comment]
Image for @nahyungkim1220 action
![6h6q](https://user-images.githubusercontent.com/75456721/108914743-acf82600-75e0-11eb-8515-c8cb45fddd91.jpg)

**Comment by nahyungkim1220** [comment]
Zombie image has been added to [Draft 6](https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit).
Press release is done!

**Comment by ExperimentsInHonesty** [comment]
added a link to the final draft into issue [Marketing: Create a guide to making a press release for your open source project](https://github.com/hackforla/knowledgebase-content/issues/119)

Added this note for Henry https://github.com/hackforla/product-management/issues/134#issuecomment-787202716

This issue hackforla/marketing#55 can be closed once we confirm that all the work prescribed in above is addressed.

**Comment by henlatourrette** [comment]
I've created the new issue to collect Marketing Assets for 100 Automations here:

[Marketing Issue hackforla/marketing#36](https://github.com/hackforla/marketing/issues/36)
 
And I have added the [Press Release](https://docs.google.com/document/d/1Rr3ueR6lTIAwcDGrEqyS0HJVIjmqlGRaldrcMkCMcGA/edit) as a link from the Marketing Assets checklist.

**Comment by henlatourrette** [comment]
The press release is now on the marketing board.
