### ISSUE TITLE
Update logos on social media

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#56]
### Overview
We need to update the logos and banners on social media accounts. 

### Action Items
- [x] Update Facebook account logo
- [x] Update Facebook account background
- [x] Update Instagram account logo
- [x] Update YouTube account logo
- [x] Add YouTube account background (we don't have one yet, but we can add one)
- [x] Update GitHub account
- [x] Update Twitter account logo
- [x] Update Twitter account background

### Resources/Instructions
[Logo Variants in Figma Board](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=242%3A327)

**Comment by ExperimentsInHonesty** [comment]
![100Automations](https://user-images.githubusercontent.com/37763229/100536199-c6e9be80-31d3-11eb-8cb5-14ed5313c93f.png)

**Comment by NivenPrasad** [comment]
The logos have all been updated.

**Comment by ExperimentsInHonesty** [comment]
![100automations-hero](https://user-images.githubusercontent.com/37763229/100954644-d0bc3c00-34c9-11eb-8f89-ddae53f04b0d.png)

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad I changed my mind about how the twitter logo, its fine.  I reviewed all the other accounts and updated the todo list above.  The only items that remain are: 
Update Twitter account background
Add YouTube account background (we don't have one yet, but we can add one)

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty Twitter and YouTube backgrounds now updated.
