### ISSUE TITLE
Create an Issue Template: Suggest a Guide

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#57]
### Overview
We need to create a "Suggest a Guide" form/issue - there is a card on the website called "Suggest a Guide" that when clicked on, should take the user to this form.

### Dependency
This template issue will have to be created and then the guide can be created and the template issue edited to link to the guide page until there is a real guide on the site.

### Action Items
- [x] Create the text for template as a comment in this issue
- [x] Review with Bonnie
- [x] Create as a template in the website repo

### Resources/Instructions

**Comment by ExperimentsInHonesty** [comment]
What would the title of the guide be
Example: Write a Short Narrative Description about Your Automation

What would the description of the guide be?
Example: A good narrative description will increase targeted traffic to your repository.  This guide helps you create one.

Who needs this guide
**_insert people we serve here as a check list_**

If you have any images (screen shots or other) that you think would be helpful, please put them in this issue, and if not screen shots, please indicate licence type of image and where it came from (link).  Only images that are creative commons can be used on our site, except where the author allows non commercial use with attribution on our credits page.

Links to external resources to learn more:
Example: a link to a github tutorial or wiki file, etc.

If you have already written a guide that you would like us to publish on 100Automations, please add it here and indicate How would you like to be credited and if you want to be consulted on edits.
Name?
Github Handle?
LinkedIn profile?
etc?

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad Please add whatever else you think this needs and format how you like before creating a new template issue in the website repo.

**Comment by ExperimentsInHonesty** [comment]
- [ ] Software developers of all skill levels
- [ ] People with ideas for automation
- [ ] People looking for automations (Project Managers, Business Analysts, Portfolio Owners)
- [ ] Employers
- [ ] Open source advocates
- [ ] Product Managers

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad looking back at this, it definitely needs more formatting to be like the other guides

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty this looks good. Minor edit but I think that the "Credit" title might be better as "Credit for Published Guide" as some people with a ready automation will come looking straight for that use case and so this directs them there more quickly.

**Comment by NivenPrasad** [comment]
In progress: @NivenPrasad working on it
Blocks: none
Eta: Saturday

**Comment by NivenPrasad** [comment]
[Here is the PR](https://github.com/100Automations/Website/pull/77) to merge the template.
