### ISSUE TITLE
Create a Guide: How to suggest a guide for 100 Automations

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#58]
### Overview
We need a guide to share with people how to suggest a guide while also making sure that people don't repeat other peoples suggestions.

### Action Items
- [x] Write mark-down for the guide instructions in a comment on this issue.
- [ ] Create a mark-down file for this guide and add it to a folder called _guides
   - [ ] Call the file a name with dashes that is as short as possible
      - [x] name: suggest-guide-for-100Automations.md 
   - [x] Add the following header to the file:
```
---
title: How to suggest a guide for 100 Automations
description:  This guide will help you in the suggestion or creation of a guide for 100Automations
status: active
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
what needs to be in this guide is

**DRY**
how to find guides that are already written or have been suggested, so that you don't duplicate work:  view this link
https://github.com/100Automations/Website/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+guides%22

**Help us prioritize our backlog**
If you do find a guide suggestion in our issues, but that has not yet been worked on, feel free to add a comment indicating your desire for its creation, so we can prioritize suggestions with the most interest.

**Help us write our guides**
if there is a suggestion for a guide that is in the prioritized backlog or icebox that you would like to write something for, join our slack and let us know or paste your content directly into the issue with details about how you would like to be credited:

How would you like to be credited?
Name?
Github Handle?
LinkedIn profile?
etc?

* Credit assignment is at the 100Automations teams discretion, we will document our decision making process in the issue.  Our intention is always to provide credit where possible for work that grows the open source community.

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad please review this

**Comment by NivenPrasad** [comment]
Hi @ExperimentsInHonesty - this looks good! Here are my comments from review:

- I think it'd be helpful to let contributors know what takes place between them finishing a guide and the guide getting published on the website. E.g. "Once a guide is ready for publication, move it to the Review column where one of the 100 Automations content team will conduct a final review before the guide is published to the website."
- Potential new section:

"**Help us update an existing guide**

If you have a suggestion for update the whole or part of an existing guide, feel free to add a comment to the guide's issue, which will appear in the closed column."

This section will be dependent on keeping closed issues in the repo so that they can be re-opened for updates.

- On a more general note, I think we have to decide on whether we go with "100 Automations" or with "100Automations" throughout our media and content.

**Comment by ExperimentsInHonesty** [comment]
Niven said: 
> I think it'd be helpful to let contributors know what takes place between them finishing a guide and the guide getting published on the website. E.g. "Once a guide is ready for publication, move it to the Review column where one of the 100 Automations content team will conduct a final review before the guide is published to the website."

Bonnie response: 
People can't move things on the project board because they don't have write access.  That has to be granted one person at a time.  If someone is going to write a guide, they should connect with us on Slack.  alternately, they could write it, up as an issue and then put in PR to commit the content, which we would review and write back with comments.  Let's talk it out


> Potential new section:
> "Help us update an existing guide
> 
> If you have a suggestion for update the whole or part of an existing guide, feel free to add a comment to the guide's issue, which will appear in the closed column."
> 
> This section will be dependent on keeping closed issues in the repo so that they can be re-opened for updates.

Bonnie response:
Good catch, we should encourage people to suggest changes to the guides.  One way to do that is to put a link to the guide raw content in the guide itself, where people could propose changes by doing a PR.  We just have to verify that someone who has a github account but is not a member of our github can make a PR.

Niven said: 

> On a more general note, I think we have to decide on whether we go with "100 Automations" or with "100Automations" throughout our media and content.

Yes!

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad - 
Camilla and I met and and ended up deciding that 100 Automations  should be "100 Automations" instead of 100Automations.  I made an issue to make those changes #71

**Comment by NivenPrasad** [comment]
In progress: @NivenPrasad working on it
Blocks: none
Eta: Saturday
