### ISSUE TITLE
Identifying the OKR's 

### ISSUE THREAD

**Issue by abi-a** [100Automations/Website#6]
### Overview
We need to collaborate on identifying how best we will measure the successes using milestones and measurable results. 

### Action Items
- [x] Identify overview of steps for Niven and Bonnie to review
   - [x] Team independently reviews Abi's doc.
- [x] Meeting with Team (Bonnie, Abi and Niven)
   - [x] Drafting set of OKRs
   - [x] Abi to identify the availability of Niven and Herself via slack dialogue
   - [x] Set meeting time and invite Bonnie
- [ ] Review OKRs with Joel

### Resources 
OKR Document-https://www.whatmatters.com/articles/okrs-positive-social-change-nonprofit/

https://www.bernardmarr.com/default.asp?contentID=1456

[CfA Aug 12 workshop](https://www.youtube.com/watch?v=JNjlAEtY6Gk)

[CfA Slides from Aug 12 workshop](https://docs.google.com/presentation/d/14F6Vf3Xq6LQlU1est5QUELc4LwE0jdtqsA8Exh-FeLY/edit#slide=id.g80ce364e7f_0_0)

**Comment by ExperimentsInHonesty** [comment]
@abi-a Checking in with you to see if you will have time to work on this issue, or we should put it back in the prioritized backlog.  No pressure, just checking your status.  If you are working on this please provide update:
1. Progress: 
2. Blocks:
3. Availability:
4. Eta:

**Comment by ExperimentsInHonesty** [comment]
sent a message to @abi-a on slack.

**Comment by abi-a** [comment]
Sincere apologies. I will add above a link to a resource we can use to identify the OKRs

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty will reach out to CfA to find out if they can provide some guidance:
- Article: https://www.whatmatters.com/articles/code-for-america-okrs-local-government/

**Comment by NivenPrasad** [comment]
[Current working OKRs document](https://docs.google.com/document/d/1ZeLLdg8fwkWyr9IRF2UqMRoI94JVGyJrMeU73CmSFa4/edit#)

**Comment by NivenPrasad** [comment]
Hi @ExperimentsInHonesty, I requested the CfA workshop recording and slides on OKRs from CfA - have posted the links under Resources in this issue

**Comment by NivenPrasad** [comment]
[Reviewed and updated document](https://docs.google.com/document/d/1ZeLLdg8fwkWyr9IRF2UqMRoI94JVGyJrMeU73CmSFa4/edit#)

**Comment by NivenPrasad** [comment]
@NivenPrasad turn Google Doc into HfLA template:
https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616

**Comment by NivenPrasad** [comment]
New [OKRs Google Sheet for 100 Automations](https://docs.google.com/spreadsheets/d/178wkyjmXPQ8PPM8jjWElUQ0qEcsvzaa12IEAlwYf_uA/edit?usp=drive_web&ouid=115147153382252034796)

**Comment by Olivia-Chiong** [comment]
@Olivia-Chiong To pull list of issues and identify the issues missing from OKRs. Go through list of missing issues with the team at the next meeting.

**Comment by Olivia-Chiong** [comment]
[Issues spreadsheet](https://docs.google.com/spreadsheets/d/1p9clOgYQPTqFHFEammGqtM13MDzZVm8N3wYF_VJmCqA/edit#gid=0) created and ready for review.

**Comment by Olivia-Chiong** [comment]
Progress: Working on the Zapier integration for the OKRs sheet
Blocks: Trying to get it to add AND update the sheet when issues get closed
Availability: Some
ETA: Need a week to do this, so likely 1/20

**Comment by Olivia-Chiong** [comment]
I would like to have a Product discussion on whether our Key Results are reflective of the work we are doing and how many of the tasks we are doing seem to fall into one single bucket. It seems to me we may want to keep the Objectives but break Key Results into smaller, more well defined results so that the tasks are better spread out over various OKRs.

**Comment by NivenPrasad** [comment]
Revised the OKR schedule to include a new KR called "Build a well functioning website design, development and product team by December 15, 2020". This breaks up the "Launch 100 Automations" KR and some the personnel related tasks to flow into this new KR.

**Comment by superbunker** [comment]
Does this still need to be open?

**Comment by henlatourrette** [comment]
It looks fine and useful. We may need to update them since we didn't fulfill the time-based objectives but the OKR are good.
