### ISSUE TITLE
Create an Issue Template: Write Bio - [INSERT TYPE]: [INSERT NAME]

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#61]
### Overview
Create an Issue Template to request a bio from people we want to profile on the site (content creators, site builders, mentors, etc.).

### Dependency
Write a guide about how to write the bio and identify motivations #62 

### Action Items
- [ ] Create two templates 
   - [x] Template #1 - Content Creator
      - [x] Specify Default title of issue is: Write Bio - Content Creator: [INSERT NAME]
      - [x] Customize content
   - [x] Template #2 - Site Builder
      - [x] Specify Default title of issue is: Write Bio - Site Builder: [INSERT NAME]
      - [x] Customize content
   - [x] Specify Default labels: Content Writing, Marketing
   - [ ] Add a link on both templates to the guide

**Comment by ExperimentsInHonesty** [comment]
TEMPLATE #1 - Content Creator

Default title of issue is: Write Bio - Content Creator: [INSERT NAME]

Default labels: 

-----

### Name

### Bio
_A 1-2 paragraph professional bio_
 
### Quote 
_A quote from you about automations_

### Motivations
_What are your internal motivations for creating an automation?_

_What are your external motivations for creating an automation?_

### Picture

_Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by ExperimentsInHonesty** [comment]
TEMPLATE #1 - Site Builder

Default title of issue is: Write Bio - Site Builder: [INSERT NAME]

Default labels: 

-----

### Name

### Bio
_A 1-2 paragraph professional bio_
 
### Quote 
_A quote from you about automations_

### Motivations
_What are your internal motivations for creating the 100 Automations site?_

_What are your external motivations for creating the 100 Automations site?_

### Picture

_Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by NivenPrasad** [comment]
[Pull request for Content Creator Bio Template](https://github.com/100Automations/Website/pull/68)

**Comment by NivenPrasad** [comment]
Here is the [Pull request for the Site Builder Bio Template](https://github.com/100Automations/Website/pull/69)

**Comment by NivenPrasad** [comment]
Templates have been created.
