### ISSUE TITLE
Create a Guide: Write your Open Source Automation Creator Bio

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#62]
### Overview
We need to create website content with a mark-down approach so that development can be easily updated. This is the issue to create a mark-down file for the "Write your Open Source Automation Creator Bio " guide.

### Action Items
- [ ] Write mark-down for the guide instructions in a comment on this issue.
- [ ] Create a mark-down file for this guide and add it to a folder called _guides
   - [ ] Call the file a name with dashes that is as short as possible
      - [ ] name: write-your-opensource-automation-creator-bio.md
   - [ ] Add the following header to the file:
```
---
title: Write your Open Source Automation Creator Bio
description: People want to know the authors behind automations on our site, writing a good bio is easy once you know what to cover.
status: coming soon
display: true
---
```

### Resources/Instructions
[Figma Board for 100 Automations Website Design](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=0%3A1)
Content for Bio Pages Issue #86

**Comment by ExperimentsInHonesty** [comment]
---
title: Write your Open Source Automation Creator Bio
description: People want to know the authors behind automations on our site, writing a good bio is easy once you know what to cover.
status: coming soon
display: true
---
# Write your Open Source Automation Creator Bio

## Instructions
This is what we’ll need from you so that we can promote you in our marketing efforts.

- [Name](#name)
- [Bio](#bio)
- [Quote](#question)
- [Motivations](#motivations)
- [Picture](#picture)
---

<a name="name"></a>
## Name
How would you like your name to appear on the website?

---
<a name="bio"></a>
##  Bio

### Uses:
- Developers can find and collaborate with you
- Content for your LinkedIn profile About section
- Information for employers visiting 100 Automations
- Speaker's bio if you land a speaking engagement

### Elements:
Your bio should have the following elements:

- Summary: Highlight your contributions at 100 Automations or Hack for LA. You can also show off your achievements, put your career choices in context, or show off your personality.
- Technical and Soft Skills: Highlight technologies used in your automations as well as your collaborative skills.
- Socials: Where can developers or recruiters reach you?

### Examples:
Here are two examples:

**Example 1: [Sophia Alice](https://www.linkedin.com/in/sophia-alice/)**
>Hi, my name is Sophia and I'm a data scientist and engineer from Philadelphia. I enjoy working with data in every step of the process, from ingestion to visualization, with an emphasis on machine learning. I'm the co-leader of the Hack for LA data science community of practice.
>
>You can see my skills and connect with me on [LinkedIn](https://www.linkedin.com/in/sophia-alice/), or check out my code on [GitHub](https://github.com/salice).
>For any other inquiries, please feel free to [Email](mailto:sophiaalice@protonmail.com) me.

**Includes:**
- A brief summary of background, interests, and strengths
- Your involvement in open-source communities or 100 Automations. If you contributed to any automations, briefly mention them and your role.
- Links to professional socials

**Does not include:**
- An expansive life story; the Bio is a place for brief first impressions
- Personal socials; keep your Bio professional
- A copy-paste of your resume


**Example 2: [Tim Malstead](https://www.linkedin.com/in/timmalstead/)**

> I am a full-stack software engineer and designer seeking to help make the world a more just and equitable place through the use of beautiful, intuitive and helpful software. My goal is to create software that helps solve tough problems for real people. I approach each project with a careful eye toward design, ease of use and performance. You can find me on the Home Unite Us and Food Oasis Los Angeles projects at Hack for LA.
> 
> TECHNICAL SKILLS:
> Front End: HTML5, CSS3, React, Next.js
> Back End: Express, Flask, Node.JS, AWS, Firebase
> Programming Languages: JavaScript, TypeScript, Python
>To see more of my technical skills, frameworks, languages, please go to my [LinkedIn](https://www.linkedin.com/in/timmalstead/) profile.
>
> SOFT SKILLS:
> Communication, Empathy, Time-management
> 
> I love collaborating with others. Let's get in touch! [GitHub](https://github.com/timmalstead) |  [LinkedIn](https://www.linkedin.com/in/timmalstead/) | [My Website](https://timmalstead.com/)

**Includes:**
- Your larger goals (personal and or professional)
- Your working / problem-solving style
- A list of technical and soft skills

**Does not include:**
- An encompassing list of all your skills.
Reason: The Bio should provide a brief view of who you are on 100 Automations. Try to keep the list no longer than 5 items.  To provide an encompassing view of your skills, provide your LinkedIn.

---
 <a name="quote"></a>
###  Quote 
A quote from you about automations. Add your personal flair!

**Example 1:**

> "Automations allow us to focus on being productive instead of busy.”

---
 <a name="motivations"></a>
### Motivations
#### Personal/ Englightend Self-interest (Internal Motivation): 
What personally motivates you to create automations and contribute to our platform? 
 (e.g. to grow certain skills, increase visibility, give back to the community, etc.)

**Example 1:**

> I'm motivated by my drive to grow as a developer – I want to strengthen my skills in Python and Jekyll, and I want to learn how to write good, clean code by contributing to a platform with high standards. I also want to work with like-minded people who use and want to improve open-source code.

#### Community Impact (External Motivation): 
What around you motivates you to create automations for the open-source community? Was it out of annoyance or need? 

**Example 1:**

> In 2020, the pandemic drove us to work at home, and we spent more hours on open-source work. But how do we make our work sustainable over the long run? Automations will help us achieve efficiency in open-source collaborations.
---
<a name="picture"></a>
###  Picture
Can we use your LinkedIn profile picture? If yes, please provide your LinkedIn URL.

A good profile picture is a:
- High-resolution image 
- Professional headshot
- Recent (it needs to look like you)

Here are [10 Tips for Picking the Right LinkedIn Profile Picture](https://business.linkedin.com/talent-solutions/blog/2014/12/5-tips-for-picking-the-right-linkedin-profile-picture).

---
#### END
---
To propose/submit changes to this guide please [edit]() the markdown file for this guide

**Comment by nahyungkim1220** [comment]
Update: I assigned myself to this card(?).

I am currently researching
- What recruiters are looking for in developers
- What software engineers' LinkedIn profiles look like.

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty will provide some LinkedIn profiles for reference

**Comment by ExperimentsInHonesty** [comment]
Tim Malstead:
https://www.linkedin.com/in/timmalstead/
I am a full stack software engineer and designer seeking to help make the world a more just and equitable place through the use of beautiful, intuitive and helpful software. My goal is to create software that helps solve tough problems for real people. I approach each project with a careful eye toward design, ease of use and performance.

**Comment by nahyungkim1220** [comment]
Update: 
- Added to Bio Example 1 & description (Includes & Does not include)
- Added Quote Examples
- Expanded on Motivation descriptions & added examples

**Comment by nahyungkim1220** [comment]
Update:
- Revised draft to feedback (Bio's are for developer collaboration, not outside parties)

**Comment by NivenPrasad** [comment]
#### Notes on Motivation Part:
Community impact motivation (external) vs personal/enlightened self interest motivation (internal)

**Comment by NivenPrasad** [comment]
List technologies used on 100 Automations automations. To see more of my technical skills, frameworks, languages, please go to my LinkedIn profile.

**Comment by nahyungkim1220** [comment]
Updates: 
- Included brief description of automations Sophia worked on in her Bio
- Directions on including a list of skills in Bio

Next steps: chat with Sophia and Tim and fact-check with them

**Comment by nahyungkim1220** [comment]
Update: Changed Bio to include their open-source volunteer activities (suggestion: the bios can be updated to include automation writing experience when we have more automation authors).

**Comment by nahyungkim1220** [comment]
Issue #62 - need to contact Kian for his bio example

**Comment by nahyungkim1220** [comment]
Heard back from Sophia! Updated her example. Currently getting in touch with Kian for one example of how someone would talk about their automation.

**Comment by Olivia-Chiong** [comment]
PR approved and merged.
