### ISSUE TITLE
Create social media accounts for 100automations

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#7]
### Overview
Create social media accounts for 100automations.

### Action Items
Set up accounts for:

- [x] Twitter
- [x] Instagram
- [x] Facebook

**Comment by NivenPrasad** [comment]
Social media accounts now set up - view here:

Twitter: https://twitter.com/100automations
Instagram: https://www.instagram.com/100automations/?hl=en
Facebook (Page): https://www.facebook.com/100automations-110926860687433/?modal=admin_todo_tour

@ExperimentsInHonesty 3 things to discuss: 

1. Where to deposit login info/passwords for these profiles
2. Okay to make you an admin for the Facebook page?
3. Any particular goals for these pages over the next month/2 months/3 months and how much time/resource to dedicate to these

**Comment by ExperimentsInHonesty** [comment]
Hi @NivenPrasad I removed the label good first issue.  That label is for issues that a novice who is joining your project can do, not for PM issues.

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad sure make me an additional admin on the facebook.

**Comment by ExperimentsInHonesty** [comment]
Here is the logo
![100automationslogo](https://user-images.githubusercontent.com/37763229/87234895-58be6f80-c38a-11ea-86d6-2bc359f81beb.png)

**Comment by ExperimentsInHonesty** [comment]
Initial setup completed.
