### ISSUE TITLE
Fix all instances of title of project: 100 Automations

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#71]
### Overview
We need to use the title consistently throughout the project.

### Action Item
Identify where the title is being used incorrectly and make changes
- [x] Readme
- [x] Issues
- [x] Meme

**Comment by NivenPrasad** [comment]
[Pull request for changes to readme](https://github.com/100Automations/Website/pull/92)

**Comment by NivenPrasad** [comment]
ReadMe and issues updated. Just need to update one meme with help of @CamilaArias

**Comment by Olivia-Chiong** [comment]
Meme updated.
