### ISSUE TITLE
Create a Wiki

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#74]
### Overview

We need to create a Wiki for the 100 Automations website development team.

### Action Items

- [x] Create a Wiki
- [x] Review with team
- [x] Implement the Wiki

### Resources
[Hack for LA Website Wiki](https://github.com/hackforla/website/wiki)

**Comment by Olivia-Chiong** [comment]
Currently studying Wikis of other teams.

**Comment by Olivia-Chiong** [comment]
I've refined the Wiki and it is ready for review.
