### ISSUE TITLE
Update Readme for website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#8]
### Overview
Readme needs an update so that people thinking about joining our project know how to contribute.

### Action Items

- [x] Review the readme resource and figure out what we can include in ours.  Also look at the one for civic opportunity as an example
- [x] Update our readme
- [x] Send to Bonnie for review

### Resources/Instructions
[Hack for LA's default readme](https://github.com/hackforla/.github) 
[civic opportunity readme](https://github.com/hackforla/civic-opportunity)
[hackforla.org website readme](https://github.com/hackforla/website)

**Comment by NivenPrasad** [comment]
Hi @ExperimentsInHonesty here is the [draft ReadMe for Website repo](https://docs.google.com/document/d/1Y4MpA5AscYJg7t6VcPVbRO_5iwwIdJWE1RYu7zjgSKU/edit#) for your review.

**Comment by ExperimentsInHonesty** [comment]
here is the ops slack channel link: https://hackforla.slack.com/archives/CV7QGL66B

**Comment by ExperimentsInHonesty** [comment]
@NivenPrasad after current changes.  go ahead and make it live.

**Comment by NivenPrasad** [comment]
@ExperimentsInHonesty current changes made and now moving issue to Done.

**Comment by NivenPrasad** [comment]
Waiting for automation template issue #13 to get resolved. Once that happens, update link in ReadMe to the template.

**Comment by NivenPrasad** [comment]
Closing this issue because initial launch of ReadMe is done.
