### ISSUE TITLE
Investigate other tools for social media image sharing

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#87]
### OVERVIEW
We need to find a tool that allows images to be shared to social media including pre-defined text.

### ACTION ITEMS
Research for a tool that shares images individually and allows for customization of pre-defined text.

**Comment by Olivia-Chiong** [comment]
Update from @mdothman 

Image sharing tools are out there, but facebook has placed a few obstacles.

Cont. og meta tags (og stands for Open Graph) were introduced by facebook, and since 2019 they no longer accept arbitrary values given for title, description and image. Facebook does a page crawl before compiling a graph composed from og meta tags. That is how facebook shares, and the tool I am looking for will overcome those obstacles to customize our image share.

ShareThis has a widget you can modify to overcome open graph protocol tags. Jekyll also has share buttons you can install.

Image sharing one image on a page is feasible if the image is a jekyll post.

**Comment by mdothman** [comment]
# Image Sharing report

## Overview

Meta tags are used by facebook page crawler. This can be used to our advantage given site structure. We want to have a carousel of images with pop-up share and download buttons. If this site wants to be constructed optimally we are going to turn those images into buttons with background preview images.

The background image of the link to the post will be that post. When the user clicks on the image, it will go to the post, and from there we can share the post with ShareThis.

**Comment by Olivia-Chiong** [comment]
Based on the analysis, if we want people to share memes from our site, each meme will have to have its own landing page.
