### ISSUE TITLE
Write Bio - Site Builder: Muhi-Dean Othman

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#88]
### Overview
We need some info to put on our site about you, so that we can highlight your participation.

### Action item
- [ ] Provide 
   - [ ] Name
   - [ ] Bio: _A 1-2 paragraph professional bio_
   - [ ] Quote:  _A quote from you about automations_
   - [ ] Motivations
      - [ ] Internal:  _What are your internal motivations for creating the 100 Automations site?_
      - [ ] External: _What are your external motivations for creating the 100 Automations site?_
   - [ ] Picture - _Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by mdothman** [comment]
# Muhi-Dean Othman

## Static Site Architect

I am a full-stack web developer who is dedicated to creating cutting edge interface friendly applications.  I tested out of high school at 16 from Fountain Valley High School. I transferred to the University of California Davis in 2013, and left in 2015. I worked mostly part-time jobs in retail.

In 2019 I decided I would pursue a career in web development. I wanted a career change that was challenging and exciting, but I found service design to be my top priority. I received my certificate from The University of California, Irvine for web development in the middle of a pandemic, May 2020.

Now I am creating *100 Automations* with my Hack4LA team to utilize my skills in web development and my knowledge of politics and government. I am attending the University of California, Davis, and I am expected to graduate  March 19, 2021 with a Bachelors in Arts Political Science.  

## Motivations

### **External**

* Gain more experience in web development
* Connect with my community.
* Receiving feedback and criticism

### **Internal**

* Learning new skills and information
* Improving where I can
* Work ethic
* Focused on customer experience and quality design.

[LinkedIn Profile](https://www.linkedin.com/in/muhi-dean-othman/)
