### ISSUE TITLE
Write Bio - Site Builder: Audrey Kim

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#91]
### Overview
We need some info to put on our site about you, so that we can highlight your contributions.
### Action item
- [x] Provide 
   - [x] Name
   - [x] Bio: _A 1-2 paragraph professional bio_
   - [x] Quote:  _A quote from you about automations_
   - [x] Motivations
      - [x] Internal:  _What are your internal motivations for creating the 100 Automations site?_
      - [x] External: _What are your external motivations for creating the 100 Automations site?_
   - [x] Picture - _Can we use your LinkedIn pic? If yes, please provide your LinkedIn URL_

**Comment by nahyungkim1220** [comment]
### Name
Audrey N. Kim

**Bio:** Hi, my name is Audrey and I'm a Content Writer at 100 Automations. I'm a recent grad from UC Berkeley (Go Bears!) with a BA in English who is curious about tech and communication. Before graduating, I worked at HarperOne as an Editorial Intern, and worked as a writing tutor teaching ESL students. I'm excited to get to work with others to make a positive contribution to my community!

**Quote:** I'll be honest: I'm lazy, so I always end up looking for ways to work efficiently. I hope 100Automations will be of help for people like me, who want to make an impact on the world while saving time!

### Motivations
**Internal:** 
Going to school at Cal, I was always surrounded by tech world, but never totally immersed in it. I'm curious about tech and communication, so it's exciting to be part of a project that brings the two together. 

**External:** What are your external motivations for building the site?
I want to be of help to my community whilst strengthening the skills I have. Being a part of this project as the content writer has allowed me to think more closely about how people interact with words on the web, and media's role in volunteer organizations. I hope to help spread 100Automation's positive influence to the open source and greater world!

**Picture:** Yes
linkedin.com/in/audreynkim
