### ISSUE TITLE
Make a list of memes that can be used for Press Releases

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#94]
### Overview
Make a list of memes that can be used for press releases so we can plan for project information to be distributed in a strategic manner.

### Action Items
- [x] Review the memes located in the Figma
- [ ] Make a shortlist of memes that are suitable to be turned into Press Releases and include talking points linked to goals in product one page
- [ ] Review with the team

### Resources/Instructions
[Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=951%3A223)
[Project One Page](https://docs.google.com/document/d/1hBKdHr5jhagXruEgykQa2DU8xH1Tp_GVhnDIrHQiYmk/edit?usp=sharing)

**Comment by nahyungkim1220** [comment]
Maybe we can write about addressing this issue:
- When you find an automation that does exactly what you’ve been working on for months

These could go into an article about the diff. guides/help our website provides:
- When you've got the best idea for an automation, but you're not a developer
- Spent 4 months writing code; Received 0 github stars 
- Joining an open-source project where none of the code is reusable/unclear
- You might need peer review on this one (creating a community peer reviewers for your automation)

**Comment by Olivia-Chiong** [comment]
For each of the above articles, Product needs to come up with the process.

Process for Press Releases should be Objective -> Guide -> Metric -> Press Release. 

When you've got the best idea for an automation, but you're not a developer
- Non developer's guide to writing an automation proposal 

Spent 4 months writing code; Received 0 github stars
- How to publicize your automation

Joining an open-source project where none of the code is reusable/unclear
- Putting in place clear quality control for code

You might need peer review on this one (creating a community peer reviewers for your automation)
- Better code is written by a community of people who are supporting each other to maintain quality standards (here's how to get a peer review at 100 automations)

**Comment by Olivia-Chiong** [comment]
Objective: Get more people to submit automation ideas
Guide: Non developer's guide to writing an automation proposal
Metric: 50 new automation ideas in futureautomations by 6 months after launch
Press Release: When you've got the best idea for an automation, but you're not a developer

Objective: Build a community of people who writing better code by supporting each other to maintain quality standards and mentorship
Guide: How to get a peer review at 100 automations
Metric: Have 25 automations with help wanted: peer review label by six months after launch
Press Release: You might need peer review on this one (creating a community peer reviewers for your automation)

Objective: Help automation developers to promote and get credit for their automations
Guide: How to publicize your automation
Metric: Automations listed on 100 Automations have average of 10 github stars by six months after launch
Press Release: Spent 4 months writing code; Received 0 github stars
(reference: https://opensource.stackexchange.com/questions/5110/github-stars-is-a-very-useful-metric-but-for-what)

Objective: Having standardised ESLint/Code Climate (other testing modules) in place for all automations
Guide: Putting in place clear quality control for code
Metric: All automations published should pass standard testing at 100 Automations
Press Release: Joining an open-source project where none of the code is reusable/unclear
