### ISSUE TITLE
Confirm MVP for the Press Kit Page

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#97]
### Overview

We need confirm the MVP for press kit page.

### Action Items

- [x] Product to come up with requirements for what this looks like
- [x] Review with team
- [x] Design to mock up changes
- [x] Review current press kit page with team
- [x] Create issue for any changes 
- [x] Finalize for mvp

### Resources

[Press Kit Page](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=791%3A30)

**Comment by NivenPrasad** [comment]
Press Kit page - team confirmed design is good for MVP.
Next step: Bio Page - @CamilaArias and @susantangux to mock up modal for "View Bio" button

**Comment by henlatourrette** [comment]
To just download the Memes images is fine for MVP - instead of each image taking us to a specific page for each image.

**Comment by henlatourrette** [comment]
Regarding the Press Releases, we would create a list with the "Date, Title, Read, Download" options. "Read" would take the users to a simple page and they would have the option to download it from there as well. @CamilaArias will do a design for this.

**Comment by CamilaArias** [comment]
Here's the design with the PR list - https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2652%3A2008

And the press release page with specs - https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=2777%3A388

both for desktop

**Comment by superbunker** [comment]
Lookin' close worthy!
