### ISSUE TITLE
Create issue on marketing board for press release review

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#99]
### Overview
We need to get marketing to review our draft press release by creating an issue on the marketing board.

### Action Items
- [ ] Bonnie to create an issue on the marketing board to get their review on our draft press release

### Resources/Instructions
[Draft press 100 Automations release issue](https://github.com/100Automations/Website/issues/55)
[Draft 100 Automations press release Google Doc](https://docs.google.com/document/d/1Vi74RhpZn2U8o79iimO6KesKRaY2zip-F0ANKxTq1go/edit)

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/marketing/issues/9
